### ISSUE TITLE
Traceback error in docker-compose

### ISSUE THREAD

**Issue by rusrushal13** [zenodo/zenodo#1001]
I am constantly getting traceback error for docker-compose up
https://gist.github.com/rusrushal13/ef25121346c8e88e845841e4d4b20d00
Can anybody help me regarding this?

**Comment by krzysztof** [comment]
Try this: https://github.com/ipython/ipython/issues/5911

**Comment by rusrushal13** [comment]
It is already there.
`Requirement already satisfied: backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages`

**Comment by rajat1994** [comment]
did you install tornado?.....  @rusrushal13

**Comment by rusrushal13** [comment]
@rajat1994 Is it required?

**Comment by rajat1994** [comment]
you can try...  install it  in your virtualenv

**Comment by rusrushal13** [comment]
installing it globally doesn't help out.

**Comment by rajat1994** [comment]
@rusrushal13 .... try uninstalling and installing it again  " backports.ssl_match_hostname"  ... like you did the last time with your other packages.

**Comment by rusrushal13** [comment]
It worked. :+1: 
Thanks @rajat1994

**Comment by krzysztof** [comment]
How did you install docker-compose ? with pip? can you reinstall it? it looks like a missing dependency (probably due to previous ``uninstall`` command I have suggested to you ;p )

**Comment by myheed** [comment]
sudo pip uninstall backports.ssl_match_hostname
sudo pip install backports.ssl_match_hostname
