### ISSUE TITLE
ui: css overflow issue in records

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#101]
![overflow](https://cloud.githubusercontent.com/assets/1698163/5628991/883ac9f8-95ae-11e4-92cf-1eb9ba66ebc2.png)

**Comment by bouzlibop** [comment]
After applying proposed changes:
![checking long relates zenodo](https://cloud.githubusercontent.com/assets/8625570/7249166/a3d35614-e818-11e4-98c3-25ec6acc13af.png)
