### ISSUE TITLE
Internal server error, while trying to upload a file into Zenodo 3

### ISSUE THREAD

**Issue by cafexpreso** [zenodo/zenodo#1014]
Mar 13 14:01:24 invtest01 zenodo: [2017-03-13 14:01:24,934] ERROR in app: Exception on /deposit/depositions/45467/actions/publish [POST]
Mar 13 14:01:24 invtest01 zenodo: Traceback (most recent call last):
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
Mar 13 14:01:24 invtest01 zenodo: response = self.full_dispatch_request()
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
Mar 13 14:01:24 invtest01 zenodo: rv = self.handle_user_exception(e)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
Mar 13 14:01:24 invtest01 zenodo: return cors_after_request(app.make_response(f(args, kwargs)))
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
Mar 13 14:01:24 invtest01 zenodo: reraise(exc_type, exc_value, tb)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
Mar 13 14:01:24 invtest01 zenodo: rv = self.dispatch_request()
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
Mar 13 14:01:24 invtest01 zenodo: return self.view_functions[rule.endpoint](req.view_args)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/views.py", line 84, in view
Mar 13 14:01:24 invtest01 zenodo: return self.dispatch_request(args, kwargs)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_rest/views.py", line 215, in dispatch_request
Mar 13 14:01:24 invtest01 zenodo: *args, kwargs
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
Mar 13 14:01:24 invtest01 zenodo: return meth(args, **kwargs)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_records_rest/views.py", line 296, in inner
Mar 13 14:01:24 invtest01 zenodo: return f(self, pid=pid, record=record, args, kwargs)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_records_rest/views.py", line 340, in need_record_permission_decorator
Mar 13 14:01:24 invtest01 zenodo: return f(self, record=record, *args, kwargs)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/inveniodeposit/views/rest.py", line 215, in post
Mar 13 14:01:24 invtest01 zenodo: record = getattr(record, action)(pid=pid)
Mar 13 14:01:24 invtest01 zenodo: File "/root/src/zenodo/zenodo/modules/deposit/api.py", line 375, in publish
Mar 13 14:01:24 invtest01 zenodo: deposit = super(ZenodoDeposit, self).publish(pid, id)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_deposit/api.py", line 99, in wrapper
Mar 13 14:01:24 invtest01 zenodo: return method(self, args, *kwargs)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_deposit/api.py", line 341, in publish
Mar 13 14:01:24 invtest01 zenodo: self._publishnew(id=id_)
Mar 13 14:01:24 invtest01 zenodo: File "/root/src/zenodo/zenodo/modules/deposit/api.py", line 289, in _publish_new
Mar 13 14:01:24 invtest01 zenodo: self._create_inclusion_requests(new_ir_comms | auto_request, record)
Mar 13 14:01:24 invtest01 zenodo: File "/root/src/zenodo/zenodo/modules/deposit/api.py", line 131, in _create_inclusion_requests
Mar 13 14:01:24 invtest01 zenodo: InclusionRequest.create(comm, record)
Mar 13 14:01:24 invtest01 zenodo: File "/opt/.virtualenv/zenodo/lib/python2.7/site-packages/invenio_communities/models.py", line 124, in create
Mar 13 14:01:24 invtest01 zenodo: if community.has_record(record):
Mar 13 14:01:24 invtest01 zenodo: Attr

**Comment by krzysztof** [comment]
Are you requesting for the record to be added to any communities?
What metadata are you entering?

**Comment by cafexpreso** [comment]
Yes. I could do this before. It is just a txt file, basic metadata
information, open access, CC-0 a test community definition.

**Comment by cafexpreso** [comment]
Hi 

I got the mail to curate the upload but this do no appear into the community curation page

**Comment by cafexpreso** [comment]
This started  to happen after deletion of Zenodo community

**Comment by cafexpreso** [comment]
Actually I can upload the file but I cannot publish it. It comes with internal server error.

**Comment by cafexpreso** [comment]
From elk I can see this type of errors
[indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"sort": [{"_created": {"order": "desc"}}], "query": {"bool": {"filter": [{"terms": {"communities": ["carloscomm"]}}]}}, "from": 0, "aggs": {"keywords": {"terms": {"field": "keywords"}}, "file_type": {"terms": {"field": "filetype"}}, "type": {"terms": {"field": "resource_type.type"}, "aggs": {"subtype": {"terms": {"field": "resource_type.subtype"}}}}, "access_right": {"terms": {"field": "access_right"}}}, "size": 10}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];
Caused by: SearchParseException[failed to parse search source [{"sort": [{"_created": {"order": "desc"}}], "query": {"bool": {"filter": [{"terms": {"communities": ["carloscomm"]}}]}}, "from": 0, "aggs": {"keywords": {"terms": {"field": "keywords"}}, "file_type": {"terms": {"field": "filetype"}}, "type": {"terms": {"field": "resource_type.type"}, "aggs": {"subtype": {"terms": {"field": "resource_type.subtype"}}}}, "access_right": {"terms": {"field": "access_right"}}}, "size": 10}]]; nested: SearchParseException[No mapping found for [_created] in order to sort on];

**Comment by krzysztof** [comment]
> This started to happen after deletion of Zenodo community

You will have to change those two config values to empty dictionaries if you remove the communities:

https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/config.py#L37-L40

**Comment by cafexpreso** [comment]
Ok thank you I will try this
