### ISSUE TITLE
github: display username or userID of the person currently holding the webhook.

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1018]
Some users are finding it difficult to to find who is currently "owning" the repository on GitHub in their organization.
Perhaps we should display the username of the current holder?

**Comment by slint** [comment]
The only issue I see with that is that we'll have to perform a separate db query to RemoteAccounts to get the GitHub username of the repo's owner from `extra_data`:
```
# In the GitHub settings index view
for repo in repos:
    if repo.user.id != current_user.id:
        repo_owner_name = GitHubAPI(user_id=repo.user.id).account.extra_data.get('login')
        ...
```

Maybe this is optimizable though with some custom join inside the view function...
A viable alternative is to "cache" the owner of the repo hook in `extra_data` as part of syncing, thus doing all the heavy work "on demand" only.

**Comment by lnielsen** [comment]
Let's fix instead by adding better support for multiple users as needed by the AAS grant.
