### ISSUE TITLE
global: footer menu update (about + status)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1021]
We should add https://status.zenodo.org in the lower right corner next to privacy policy.

Also the about menu I think should be updated:

About
General Policies
Infrastructure
Principles
Contact

**Comment by rusrushal13** [comment]
@lnielsen I want to start with this issue. Can you guide me to the modules which one should I change?

**Comment by krzysztof** [comment]
Hey @rusrushal13 

All changes should go here:
https://github.com/zenodo/zenodo/blob/master/zenodo/modules/theme/templates/zenodo_theme/footer.html

The "About" sublinks that Lars mentions are here: http://about.zenodo.org/

**Comment by rusrushal13** [comment]
@krzysztof #1022 please review it.
