### ISSUE TITLE
Internal server Error

### ISSUE THREAD

**Issue by kishansag** [zenodo/zenodo#1028]
I am getting internal server error on running this [test](https://gist.github.com/kishansag/d36a56422639310956da90f013730b25). 
Error displayed can be seen over [here](https://gist.github.com/kishansag/46e4a5e33656d7cf04ada45412ca2493)
If you can replicate the error please let me know

![screenshot from 2017-03-23 11-50-02](https://cloud.githubusercontent.com/assets/10185999/24234536/e6cac112-0fbe-11e7-9600-81d93102d08c.png)

**Comment by rajat1994** [comment]
@kishansag ... use ipdb to debug your code

**Comment by lnielsen** [comment]
I can't reproduce the problem. Please re-open if you find the root cause of the error.
