### ISSUE TITLE
records: sub/super script in record title

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#103]
![zenodo](https://cloud.githubusercontent.com/assets/1698163/5642775/bb43fa3a-964f-11e4-8a30-a05fb9d5508a.png)

vs

![zenodo2](https://cloud.githubusercontent.com/assets/1698163/5642777/bd134974-964f-11e4-8766-693043912428.png)

https://zenodo.org/record/11146

**Comment by lnielsen** [comment]
Seemed like caching issue, but subscript still not displayed nicely.

**Comment by bouzlibop** [comment]
@lnielsen, I've just tested this issue in Chrome (v39) and Firefox (v35) and both super- and subscripts are displayed correctly:

![script](https://cloud.githubusercontent.com/assets/8625570/5801137/ef5edf50-9fe7-11e4-8ae5-5c14f5c8a208.png)

**Comment by lnielsen** [comment]
Apparently a Safari only problem.

**Comment by bouzlibop** [comment]
I'm not sure how the title is generated, but maybe it'd be worth to introduce the `<sup>` and `<sub>` tags instead of what there is now.
