### ISSUE TITLE
REST API links redirecting to http://developers.zenodo.org 

### ISSUE THREAD

**Issue by cafexpreso** [zenodo/zenodo#1051]
Hello, this link This link https://invenioinstall/dev routes the request to http://developers.zenodo.org instead of the API pages hosted locally, I had set to FRONTPAGE_ENDPOINT  this seems not to be working.

{%- set BASE_URL = url_for(FRONTPAGE_ENDPOINT, _external=True, _scheme='https') %} {%- macro panel_start(title, title_small, num, anchor) %}

{{title}}{% if title_small %} {{title_small}}{% endif %}

{%- endmacro %} {%- macro panel_end() %}

{%- endmacro %} {%- macro examples_start(id) %} Example

**Comment by cafexpreso** [comment]
It seems that is related to the redirector module
REDIRECTOR_EXTERNAL_REDIRECTS = [
    ['/dev', 'dev', 'http://developers.zenodo.org'],
    ['/faq', 'faq', 'http://help.zenodo.org'],
    ['/features', 'features', 'http://help.zenodo.org/features/'],
    ['/whatsnew', 'whatsnew', 'http://help.zenodo.org/whatsnew/'],
    ['/about', 'about', 'http://about.zenodo.org'],
    ['/contact', 'contact', 'http://about.zenodo.org/contact/'],
    ['/policies', 'policies', 'http://about.zenodo.org/policies/'],
    ['/privacy-policy', 'privacy-policy',
     'http://about.zenodo.org/privacy-policy/'],
   ['/terms', 'terms', 'http://about.zenodo.org/terms/'],
    ['/support', 'support', 'http://about.zenodo.org/contact/'],
    ['/donate', 'donate', 'https://giving.web.cern.ch/civicrm/contribute/'
                          'transact%3Freset%3D1%26id%3D20'],

**Comment by cafexpreso** [comment]
How I can fix this?

**Comment by krzysztof** [comment]
Overwrite the ``REDIRECTOR_EXTERNAL_REDIRECTS`` variable to empty list.

**Comment by krzysztof** [comment]
@cafexpreso 
As soon as this PR is merged we will not host any static pages in DB anymore: https://github.com/zenodo/zenodo/pull/1013

If you want to use some of those you might want to revert this commit on your fork and clear the redirector config.

**Comment by cafexpreso** [comment]
Hi
How can I customize the pages otherwise not using the DB.
I tried to set this variable FRONTPAGE_ENDPOINT  and they did not change it
seems that the template ingnores this variable.
