### ISSUE TITLE
docker-compose up Errno 113

### ISSUE THREAD

**Issue by amadeusgwin** [zenodo/zenodo#1057]
Prereq.: 
- Ubuntu 16.04 LTS xenial,
- installation with Docker ("docker-compose build" results in successful build without errors)

Issue:
"docker-compose up" throws following error and continues running
...
worker_1    | Trying again in 32.00 seconds...
worker_1    |
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:07:43 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:07:45 +0000] "HEAD /ping HTTP/1.0" 500 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:07:48 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:07:53 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:07:58 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:08:03 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:08:05 +0000] "HEAD /ping HTTP/1.0" 500 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:08:08 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.11 - - [13/Apr/2017:07:08:13 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
worker_1    | [2017-04-13 07:08:14,478: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@mq:5672//: [Errno 113] No route to host.
worker_1    | Trying again in 32.00 seconds...

**Comment by MichaelJames02** [comment]
I'm having the same problem

**Comment by satyarapelly** [comment]
sorry, its closed. i would like to one more issue related to this.
Its running for few days, suddenly we started seeing this error. we end up by restarting the rabbitmq-server service to make it work. we would like to know what could be the reason get this error intermittently.

**Comment by lnielsen** [comment]
@satyarapelly We'll take a look. Out of curiosity, is MS interested in this project? Feel free to contact me privately on lars.holm.nielsen@cern.ch

**Comment by reema-dass26** [comment]
Hello @lnielsen , i am still facing the same problem, the Variable is already set by default in my .yml file, so i am unsure how to resolve this.. Please find the attachment below, I really appreciate if anyone could guide me 
<img width="985" alt="image" src="https://github.com/user-attachments/assets/a5a5b8e8-684c-46e1-8630-b98fd51ded51" />
<img width="617" alt="image" src="https://github.com/user-attachments/assets/8a8d048e-1dd2-4430-bbf6-3f7882980b6b" />
I am installing V9.1 with python 3.8( i faces different issues with other version, this version has worked the farthest so far)
