### ISSUE TITLE
formatting error of link in community curation request emails

### ISSUE THREAD

**Issue by jradavenport** [zenodo/zenodo#1072]
When a user submits an entry to be included in my community and I receive an automated email, there is a formatting error that always causes problems for me: the link at the end of the email comes through like this:

    You can accept or reject this record in your community curation page:
    (&#39;https://zenodo.org/communities/astronomy-general/curate/&#39;,)

**Comment by slint** [comment]
Thank you for noticing.

This issue has been addressed by https://github.com/inveniosoftware/invenio-communities/pull/95, and a fix will be deployed on Zenodo, on the next release of `invenio-communities`.
