### ISSUE TITLE
I can't view an upload I just made to sandbox.zenodo.org

### ISSUE THREAD

**Issue by MichaelCurrie** [zenodo/zenodo#1078]
Using the API, not the front-end interface, I made a test upload:

![image](https://cloud.githubusercontent.com/assets/5267078/25694464/f97e30e2-30d8-11e7-9b98-ae01b2af66a3.png)

When I try to open my upload by clicking the link, taking me to https://sandbox.zenodo.org/record/72137, I get this page:

    Internal server error
    Error identifier: 399042175dce40bda41c41c10e3bc42e

I've tried a couple of times and the error identifier changes each time.

If I just create a draft but do not publish, I can click through to see the details, and no error appears.

So the problem seems to happen at the "publish" step.

**Comment by slint** [comment]
Apparently this has to do with the fact that the Publication Date of this record is set to a date before the year 1900, so one of our rendering components fails. I've created the relevant issue #1079.

**Comment by suso2** [comment]
Maybe it is related to #1067
I have a similar problem at the "publish" step. In my case with a docker installation. And the date is right.

**Comment by MichaelCurrie** [comment]
Thanks!  Yes when I change the date I can publish.  Feel free to close this issue if you feel it's redundant with #1079.
