### ISSUE TITLE
records-ui: publication date before 1900-01-01

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1079]
Records with publication dates before the year 1900 (eg. https://sandbox.zenodo.org/api/records/72137), fail to render their pages because of Python's `datetime.strftime` limitation. Alternative is to use `arrow` for this as proposed in this [SO thread](http://stackoverflow.com/a/35607999).

(Relevant issue: https://github.com/inveniosoftware/invenio-formatter/issues/47)

**Comment by krzysztof** [comment]
This has been fixed. Referenced issue no longer reproduces the bug.
