### ISSUE TITLE
deposit: add warning to submit dialog

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#109]
Add extra warning to the deposit submit dialog that files cannot be modified.

> * Uploaded files **cannot** be modified/added/removed after upload. Metadata (title, description, etc.) **can** be modified."
> * A Digital Object Identifier (DOI) will be registered for your upload, unless you provided an existing one."

![zenodo](https://cloud.githubusercontent.com/assets/1698163/5677065/1c3a1d0a-97e1-11e4-8ba5-7a97ec37ffaf.png)

**Comment by lnielsen** [comment]
Add two new bullets after the existing bullet.

**Comment by bouzlibop** [comment]
Dialog, after applying [this](https://github.com/zenodo/zenodo/pull/126):

![warning](https://cloud.githubusercontent.com/assets/8625570/5801048/cbe230be-9fe6-11e4-831b-53b05b55d172.png)
