### ISSUE TITLE
deposit: display better grant string

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1102]
E.g. 

"Open Access Research Infrastructure for Europe 2020" ->  "OpenAIRE2020 (731011) | Open Access Research Infrastructure for Europe 2020"

Needs to be checked against both Horizon 2020 and other funders such as NSF, Wellcome Trust, etc.

Needs to be checked if it's solely on the UI based on better payload in the suggester, or we need to index the entire string in the ES suggester.

**Comment by slint** [comment]
@lnielsen Some basic redesign to fit everything in the results
![image](https://user-images.githubusercontent.com/1814661/30656923-02d0144c-9e36-11e7-8048-80a6c760fdfb.png)

**Comment by slint** [comment]
Closed via #1299
