### ISSUE TITLE
publication date less than 1900 issue

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1135]
Sentry: ebf79b2873f1455ab3ac766c01437918

**Comment by krzysztof** [comment]
@slint I think you fixed that somewhere

**Comment by slint** [comment]
I think it's fixed by this one: https://github.com/inveniosoftware/invenio-formatter/commit/c86026a19290eb00f90b6e94200c8e5da7240aa2
But there are a couple of version releases and bumps required

**Comment by lnielsen** [comment]
Closed by #1148
