### ISSUE TITLE
versioning: link old records

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1139]
First case:
https://zenodo.org/record/18003

**Comment by krzysztof** [comment]
- [ ] Requires search in related identifiers to find those
- [ ] CLI for linking records together:
``zenodo migration versioning link 1234 2345 3456``

**Comment by krzysztof** [comment]
Resolved the case

**Comment by krzysztof** [comment]
WIP https://github.com/zenodo/zenodo-migrator/pull/40
