### ISSUE TITLE
datacite: upgrade to datacite v4.1 including hasVersions/isVersionOf

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1146]

**Comment by lnielsen** [comment]
- https://github.com/inveniosoftware/datacite
- https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L744-L745
https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/__init__.py#L76-L82

```curl -i -H "Accept: application/x-datacite+xml" https://zenodo.org/api/records/1171933```

**Comment by ChiaraBi** [comment]
remember to reindex all the records

**Comment by slint** [comment]
Should we also add the `IsDescribedBy/Describes`, `IsRequiredBy/Requires` pairs for related identifiers?

**Comment by tedhabermann** [comment]
+1 for format... I described why the format field is important (for datasets) and how DataCite recommends using it in https://www.hdfgroup.org/2018/06/citations-for-hdf-data-and-software/
