### ISSUE TITLE
Improve authors list in suggested citation

### ISSUE THREAD

**Issue by alesarrett** [zenodo/zenodo#1147]
In the "Cite as" section of a resource, the authors are listed as

`Surname1, Name1, Surname2, Name2, Surname3, Name3, ...`

this doesn't help readability of authors.
Below the title of the resource there's a better formatting option that could be adopted:

`Surname1, Name1; Surname2, Name2; Surname3, Name3; ...`

**Comment by lnielsen** [comment]
Thanks for the suggestion. We are relying on the citation style language for automatically generating citation according to many different styles. The default style is APA which doesn't use semicolon.

There is however problem which is that current we only have full names and not the name split into family/given names, which causes problems when we have to convert the given name into initials (e.g. "Nielsen, Lars Holm" -> "Nielsen LH".

We have it on our radar to improve it.

**Comment by alesarrett** [comment]
Just for clarification, could you please explain how you have solved this issue and when it'll become visible to users? Thanks!
