### ISSUE TITLE
communities: accept/reject communities not listed alphabetically on record detail page

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1159]
Causes communities to jump around
<img width="353" alt="screen shot 2017-06-03 at 17 07 30" src="https://cloud.githubusercontent.com/assets/1698163/26754672/1e5ab74c-487f-11e7-9e3e-c9ff63c4c867.png">

**Comment by slint** [comment]
Example record from Sandbox: https://sandbox.zenodo.org/record/186777
![2018-02-07-174643_355x221_scrot](https://user-images.githubusercontent.com/1814661/35929122-087732ec-0c2f-11e8-86f4-2a813a584587.png)
