### ISSUE TITLE
search: results description incorrect

### ISSUE THREAD

**Issue by LibrarPotter** [zenodo/zenodo#116]
The search results page displays "Showing records 1 to 0 out of 0 results." regardless of the number of results actually returned.

See screencap:
![zenodosearcherror](https://cloud.githubusercontent.com/assets/7935142/5745449/e6088ef0-9bf6-11e4-8dd4-48a50bc0f134.JPG)

**Comment by LibrarPotter** [comment]
An additional issue with this error is that the facets are not working either.  When I clicked "Any Author," all the records disappeared.  Presumably these are part of the same issue.

![zenodosearcherror2](https://cloud.githubusercontent.com/assets/7935142/5745632/2d83fb10-9bf8-11e4-9ae5-b8e039960e7c.JPG)

**Comment by lnielsen** [comment]
Same as #72. Happens when you are not logged in.

**Comment by lnielsen** [comment]
@LibrarPotter It should be fixed now. I will keep an eye out for problems, but in case you see it again, just reopen this issues.
