### ISSUE TITLE
Site name not displayed in some places

### ISSUE THREAD

**Issue by mpol** [zenodo/zenodo#1177]
Noticed at least on
- the [communities page](https://zenodo.org/communities/) - in the "Communities created and curated by users" header,
- individual community pages ([example](https://zenodo.org/communities/zenodo/?page=1&size=20)) - in the second box on the right, last bullet.

The Zenodo name that should be part of these texts is missing.

From a quick code search it seems that the templates using `THEME_SITENAME` work, those using `CFG_SITE_NAME` don't.

**Comment by jainaman224** [comment]
Hey @mpol, thanks for reporting. We have fixed the first issue [check here](https://github.com/zenodo/zenodo/issues/998) and it will reflect once the new `invenio` version is released.

**Comment by mpol** [comment]
@jainaman224 I don't think this is the same issue, or at least this is not the same missing name that I'm writing about. Looking at the template https://github.com/zenodo/invenio/blob/zenodo-master/invenio/modules/communities/templates/communities/index_base.html there should be a name in "created and curated by users", between "by" and "users".

**Comment by jainaman224** [comment]
Ohh ok, Sorry I misunderstood you.

**Comment by slint** [comment]
Fix in inveniosoftware/invenio-communities/pull/108. Pending next `invenio-communities` release for integration in Zenodo.

**Comment by slint** [comment]
Clsoed via https://github.com/inveniosoftware/invenio-communities/pull/110
