### ISSUE TITLE
Github release failed

### ISSUE THREAD

**Issue by pat-s** [zenodo/zenodo#1181]
https://zenodo.org/account/settings/github/repository/pat-s/oddsratio#

# Errors
```
{
    "errors": "Unknown error occured."
}
```

# Github payload

```
{
    "action": "published", 
    "release": {
        "body": "## Major\r\n  * rename functions (snake_case)", 
        "tag_name": "v1.0.0", 
        "assets_url": "https://api.github.com/repos/pat-s/oddsratio/releases/6693315/assets", 
        "assets": [], 
        "upload_url": "https://uploads.github.com/repos/pat-s/oddsratio/releases/6693315/assets{?name,label}", 
        "author": {
            "following_url": "https://api.github.com/users/pat-s/following{/other_user}", 
            "gists_url": "https://api.github.com/users/pat-s/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/pat-s/orgs", 
            "url": "https://api.github.com/users/pat-s", 
            "events_url": "https://api.github.com/users/pat-s/events{/privacy}", 
            "html_url": "https://github.com/pat-s", 
            "subscriptions_url": "https://api.github.com/users/pat-s/subscriptions", 
            "avatar_url": "https://avatars0.githubusercontent.com/u/8430564?v=3", 
            "repos_url": "https://api.github.com/users/pat-s/repos", 
            "received_events_url": "https://api.github.com/users/pat-s/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/pat-s/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "pat-s", 
            "type": "User", 
            "id": 8430564, 
            "followers_url": "https://api.github.com/users/pat-s/followers"
        }, 
        "url": "https://api.github.com/repos/pat-s/oddsratio/releases/6693315", 
        "created_at": "2017-06-13T10:05:35Z", 
        "target_commitish": "master", 
        "html_url": "https://github.com/pat-s/oddsratio/releases/tag/v1.0.0", 
        "zipball_url": "https://api.github.com/repos/pat-s/oddsratio/zipball/v1.0.0", 
        "published_at": "2017-06-13T10:07:42Z", 
        "draft": false, 
        "prerelease": false, 
        "tarball_url": "https://api.github.com/repos/pat-s/oddsratio/tarball/v1.0.0", 
        "id": 6693315, 
        "name": "oddsratio 1.0.0"
    }, 
    "sender": {
        "following_url": "https://api.github.com/users/pat-s/following{/other_user}", 
        "gists_url": "https://api.github.com/users/pat-s/gists{/gist_id}", 
        "organizations_url": "https://api.github.com/users/pat-s/orgs", 
        "url": "https://api.github.com/users/pat-s", 
        "events_url": "https://api.github.com/users/pat-s/events{/privacy}", 
        "html_url": "https://github.com/pat-s", 
        "subscriptions_url": "https://api.github.com/users/pat-s/subscriptions", 
        "avatar_url": "https://avatars0.githubusercontent.com/u/8430564?v=3", 
        "repos_url": "https://api.github.com/users/pat-s/repos", 
        "received_events_url": "https://api.github.com/users/pat-s/received_events", 
        "gravatar_id": "", 
        "starred_url": "https://api.github.com/users/pat-s/starred{/owner}{/repo}", 
        "site_admin": false, 
        "login": "pat-s", 
        "type": "User", 
        "id": 8430564, 
        "followers_url": "https://api.github.com/users/pat-s/followers"
    }, 
    "repository": {
        "issues_url": "https://api.github.com/repos/pat-s/oddsratio/issues{/number}", 
        "deployments_url": "https://api.github.com/repos/pat-s/oddsratio/deployments", 
        "svn_url": "https://github.com/pat-s/oddsratio", 
        "has_wiki": true, 
        "forks_url": "https://api.github.com/repos/pat-s/oddsratio/forks", 
        "mirror_url": null, 
        "stargazers_count": 12, 
        "subscription_url": "https://api.github.com/repos/pat-s/oddsratio/subscription", 
        "notifications_url": "https://api.github.com/repos/pat-s/oddsratio/notifications{?since,all,participating}", 
        "collaborators_url": "https://api.github.com/repos/pat-s/oddsratio/collaborators{/collaborator}", 
        "updated_at": "2017-03-21T18:35:11Z", 
        "private": false, 
        "pulls_url": "https://api.github.com/repos/pat-s/oddsratio/pulls{/number}", 
        "owner": {
            "following_url": "https://api.github.com/users/pat-s/following{/other_user}", 
            "gists_url": "https://api.github.com/users/pat-s/gists{/gist_id}", 
            "organizations_url": "https://api.github.com/users/pat-s/orgs", 
            "url": "https://api.github.com/users/pat-s", 
            "events_url": "https://api.github.com/users/pat-s/events{/privacy}", 
            "html_url": "https://github.com/pat-s", 
            "subscriptions_url": "https://api.github.com/users/pat-s/subscriptions", 
            "avatar_url": "https://avatars0.githubusercontent.com/u/8430564?v=3", 
            "repos_url": "https://api.github.com/users/pat-s/repos", 
            "received_events_url": "https://api.github.com/users/pat-s/received_events", 
            "gravatar_id": "", 
            "starred_url": "https://api.github.com/users/pat-s/starred{/owner}{/repo}", 
            "site_admin": false, 
            "login": "pat-s", 
            "type": "User", 
            "id": 8430564, 
            "followers_url": "https://api.github.com/users/pat-s/followers"
        }, 
        "full_name": "pat-s/oddsratio", 
        "issue_comment_url": "https://api.github.com/repos/pat-s/oddsratio/issues/comments{/number}", 
        "contents_url": "https://api.github.com/repos/pat-s/oddsratio/contents/{+path}", 
        "id": 67336792, 
        "keys_url": "https://api.github.com/repos/pat-s/oddsratio/keys{/key_id}", 
        "issue_events_url": "https://api.github.com/repos/pat-s/oddsratio/issues/events{/number}", 
        "tags_url": "https://api.github.com/repos/pat-s/oddsratio/tags", 
        "downloads_url": "https://api.github.com/repos/pat-s/oddsratio/downloads", 
        "assignees_url": "https://api.github.com/repos/pat-s/oddsratio/assignees{/user}", 
        "statuses_url": "https://api.github.com/repos/pat-s/oddsratio/statuses/{sha}", 
        "has_pages": true, 
        "git_refs_url": "https://api.github.com/repos/pat-s/oddsratio/git/refs{/sha}", 
        "open_issues_count": 0, 
        "has_projects": true, 
        "clone_url": "https://github.com/pat-s/oddsratio.git", 
        "watchers_count": 12, 
        "git_tags_url": "https://api.github.com/repos/pat-s/oddsratio/git/tags{/sha}", 
        "labels_url": "https://api.github.com/repos/pat-s/oddsratio/labels{/name}", 
        "forks": 0, 
        "size": 3691, 
        "comments_url": "https://api.github.com/repos/pat-s/oddsratio/comments{/number}", 
        "fork": false, 
        "milestones_url": "https://api.github.com/repos/pat-s/oddsratio/milestones{/number}", 
        "commits_url": "https://api.github.com/repos/pat-s/oddsratio/commits{/sha}", 
        "releases_url": "https://api.github.com/repos/pat-s/oddsratio/releases{/id}", 
        "description": "Simplified odds ratio calculation of binomial GAM/GLM models", 
        "archive_url": "https://api.github.com/repos/pat-s/oddsratio/{archive_format}{/ref}", 
        "contributors_url": "https://api.github.com/repos/pat-s/oddsratio/contributors", 
        "events_url": "https://api.github.com/repos/pat-s/oddsratio/events", 
        "default_branch": "master", 
        "html_url": "https://github.com/pat-s/oddsratio", 
        "compare_url": "https://api.github.com/repos/pat-s/oddsratio/compare/{base}...{head}", 
        "trees_url": "https://api.github.com/repos/pat-s/oddsratio/git/trees{/sha}", 
        "watchers": 12, 
        "git_url": "git://github.com/pat-s/oddsratio.git", 
        "forks_count": 0, 
        "merges_url": "https://api.github.com/repos/pat-s/oddsratio/merges", 
        "has_issues": true, 
        "ssh_url": "git@github.com:pat-s/oddsratio.git", 
        "blobs_url": "https://api.github.com/repos/pat-s/oddsratio/git/blobs{/sha}", 
        "git_commits_url": "https://api.github.com/repos/pat-s/oddsratio/git/commits{/sha}", 
        "hooks_url": "https://api.github.com/repos/pat-s/oddsratio/hooks", 
        "has_downloads": true, 
        "languages_url": "https://api.github.com/repos/pat-s/oddsratio/languages", 
        "name": "oddsratio", 
        "language": "R", 
        "url": "https://api.github.com/repos/pat-s/oddsratio", 
        "homepage": "https://pat-s.github.io/oddsratio/index.html", 
        "created_at": "2016-09-04T09:38:11Z", 
        "pushed_at": "2017-06-13T10:07:42Z", 
        "teams_url": "https://api.github.com/repos/pat-s/oddsratio/teams", 
        "open_issues": 0, 
        "branches_url": "https://api.github.com/repos/pat-s/oddsratio/branches{/branch}", 
        "subscribers_url": "https://api.github.com/repos/pat-s/oddsratio/subscribers", 
        "stargazers_url": "https://api.github.com/repos/pat-s/oddsratio/stargazers"
    }
}
```

**Comment by chrisfilo** [comment]
I'm experiencing the same issue (which also seems to be a related to https://github.com/zenodo/zenodo/issues/799

**Comment by PrometheusPi** [comment]
I experienced the same issue today - in #1214 I suggested the following workaround (that worked for me)

---------------
**from #1214**
*For me the issue was solved by using the dev branch instead of the master branch - however, this skipped the check on the zenodo website where I should press "publish" before it is published according to this github guide (Thus having on github user name as author name instead of the real name).*

*Thus adding event ids would at leas allow to pinpoint the origin of these bugs.*

----------

**Comment by giove91** [comment]
I've also just experienced the same issue.

**Comment by jspaaks** [comment]
my two cents:

I was struggling with this, then found this other issue https://github.com/zenodo/zenodo/issues/799
basically it says delete the v from your tag name, so instead of v1.0.0, have 1.0.0

That worked for some of my repos, but not for others. Here are the things I tried:

- renamed tags for earlier releases that still had the 'v'
- deleted tags that still had the 'v'
- did a minor change to the readme to avoid zenodo failing due to commit SHAs being the same

These steps fixed all but one of my repos. For the final one, I removed all but the master branch, and then it worked.

I'm not sure which of the steps I did are strictly necessary, so use your best judgment and good luck.

**Comment by asingh33** [comment]
I am getting the same error msg for my two newly released (first time) repos :(
I am not using 'v' tags in version.
Also tried toggling the switch in zenodo's interface
Both of them are master repo

Any help will be appreciated.

**Comment by jspaaks** [comment]
could you please post links to repos so I can have a look?

**Comment by asingh33** [comment]
Here are they:
https://github.com/asingh33/CNNGestureRecognizer/releases/tag/1.0
https://github.com/asingh33/SupervisedChromeTrex/releases/tag/1.0

**Comment by jspaaks** [comment]
Not at all sure what the problem is, but could you try to do this:

- do an minor change, maybe add some whitespace to the readme or something. just to make sure you have a different SHA 
- then do a new release exactly as you did before, but using three-element semantic versioning, e.g. 1.0.0

If that doesn't work, I don't know what does, so fingers crossed.

**Comment by asingh33** [comment]
Ok so I tried as you suggested. Did a small edit to readme to generate new SHA and created new release as 1.0.2 and it worked for one of the repo. :)
I am going to try for other one now.
Thanks a lot man for your suggestions. Really appreciate it.

**Comment by epiasini** [comment]
I'm also having this problem on this repo:

https://zenodo.org/account/settings/github/repository/epiasini/SubPID

I've already tried doing as @jspaaks suggested above (minor change, new commit, new tag with "pure" semantic versioning-style tag 0.2.1), but no luck :( . Any idea? Thanks!

**Comment by asingh33** [comment]
Hey Epiasini,
Try those same steps in following order (It worked for me atleast on two of my repos).
1 toggle the switch for your repo in zenodo's interface to "OFF"   <this is important>
2 do an minor change, maybe add some whitespace to the readme or something. just to make sure you have a different SHA
3 then do a new release exactly as you did before, but using three-element semantic versioning
4 Wait for few minutes, let Zenodo sync or click the manually sync button on Zenodo.
5 Again toggle back your repo to "ON" in Zenodo interface
6 Repeat steps 2 - 3.
That last step should auto trigger Zenodo to sync and hopefully it should work for you.

**Comment by epiasini** [comment]
That worked! I guess the key step I was missing was that I had to turn the integration off and on again (besides dropping the "v" in my tag names). Thanks a lot @asingh33 !

**Comment by ms609** [comment]
I've followed all the suggestions above but am still receiving a "failed" error message
https://github.com/ms609/Ternary/releases/tag/1.0.0

**Comment by jspaaks** [comment]
Hi @ms609,
I see that your repo still has tags and release titles that are not pure semantic versioning, like "Ternary v1.0.0", and "Version 0.1.1 - Initial CRAN release" for instance. Same for tags ("0.1.2-alpha1"). It's hard to tell if this is in fact the reason, but all I can say is that I removed them as described in one of the steps of my post above, and then it worked. Might be worth a try?

**Comment by ms609** [comment]
Ah, I missed that titles needed to follow semantic versioning too.  I've renamed, so will see whether this helps on the next release.  (It turns out that it's not too difficult to update manually, which is what I have done for the time being.) Thanks for the suggestion.

**Comment by ms609** [comment]
I can confirm that in my case, the issue was an unrecognized license.  

Per #1448, The `license` field of `.zenodo.json` must be set to a [recognized value](https://github.com/zenodo/zenodo/blob/fb2fb960e2719b062655125d9bcb06d3ac2a70a6/zenodo/modules/fixtures/data/licenses_map.json).

**Comment by slint** [comment]
An even more complete place to find the valid license IDs is our REST API endpoint. We now have [official documentation](https://developers.zenodo.org/?python#licenses) for it

**Comment by Socrats** [comment]
I hope this get's open again. I had the following error on my previous release and my new release was not even captured by zenodo....

```
    "errors": "Something went wrong when we tried to publish your release. If your release has not been published within the next hour, please contact us via our support form to resolve this issue."
```

I have no idea what to do about it, since the error message does not say anything useful and I don't know where to search for more info... 

The issues are happening with the following repository: https://github.com/Socrats/EGTTools for releases 0.1.8 and 0.1.9

**Comment by jspaaks** [comment]
@Socrats: I suspect the escape in your name in CITATION.cff, at least [`cffconvert`](https://pypi.org/project/cffconvert/) doesnt understand the file:

```shell
cffconvert --url https://raw.githubusercontent.com/Socrats/EGTTools/master/CITATION.cff --validate 
```

Maybe use double escape or no escape.

Also, the `date-released` in CITATION.cff has format YYYY-DD-MM, should be YYYY-MM-DD

After making those changes I can release on Zenodo Sandbox (repo with only a copy the CITATION.cff with suggested changes)

**Comment by Socrats** [comment]
@jspaaks Thanks so much for the help! I have fixed these issues on the CITATION.cff file. I also updated the version to the latest release `0.1.9`. Can you do this update and also force this latest release to get published on zenodo?

**Comment by jspaaks** [comment]
Seemingly only works if I release with tag name without v:

![image](https://user-images.githubusercontent.com/4558105/149985865-933db200-1296-441c-bf54-6da748cd6be0.png)

This is on Zenodo Sandbox, but should work the same on regular Zenodo

Also the repo contents are exactly the same, just a rerelease with different tag and title name. Not sure why it seems to matter.

Note the Zenodo Sandbox entries are wiped periodically, it's there for testing only.

**Comment by Socrats** [comment]
Thanks for the help again. The main issue is that my CI is set to use tags with v to automatically create new releases... I'll have to figure out a different way then....

**Comment by jspaaks** [comment]
Yay it works

![image](https://user-images.githubusercontent.com/4558105/149989963-f80b9128-04c6-4e83-b859-eff128a94dc6.png)

Previous error for v0.1.9 was because I didnt heed my own warning 

> do an minor change, maybe add some whitespace to the readme or something. just to make sure you have a different SHA

**Comment by Socrats** [comment]
Nice! Yet I still don't get it on zenodo, how can I trigger the publishing of the release manually?

**Comment by jspaaks** [comment]
If you go to https://zenodo.org/account/settings/github/ , do you see your repo listed?

**Comment by Socrats** [comment]
Yes, it appears in red due to the error with version 0.1.8: 
![image](https://user-images.githubusercontent.com/8985041/149991615-e73f5310-63df-4d8b-912f-00caca9a3926.png)

**Comment by jspaaks** [comment]
Of course.

> Nice! Yet I still don't get it on zenodo, how can I trigger the publishing of the release manually?

You can retrigger GitHub, but usually this fails, because it will be the same as what's already there. For reference, the retrigger is under your repo's settings, then Webhooks, then tab Recent Deliveries, Click three dots button to expand:

![image](https://user-images.githubusercontent.com/4558105/149992125-dce33f6b-c366-45c6-95fd-33ddccbf6790.png)

Easier way is to bump the patch version in CITATION.cff, this will take care of updating the SHA, then making a new release via the "Draft new release" with the patched version as tag name. (I assume this bypasses your CI, unless said CI triggers based on release_published event)

**Comment by Socrats** [comment]
This fixed it. Thanks a lot @jspaaks !

**Comment by jspaaks** [comment]
Woohoo! Glad I could help.
