### ISSUE TITLE
deposit: license list updates

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#119]
Reported by @LibrarPotter

Licensing Updates needed:
* Licenses to consider removing:
  * Apache Software License - Has been replaced with Apache License, 2.0 (which is also an option)
  * UK Click Use PSI - has been replaced with the UK Open Government Licence (OGL).
  * UK Crown Copyright with data.gov.uk rights - This does not appear to be a license option at this time. All information on data.gov.uk is currently covered under the Open Government Licence (OGL).
  * UK PSI Public Sector Information - This information is also entirely covered under Open Government Licence (OGL) now.
* Licenses to consider adding (found on http://creativecommons.org/choose/)
  * Creative Commons Attribution-NoDerivatives 4.0 International
  * Creative Commons Attribution-NonCommercial 4.0 International
  * Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International 
  * Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International

**Comment by lnielsen** [comment]
Check with http://licenses.opendefinition.org/

**Comment by LibrarPotter** [comment]
The issue I see with this page is just that it doesn't seem totally up to date seeing as it lists UK Click Use PSI as "status: active" but the official site (http://www.opsi.gov.uk/psi/) disagrees:

![ogl license](https://cloud.githubusercontent.com/assets/7935142/5967006/3bf0c4d6-a7d7-11e4-9723-ba2ec5f4b6b7.png)

I am also concerned that we would point people to the creative commons website for licensing options, but that a couple of the suggested licenses are currently not available in Zenodo.

Do you mean that I should contact http://licenses.opendefinition.org/ to let them know that some of their content is out of date?

**Comment by LibrarPotter** [comment]
I have reported these issues to http://licenses.opendefinition.org/ as suggested.

**Comment by wetneb** [comment]
Would it be possible to sync the licenses available on the sandbox and on the production site ?
The current versions differ:
https://zenodo.org/kb/export?kbname=licenses&format=kba
https://sandbox.zenodo.org/kb/export?kbname=licenses&format=kba

Thanks!

**Comment by lnielsen** [comment]
@krzysztof Can you take a look to see if this have been resolved when the updates to the new license API.

**Comment by lnielsen** [comment]
@LibrarPotter Just seeing now your comment sorry - my very short comment "Check with http://licenses.opendefinition.org/" was a note to myself :-) Not something for you.....sorry.

**Comment by krzysztof** [comment]
All previous references to Apache license will now point to Apache 2.0, although 1.1 will still be an option for all new uploads.

All three UK licenses are still there and will be available and are not automatically replaced by the OGL. 
We could map all previous UK Crown, UK Click and UK PSI license information to OGL during data migration by providing fixed mapping similarly to how it was done for Apache example above: https://github.com/zenodo/zenodo/pull/562/files#diff-3ddc7aacb02644c8127f1df51a724d4aR58
