### ISSUE TITLE
deposit: supervisor problem in upload

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#120]
For an upload to have a supervisor or supervisors added to it, if must be classified as a thesis.  The presentations I’ve been uploading are not technically theses, but do have supervisors.

Via @LibrarPotter

**Comment by lnielsen** [comment]
Currently can’t add additional supervisors (under Thesis) once saved and uploaded. This would be helpful when editing

**Comment by bouzlibop** [comment]
@lnielsen I wasn't able to reproduce this (neither locally nor on `qa`).

1. it is possible to add `supervisors` to a record which is not necessarily a `thesis` (eg. `presentation`)
    btw, as far as I understand this is the concern brought up in the description of this issue?
2. it is possible to:
   1. **save** and **edit** `supervisors`
   2. **submit** and **edit** `supervisors`

   (both points tested with `thesis` and `presentation`)

Can you think of any other case I should test it against?

**Comment by lnielsen** [comment]
@LibrarPotter We have issues reproducing this problem. Can you see if the issue still exists and if so, send us instructions for how we can reproduce it. Many thanks.
