### ISSUE TITLE
metadata extraction in a celery task

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1200]
In order to offload heavy tasks, we need to use celery for extraction. Gathering results from celery job is non trivial, unless we're willing to wait in the web application for the result (which doesn't solve the problem).

Most likely to solve this we will have to define a DB Model which will keep track of the metadata extraction jobs, as well as build a simple REST API.

Endpoint: ``/fileextractor/<extractor_type>/<object_version_id>/<action>``

Examples:
``GET /fileextractor/pdfmeta/bd4c8bf0-5012-4ddf-b960-612875f997a9``  <- returns the response if the job was already done before (we would probably want to store the results in DB), otherwise returns message that the job was not started.

``POST /fileextractor/pdfmeta/bd4c8bf0-5012-4ddf-b960-612875f997a9/start``  <- starts the extraction job

Then we would have endpoint which we would pool periodically for results:
``POST /fileextractor/pdfmeta/bd4c8bf0-5012-4ddf-b960-612875f997a9/status``  <- returns the status of the job (``NOTSTARTED``, ``PROCESSING``, ``DONE``, ``ERROR``)

This way on the deposit form (or wherever the task is called from), we would make calls to the endpoints to start/ping and get results of jobs. An advantage of having this in a DB is that we wouldn't repeat the same job twice, i.e. you can extract metadata first time (might take some time), but if you close the page, and decide to click it again you get the results from the DB immediately.

**Comment by krzysztof** [comment]
@xiaom For starter we can create a module in zenodo (we will refactor it later to a separate invenio module), which will have provide simple handling of those endpoints, as well as define a simple DB model like:

class FileExtraction(db.Model, Timestamp):
    id - UUID (PK)
    object_version_id - FK to Object Version
    status - (Enum with possible job states)
    extractor - (String which represents the extractor)

**Comment by krzysztof** [comment]
Then the celery part is rather easy - the endpoint will query (if they exist) or instantiate (if the action is "start") those "job" DB objects and launch a celery task, which will have a signature like:

```
@shared_task
process_job(job_id):
   job = FileExtraction.query.get(job_id)
   extractor_function = resolve_extractor(job.extractor)  # We need to think how we turn the "extractor" string to actual function, but it should be easy enough
   job.status = PROCESSING
   db.session.commit()
   try:
       result = extractor_fun(job.object_version_id)
       job.result = result
   except:
       job.status = ERROR
       db.session.commit()
   job.status = DONE
```

**Comment by krzysztof** [comment]
Here's a rough sketch for the endpoint:

@route('/fileextractor/<extractor_type>/<object_version_id>/<action>', methods=['POST', 'GET'])
def extractor(extractor_type, object_version_id, action):
   if request.method=='GET':
       job = FileExtractor.query.filter_by(...).one_or_none() # see if job exists
       if job:
           return job.result
       else:
           # inform that the job needs to started first
   if request.method == "POST":
        # depending on the action start the job or return its status

**Comment by krzysztof** [comment]
Now finally, the last part is modifying the angular code on the deposit UI so that on button click it first checks if the extraction job exists, if not, start it, then pool the endpoint every several seconds for the status, and finally if it's 'DONE' fill-in the metadata on the form

**Comment by krzysztof** [comment]
Last comment:
Since the DB model makes a FK to ObjectVersion, it means that two different ObjectVersions which point to the same bytes (FileInstance), will now know that given job was already done. Perhaps we should keep the FK to the FileInstance instead? I guess for simplicity the REST API should accept ObjectVersion since that's what you get from the Deposit UI, but internally we should not re-do the same job for the same "bytes".

**Comment by lnielsen** [comment]
Please talk to @egabancho about what they did for videos.

**Comment by egabancho** [comment]
This a quick [brain dump](https://github.com/CERNDocumentServer/cds/issues/913#issuecomment-314051559) of what we are thinking on doing, our use case is a bit more complex than the one you describe here, but in the end I think it fits perfectly.
