### ISSUE TITLE
bootstrap a skeleton module for the metadata extraction module

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1202]
This might be more general than just metadata extraction, but a general file processing, also to get some side effects in the system (e.g. create new files - thumbnails/video convertions).

Possible candidates: ``invenio-file{analyzer,processor,extractor}``?

@lnielsen @slint comments?

**Comment by slint** [comment]
invenio-file**s**-processor :+1:

**Comment by krzysztof** [comment]
https://github.com/xiaom/invenio-files-processor

Needs moving to inveniosoftware org.
