### ISSUE TITLE
create a PDF metadata extractor

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1203]
This includes first taking a look at what's available off-the-shelf, or if we're feeling adventurous to write up something simple that analyzes the PDF structure for some basic stuff like: "title", "abstract" and "authors".

**Comment by xiaom** [comment]
I have good experience with [grobid](https://github.com/kermitt2/grobid). And it claims "deployments in production includes ResearchGate, HAL Research Archive, the European Patent Office, INIST, Mendeley, CERN, ..." 😄   We can start with it.

**Comment by krzysztof** [comment]
Perfect, I will take a look :)

@lnielsen WDYT about grobid?

**Comment by krzysztof** [comment]
We might need to ask Inspire team about it

**Comment by lnielsen** [comment]
@krzysztof I'm not sure Grobid if it's worth the effort:

1) Grobid seems non-trivial to run in production (have to run as a service, and meaning machines, monitoring, alarms etc).
2) OpenAIRE is setting up an endpoint where we can send the PDF and they'll do both bibliographic metadata extraction as well as grant identification. Cermine can be checked here http://cermine.ceon.pl/index.html

Inspire team is already using Grobid and have a couple of modules: https://github.com/inspirehep/invenio-grobid

**Comment by krzysztof** [comment]
We settled on using grobid for now as the first PDF extractor which seems to work OK. When CERMINE by OpenAIRE goes live we can develop another extractor and compare the results. Swapping those alter in deposit form should be a one-liner.
