### ISSUE TITLE
REDIRECTOR_EXTERNAL_REDIRECTS 

### ISSUE THREAD

**Issue by ghost** [zenodo/zenodo#1219]
Hi 

I am trying to use REDIRECTOR_EXTERNAL_REDIRECTS to customize some of the pages [about, dev ...] to point to the test installation. While the initial redirect work the page falls back to the zenodo.org site. 
Beside the definition of the custom URL/Link in REDIRECTOR_EXTERNAL_REDIRECTS is there any other variable needed to be set to fully isolate the zenodo test system from the zenodo.org?

All the best,
Carlos

**Comment by cafexpreso** [comment]
Ok this REDIRECTOR_EXTERNAL_REDIRECTS only affect the behavior of the redirector module if defined directly in the configuration file in the modules directory (config.py). If defined in the zenodo.cfg file this variable appears to be ignored.
