### ISSUE TITLE
Alembic recipes for Invenio-SIPStore

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1226]
Create initial alembic recipes on https://github.com/inveniosoftware/invenio-sipstore/commit/12f365634de698a1659365, to be able to sync currently deployed DB schema on production.

Syncing involves modifying constraints and names of the deployed schema to match the schema produced by the alembic recipe.

**Comment by krzysztof** [comment]
Second part is the recipe that upgrades the SIP DB schema with the newest changes + migrates the data (extraction of SIP.content, SIP.format to separate table etc.).

1. Init recipe
2. SIP store tables recipe (the same state as current Zenodo state)
3. Third recipe with the recent SIPstore changes.

**Comment by slint** [comment]
Migration recipes tested on production dump successfully :taco: 
Average duration for the upgarde is 20-30min.

**Comment by lnielsen** [comment]
Does this require downtime again? Would be good if e.g. table changes could be made immediately, and then the site could be up during the time it takes to migrate the old data.

**Comment by slint** [comment]
The problem is that it's not only new tables but also there's columns being moved from one table to another (`SIP.{content, sip_format} -> SIPMetadata.{content, type_id}`) and I'm not sure if having an intermediate state is OK with the SQLAlchemy models... 

SIP creation is part of publishing as well which uses these models. I'll give it a try and see if we can split it in two parts
