### ISSUE TITLE
deposit: license selection "CC0" problem

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1229]
If you type "CC0" the license is not found, if you type "Creative Commons Zero" it is.

**Comment by krzysztof** [comment]
Actually typing "Creative Commons Zero" doesn't do it either. One needs to type "C" and then wait for the results (should be first on the list).

**Comment by krzysztof** [comment]
Similarly PDDL (https://opendatacommons.org/category/pddl/) requires a pharase "Open Data Commons".

Most "intuitive" phrases that do not work and perhaps should:

- "PDDL"
- "Public Domain Dedication"

**Comment by hvwaldow** [comment]
Now "C" doesn't work anymore, "Creative Commons Z" is the minimum. That deserves quick fixing, as for scientific data CC0 is the only sane choice.

**Comment by slint** [comment]
Typing `cc0` should work now. The issue was related to not having an outdated ES mapping which was stripping away numbers from search queries. The mapping has been updated (both in QA and Production)
