### ISSUE TITLE
deposit-ui: clarify which DOI is pre-reserved

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1251]
It should be mentioned/clarified near the "Pre-reserve DOI" button that the produced DOI is that of the record and not the Concept DOI

**Comment by lnielsen** [comment]
Is this an issue? We only display the version doi in the upload interface.

**Comment by slint** [comment]
I guess somebody asked the question on support... Maybe the issue is more about clarifying that a Concept DOI will be registered as well (or that one already exists in case the deposit is a new version).

**Comment by lnielsen** [comment]
Ok, not sure what to do, so I'll close it we have something concrete.
