### ISSUE TITLE
Small outage? 502 errors

### ISSUE THREAD

**Issue by wetneb** [zenodo/zenodo#1261]
Hi,
We see a few 502 errors on our side. This one at 19:36:47 swiss time:
```
### Checking the access token
--- Request to https://zenodo.org/api/deposit/depositions?access_token=redacted

Status code: 200 (expected 200)

### Creating a new deposition
--- Request to https://zenodo.org/api/deposit/depositions?access_token=redacted

Status code: 502 (expected 201)

Server response:
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
```

This time I checked that you had not announced any recent outage on Twitter. Is it helpful if I keep reporting that here in these cases?

Keep up the good work!

**Comment by lnielsen** [comment]
We did a production deployment around that time, which normally are fully transparent for some reason the load balancer directed traffic to notes that wasn't fully up yet.

**Comment by samapriya** [comment]
Experiencing 502 errors again trying to access https://zenodo.org/account/settings/github/ anything changed?

**Comment by olejandro** [comment]
Experiencing the 502 error while trying to access https://zenodo.org/account/settings/github/

**Comment by slint** [comment]
@olejandro can you contact us via our [support form](https://zenodo.org/support) or shoot an email at <info@zenodo.org>? We can have a closer look there and identify the root cause.
