### ISSUE TITLE
deposit: enable orcid field in deposit form

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1268]
The REST API already supports ORCIDs for authors and contributors. Enable the field in the form so that users can enter the ORCID.

**Comment by slint** [comment]
Field preview:
![image](https://user-images.githubusercontent.com/1814661/30869546-b72988c4-a2e1-11e7-9911-7c8911440ad4.png)

**Comment by slint** [comment]
Closed via #1299
