### ISSUE TITLE
missing data in search

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1290]
when I want to see all the files type=pdf that are access right type=close, I expect 16,767 results, but don't see anthing
https://zenodo.org/communities/biosyslit/search?page=1&size=20&access_right=closed&file_type=pdf

![image](https://user-images.githubusercontent.com/4609956/30683825-360191be-9eaf-11e7-848d-00cd55cc27f6.png)

**Comment by slint** [comment]
That is because we do not index any file information for closed access records, since that would technically be considered as sharing information about the files.

Though your confusion is justified, since the search facet/filter categories show (on purpose) totals for the entire query result set.
