### ISSUE TITLE
search results: incomplete

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1291]
when I search for
https://zenodo.org/communities/biosyslit/search?page=1&size=20&access_right=closed&type=publication

I don't get all the files that are in Zenodo/BLR. For example here, I do not get DOI: https://doi.org/10.11646/zootaxa.4323.2.2 (which is in the system: https://zenodo.org/record/898880) and  DOI: https://doi.org/10.11646/zootaxa.4323.2.8 (which is in the system: https://zenodo.org/record/898981)

**Comment by slint** [comment]
This seems to be an issue caused by a malfunctioning search index node we had on production since last week. We will be running a task which will synchronize published records and the search index for that specific time period.

**Comment by slint** [comment]
All records affected by the issue have been reindexed and are available in search results now.
