### ISSUE TITLE
[search api] anticipate integration with Searx

### ISSUE THREAD

**Issue by jibe-b** [zenodo/zenodo#1296]
Dear OpenAIRE team,

[Searx](http://github.com/asciimoo/searx) is meta-search engine that takes various indexes as sources. The science tab only searches in scientific academic engines, including BASE and soon, PubMed and OpenAIRE.

Zenodo would be a really interesting index for this tab. I have then two questions:
- could you give the expected API url pattern, so that I already write the engine and we can add it as soon as the new API is available.
- Searx instances proxy the requests of several users, using only one API key. Does this fit with your policy? Any constraint is made on traffic incoming to the Zenodo API will be accepted, indeed.

Note that with the increase of indexes which indexes overlap brings the question of ranking. This is an issue that is already handled but I would like to improve it in the Science tab with licensing information and full-text availability.

**Comment by lnielsen** [comment]
You'll find Zenodo records already via OpenAIRE, so probably not a big issues. 

Searx instance will be considered a single user from our system point of view and from our terms of use point of view. 

Searx will prevent us to properly count number of unique users. While I understand concerns over privacy, we go to a great deal of length to anonymize all statistics and respect privacy of users. Statistics on usage is important for us to provide a better product, but also justify usage of zenodo towards our funders and thereby ensure continued operation of Zenodo. 

I'm not assuming we have a lot of request from Searx instances, so not really a big issue.
