### ISSUE TITLE
installing webhooks failing

### ISSUE THREAD

**Issue by aminevsaziz** [zenodo/zenodo#1302]
Just by following the steps to get a DOI for GitHub repo i fail at  installing webhooks since the installed webhooks show "invalid HTTP Response:500". also by accessing the webhook then response tab i see the following :

> 
 Headers

Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type, ETag, Link, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset
Content-Length: 64
Content-Type: application/json
Date: Sun, 01 Oct 2017 23:45:48 GMT
Server: nginx/1.10.2
X-Sentry-ID: None

Body

{
  "message": "No row was found for one()", 
  "status": 500
}
> 
Any help to solve this problem and archive my repo in Zenodo

**Comment by lnielsen** [comment]
Sorry for the very late reply - Can you please submit this via our support form if you still have the issue: https://zenodo.org/support

**Comment by Michael-A-Heuer** [comment]
@lnielsen I have the same problem just for one repository. I tried deleting and re-adding the webhook in GitHub without success.
