### ISSUE TITLE
Internal Server Error when updating GitHub record

### ISSUE THREAD

**Issue by mdeff** [zenodo/zenodo#1314]
I created a [record](https://zenodo.org/record/1003158) from a GitHub tag and Zenodo registered a DOI for it. All went fine, but I am not able to update that record, e.g. to change the authors. I can click on *Edit*, do my modifications, click *Save*. But once I click on *Publish* I get an *Internal Server Error*.

Any idea of what is wrong? Let me know if there's anything I can do to track this down.

**Comment by mdeff** [comment]
For the record, I was able to get around this bug by clicking *Edit*, then *Discard changes*, then *Publish*. Then I could edit again and publish my modifications. I guess the bug is that it **first needs to be published without change**. I hope it can help you track that bug done!

**Comment by lnielsen** [comment]
If it happens again, can you send us the link to the record via the [support form](https://zenodo.org/support). Then we can take a closer look and to better understand the error.
