### ISSUE TITLE
conference proceedings: author should not be mandatory (or should be displayed as editor)

### ISSUE THREAD

**Issue by iiegn** [zenodo/zenodo#1315]
i am trying to deposit the complete conference proceedings of a conference (next to the individual papers).

when i put down the editors unter contributors and set their type to 'editor' an author is still mandatory. once i put down the editors as authors i cannot set their type anymore and consequently they won't be displayed as editors.

to display the editors i would have to put down their names as contributors and as authors. this seems odd.

**Comment by lnielsen** [comment]
This is an artefact of the DataCite metadata schema, which requires a list of authors that don't have a type for authors. We need this in order to register a DOI so unfortunately we won't be able to fix this.
