### ISSUE TITLE
API Error: The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request.

### ISSUE THREAD

**Issue by chrisfilo** [zenodo/zenodo#1322]
The query recommended by @lnielsen  at https://github.com/duecredit/duecredit/issues/117#issuecomment-317984087 returns an error

```
$ curl -H "Accept: text/bibtex" https://www.zenodo.org/api/records/581704
{
  "message": "The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request.",
  "status": 406
}
```

**Comment by slint** [comment]
Indeed, the correct content type is "**application**/x-bibtex". An unofficial/raw list of the available content types can be found [here](https://github.com/zenodo/zenodo/blob/ebe8e469410d4ecac59c7079e8c2f187923946ff/zenodo/config.py#L684-L699)

**Comment by chrisfilo** [comment]
Thanks - this worked!
