### ISSUE TITLE
unable to select zenodo-freetoread-1.0 as license for a new deposit

### ISSUE THREAD

**Issue by wetneb** [zenodo/zenodo#1326]
Hi!
We were thinking about changing the default license used by Dissemin for deposit in Zenodo to something a bit better: https://github.com/dissemin/dissemin/issues/441

zenodo-freetoread-1.0 looked a bit more explicit than "other (open)" so we would like to use that, but it looks like this license is not accepted by the deposit interface (both GUI and API). I am not sure why?

**Comment by krzysztof** [comment]
Hey @wetneb sorry for the late reply. It looks like the license was missing from sandbox (only on production system). The license has been added to sandbox now.

**Comment by wetneb** [comment]
@krzysztof thanks a lot, it works!
