### ISSUE TITLE
openaire: import SNSF grants

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1332]
Swiss national science foundation grants are now in production (8.5k grants): https://www.openaire.eu/search/browse/publications?funder=snsf________::SNSF||Swiss%20National%20Science%20Foundation||SNSF

**Comment by krzysztof** [comment]
grants imported to QA. Production does not contain NIH grants yet.

- [ ] Check how the QA responds with the 1.5M grants from NIH (already there)
