### ISSUE TITLE
Invalid xml records in the direct indexing API

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1337]
I noticed an error in the direct indexing procedure. The system could not accept an invalid xml record:
More specifically, the parser complains about:

org.xml.sax.SAXParseException; lineNumber: 25; columnNumber: 595; Character reference "&#55349" is an invalid XML character.

---

Please check that 10.5281/zenodo.996201 when serialised to OpenAIRE JSON that it is purely encoded in UTF-8.

The XML is built on the OpenAIRE side so we just need to verify that we send valid data.

Ref: https://issue.openaire.research-infrastructures.eu/issues/3146

**Comment by slint** [comment]
The produced JSON is this:
```json
{
  "authors":[
    "Alouges, Fran\u00e7ois",
    "Di Fratta, Giovanni"
  ],
  "collectedFromId":"opendoar____::2659",
  "description":"The paper is about the parking 3-sphere swimmer ($\\text{sPr}_3$). This is a low-Reynolds number model swimmer composed of three balls of equal radii. The three balls can move along three horizontal axes (supported in the same plane) that mutually meet at the center of $\\text{sPr}_3$ with angles of $120^{\u2218}$ . The governing dynamical system is introduced and the implications of its geometric symmetries revealed. It is then shown that, in the first order range of small strokes, optimal periodic strokes are ellipses embedded in 3d space, i.e. closed curves of the form $t\ud835\udfc4 [0,2\u03c0] \u21a6 (\\cos t)u + (\\sin t)v$ for suitable orthogonal vectors $u$ and $v$ of $\u211d^3$. A simple analytic expression for the vectors $u$ and $v$ is derived. The results of the paper are used in a second article where the real physical dynamics of $\\text{sPr}_3$ is analyzed in the asymptotic range of very long arms. ; Comment: 17 pages, 4 figures",
  "hostedById":"opendoar____::2659",
  "licenseCode":"OPEN",
  "originalId":"oai:zenodo.org:996201",
  "pids":[
    {
      "type":"oai",
      "value":"oai:zenodo.org:996201"
    },
    {
      "type":"doi",
      "value":"10.5281/zenodo.996201"
    }
  ],
  "publisher":"Zenodo",
  "resourceType":"0020",
  "title":"Parking 3-sphere swimmer. I. Energy minimizing strokes",
  "type":"publication",
  "url":"https://zenodo.org/record/996201"
}
```

There are Unicode characters in the description, encoded correctly using the `\u` prefix. I found [this similar issue](https://sourceforge.net/p/joost/mailman/message/1418702/), about a Java library that has problems parsing Unicode surrogate pairs (wider ), one of which appears in this record's description: [\ud835\udfc4 -> 𝟄](http://www.fileformat.info/info/unicode/char/1d7c4/index.htm)
