### ISSUE TITLE
support-form: better handling of file upload UX

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1340]
The following scenario has become pretty common:

1. User uploads file in support form and submits
2. Form has some validation error (invalid email address, short description, etc)
3. Page is rendered to display field errors, but the file upload field is lost (no file included in form)
4. User forgets, or is not aware of the missing the file, and submits the form without the file

Possible solutions (in order of preference):

- Validate the form on the client side
- Include some extra info to the template when rendering the validation error in case the user had included a file

**Comment by krzysztof** [comment]
I think form validation on the client-side would be the way, given that we don't do any validation that requires communication with the server.
