### ISSUE TITLE
question: how can a curator add an entry in a community?

### ISSUE THREAD

**Issue by monperrus** [zenodo/zenodo#1341]
As a curator, I'd like to add https://zenodo.org/record/12646 to https://zenodo.org/communities/empirical-software-engineering/

how can a curator add an entry in a community without any request? (the opposite of an author requesting to be part of a community)

**Comment by krzysztof** [comment]
@monperrus Thank you the suggestion. At the moment this is not possible, but this already came up as one of the possible future improvements, see: https://github.com/zenodo/zenodo/issues/136

We do not plan on working on this in near future (Q4), but it should be straightforward to implement and could be piled-up along other community tasks we have queued up for later. Closing this on behalf of the other issue.
