### ISSUE TITLE
communities: deposit form redesign

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1344]
- [x] Communities section redesign
  - [x] Move communities section to the top (between files and resource type)
  - [x] Single search bar on top
  - [x] List of boxes/rows with detailed information for each community
  - [x] Mark communities that have extra resource types with a small OpenAIRE logo
- [x] OpenAIRE resource type
  - [x] Load from config, passed as JSON to the form
  - [x] Show when OpenAIRE communities are selected
  - [x] Choices available are set union of the selected OpenAIRE communities

**Comment by slint** [comment]
Screencast from current redesign and workflow for selecting an OpenAIRE community with extended subtypes:
![zenodo-oa-comms](https://user-images.githubusercontent.com/1814661/33204246-3719f286-d103-11e7-9163-9eed414ecc62.gif)

**Comment by krzysztof** [comment]
Integrated in master and qa
