### ISSUE TITLE
support-form: increase the description and title character limit.

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1354]
Increase 1000 -> 3000/5000? 

We like concise emails but 1000 might not be enough for a detailed explanation of the issue.

**Comment by jainaman224** [comment]
I think we just need to change https://github.com/zenodo/zenodo/blob/4d26f7121356f0ac55b5b2bbd2c041ed7ffad0f2/zenodo/modules/support/config.py#L33. Can I open a PR?

**Comment by krzysztof** [comment]
Hey @jainaman224, sure, you can change it to 5000

**Comment by jainaman224** [comment]
I have opened a PR #1360 .
