### ISSUE TITLE
records: display of pre-1900 dates

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#138]
See https://zenodo.org/record/14266

![unknown](https://cloud.githubusercontent.com/assets/1698163/5953890/75e53ae4-a798-11e4-989d-67cedef83094.png)

**Comment by bouzlibop** [comment]
From [Python Docs](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior): 
> The exact range of years for which strftime() works also varies across platforms. Regardless of platform, years before 1900 cannot be used.

`bfe_date.py` is using `time.strftime` which according to the note above doesn't work for the year < 1900

**Comment by lnielsen** [comment]
See #2673

**Comment by bouzlibop** [comment]
[This PR](https://github.com/inveniosoftware/invenio/pull/2728) should close this issue. Records with old publication date are rendered properly:

![old_date](https://cloud.githubusercontent.com/assets/8625570/5974310/1b5e8248-a873-11e4-940a-f4d2aa53be34.png)

**Comment by lnielsen** [comment]
Thanks. inveniosoftware/invenio@86d912867d459ab0ffa0887e69dcc020dc38a7bf cherry picked to zenodo/invenio@cf3fc2d
