### ISSUE TITLE
Add JSON-LD serialisation based on schema.org

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1381]
Following properties should be present:

```
- @id
- name (i.e. title)
- author (type person, ORCID), 
- publisher, 
- datePublished, 
- type (according to schema.org)
- description (strip html), 
- keywords
- license (URL)
- isPartOf (data citation - probably needed for version hierarchy)
- citation (pub citation)
- dateModified (record.modfied)
- version (from version field)
```

**Comment by 7048730** [comment]
Hello there,

does this mean you are also planning on adding a [JSON schema](http://json-schema.org/specification.html) file, that the zenodo metadata could be validated against?

This would be appreciated!

**Comment by krzysztof** [comment]
@7048730 That would be only for export, so there would be no need for users to validate it. If you mean for our REST API metadata schema (currently the only import format in Zenodo), i.e.: http://developers.zenodo.org/#representation we do not have JSON schema file yet, but it is a good idea to have one. It's not part of this task though.

**Comment by 7048730** [comment]
I see. Thank you for the clarification. That is exactly what I meant: It would enable users to validate their deposition metadata before making an API call. A very useful addition when submitting to zenodo via REST API or creating metadata crosswalks.

**Comment by lnielsen** [comment]
Thanks for the suggestion. Internally everything is validated with JSONSchemas, so shouldn't be too far a fetch to also publish it for the public APIs.

**Comment by lnielsen** [comment]
JSON-LD export was implemented and now have export format, and is also embedded in the landing page.
