### ISSUE TITLE
Display of Meeting/Conference: Superflous blank

### ISSUE THREAD

**Issue by kwenzig** [zenodo/zenodo#1391]
In this record https://zenodo.org/record/1084106, the meeting information is displayed liked this:

**Meeting:** 
```
9th Annual European DDI User Conference (EDDI17), Lausanne, Switzerland, December 5/6, 2017 (Session E2 )
````
There is a superflous blank after E2 at the end of the line before the closing bracket, which is not contained in the metadata.

**Comment by slint** [comment]
Closed via #1919
