### ISSUE TITLE
deposit-ui: more intutitve file upload indicators

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1412]
Many users come across the issue where they select files, but do not click the green "Start upload" button to complete the upload. Saving and publishing the deposit later gives them a validation error of course since one file minimum is required.

One solution would be to have a visual indicator/icon that reminds the user that he has selected files but has not uploaded them yet.

**Comment by Herrner** [comment]
possibly change the buttons to `upload and save` (and - see also #1320 - and to `upload, save and publish` when everything checks out).
