### ISSUE TITLE
Read additional metadata from github repositories

### ISSUE THREAD

**Issue by aragilar** [zenodo/zenodo#1421]
Currently, to add additional metadata (e.g. orcid for author, keywords), this information must be entered manually into the deposit-ui. Would it be possible to read such metadata from files inside the github repository, such that creating a release on github is the only thing required to have the release appear on zenodo?

**Comment by lnielsen** [comment]
You can add a ``.zenodo.json`` inside the repository:

![screen shot 2018-02-21 at 15 57 40](https://user-images.githubusercontent.com/1698163/36486957-10316bf0-1720-11e8-9b06-44c4729defeb.png)

**Comment by aragilar** [comment]
OK, cool, that's what I was looking for. Is it possible to make that more obvious, e.g. adding it to the FAQ, and putting a link on the setting page? Also, how much of the metadata gathering is overridden by using a `.zenodo.json` file? Am I able to just add people's orcid, and allow zenodo to add and sort the authors by the contributors statistics?
