### ISSUE TITLE
number of files in a deposit

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1434]
We (Biodiversity Literature Repository)  would like to make use of the article deposit to add all the files we produce when we extract data from articles. In this process, we create a IMF file which is essentially a zip file that is the output from our GoldenGate Imagine process and is the bases for all the further annotations. The files included are the source file (that is already in Zenodo deposited and linked to), an image of each page so each token can be ancered to a specific position in the image, all the figures that are the source for the images deposited in BLR and linked to the source document and the taxonomic treatments in TreatmentBank, and a series of CSV files that include all the information from the tagging.
When something is changed in the tagging, the CSV files will be altered, and thus the versioning is important.

In some cases, this might included several hundred files, well beyond the limit currently set for a deposition.

Is an extension of the maximum file number per deposit something that could be discussed? If so, let's pursue this.

**Comment by lnielsen** [comment]
We discussed this at the meeting at CERN.
