### ISSUE TITLE
PID #<PersistentIdentifier depid:6 / rec:d99ce3c3-42e2-44ab-b12e-5c5a1e81d0d5 (R)> could not be resolved.

### ISSUE THREAD

**Issue by amoureba** [zenodo/zenodo#1438]
Hello,

I can not publish a record on my invenio instance. Indeed, after having installed invenio 3. I integrate zenodo to my project. The data is stored in a database but can not be published. I was asked to look at RECORDS_UI_ENDPOINTS, but I do not know what to do. (sorry if this is not the right place to ask this question) Thanks !

![capture d ecran 4](https://user-images.githubusercontent.com/14302634/37358686-9d8e5d64-26e3-11e8-9b17-962c81595fb9.png)

**Comment by lnielsen** [comment]
I think this was solved via the Gitter channel.
