### ISSUE TITLE
records: endnote export not complete

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#144]
The export of bibliographic of publication data for Endnote is not complete and missing the complete data for a citation of a publication. Can this be augmented?

**Comment by lnielsen** [comment]
Yes for sure. Do you have an example record where you can show us what information is missing.

**Comment by myrmoteras** [comment]
Here is a list of bibliographic references.

http://osuc.biosci.ohio-state.edu/hymenoptera/manage_lit.list_pubs?author=Agosti&Submit=Submit+Query

an example on Zenodo
Agosti, D.. (2006). Biodiversity data are out of local taxonomists' reach. Zenodo. 10.1038/439392a

and how it should read
Agosti, D.. (2006). Biodiversity data are out of local taxonomists' reach. Nature 439: 392. DOI....

or a book

Agosti, Donat et al.. (2000). Ants: Standard methods for measuring and monitoring biodiversity. Zenodo. 10.5281/zenodo.11736 

should read

Agosti, D., J. D. Majer, L. E. Alonso and T. R. Schultz. 2000. Ants: standard methods for measuring and monitoring biodiversity. Smithsonian Institution Press, Washington, DC. 280 pp.

**Comment by lnielsen** [comment]
Endnote support have been removed.
