### ISSUE TITLE
communities: bug in the community details template

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1441]
Requires fix to the template: https://github.com/inveniosoftware/invenio-communities/blob/ccadd4049b8c55b0ee7cd6fccdf4657ecec9dcd1/invenio_communities/templates/invenio_communities/new.html#L149
<a href="https://i.imgur.com/Ic3Cf2v.png">
  <img src="https://imgur.com/Ic3Cf2vl.png" />
</a>

**Comment by slint** [comment]
Closed via https://github.com/inveniosoftware/invenio-communities/pull/119
