### ISSUE TITLE
records: bibtex serializer should escape the % sign in bibtex record

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1442]
If you create a record with % in the title "Test 100% title", the bibtex serialization should escape the % sign.

**Comment by frederickjansen** [comment]
To add to this, I believe $ and & should be escaped too. Not sure if that's currently the case already.

**Comment by slint** [comment]
The place for this is inside the [`bibtex.py` serializer](https://github.com/zenodo/zenodo/blob/af6047f37b4a5a33cc9cb497b95559949cc5a30c/zenodo/modules/records/serializers/bibtex.py#L146-L152).

**Comment by pseyfert** [comment]
https://zenodo.org/record/842249/export/hx

adding `_` to the pool of characters that need to be escaped.
