### ISSUE TITLE
"Unknown error occured" when adding author metadata

### ISSUE THREAD

**Issue by MaxNoe** [zenodo/zenodo#1443]
We get an "Unknown error occured" for our most recent tags after we added author metadata in a `.zenodo.json` for this repository: https://github.com/fact-project/fact-tools

See: https://zenodo.org/account/settings/github/repository/fact-project/fact-tools#

Any help on how to fix this would be highly appreciated.

**Comment by moble** [comment]
I wonder if this is because you don't list an `"upload_type"` entry.  Googling for other repositories with this file, they seem to contain that entry.  This may be related to #1447, which describes getting a 500 error whenever the metadata is incomplete.

**Comment by MaxNoe** [comment]
I was under the impression that metadata not provided in the json is extracted from the github data.

**Comment by MaxNoe** [comment]
I added upload_type and keywords, still the same: 

* https://github.com/fact-project/fact-tools/pull/350
* https://zenodo.org/account/settings/github/repository/fact-project/fact-tools#

**Comment by moble** [comment]
@MaxNoe So should this issue be closed, in favor of #1448?

**Comment by MaxNoe** [comment]
Yes, as this seemed to be the root cause and is more specific
