### ISSUE TITLE
Update invenio depdendencies to v1.0.0

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1444]
Since most Invenio core packages are now `v1.0.0`, updating one of them on Zenodo requires bumping all other versions to `v1.0.0` as well. Updating packages means fixes + features and maybe behaviour changes on Zenodo. The following packages so far were updated (taken from the [big list of Invenio packages](https://github.com/inveniosoftware/invenio/wiki/Invenio-3.0-Build-Status)):

- `invenio-rest v1.0.0` 
    - CORS installed by default
    - [x] **TODO:** Sentry ID in REST error responses as `error_id` (should be used in Deposit forms and Search results error display :tada:)
- `invenio-records-rest v1.0.1`
    - Datacite v4.1 :tada: :taco:
    - Unicode doesn't change sorting now (closes #1227)
    - removes `invenio-query-parser` dependency (probably safe for us to remove as well)
- `invenio-pidstore v1.0.0`
    - introduces `PIDSTORE_RECID_FIELD`, which doesn't affect us though
- `invenio-search-ui v1.0.1`
    - [x] **TODO:** Fix facet to display selections that don't have any results (addressing inveniosoftware/invenio-search-js#111)
- `invenio-oauthclient v1.0.0`
    - [ ] **TODO:** Test alembic migration for tables to add Timestamp columns
        - ~~:warning: **Important** For zero-downtime, there's a need for an intermediary migration step, which means the existing recipe has to be split into two recipes...~~
    - [x] **TODO:** Check if redirects work as expected (https://github.com/inveniosoftware/invenio-oauthclient/commit/2d6256ed2ac729f6c679265ec0c3053ec7298383). *Note: for some reason the redirect from ORCiD goes to `http` instead of `https`...*
    - Remote access tokens are no longer displayed fully in plaintext
- `invenio-oauth2server v1.0.0`
    - Fixes personal token name's length validation in settings form
- `invenio-oaiserver v1.0.0`
    - [x] **TODO:** OAI-PMH XSL has to be set manually via `OAISERVER_XSL_URL` and be part of Zenodo's static files (https://github.com/inveniosoftware/invenio-oaiserver/commit/112d4248c72535bdf17638e6517d890441ca5197)
- `invenio-pidrelations v1.0.0a4`
    - [x] **TODO:** Compare DB schemas and create alembic stamp for the recipe
- `Jinja v2.10`
    - [x] **TODO:** `tojson` filters by default safe now. Check if deposit forms or other places using this work as expected...
- `invenio-db v1.0.0`
  - ~~`psycopg2-binary>=2.7.4` instead of `psycopg2`~~ (this will happen on `invenio-db v1.0.1`)
- `invenio-indexer v1.0.0`, `invenio-search v1.0.0`, `invenio-theme v1.0.0`, `invenio-userprofiles v1.0.0`, `invenio-records-ui v1.0.0`, `invenio-records v1.0.0`, `invenio-marc21 v1.0.0.`, `invenio-logging v1.0.0`, `invenio-jsonschemas v1.0.0`, `invenio-formatter v1.0.0`, `invenio-access v1.0.0`, `invenio-accounts v1.0.0`, `invenio-i18n v1.0.0`, `invenio-mail v1.0.0`, `invenio-admin v1.0.0`, `invenio-assets v1.0.0`, `invenio-base v1.0.0`, `invenio-celery v1.0.0`, `invenio-config v1.0.0`, `invenio-formatter v1.0.0`

------

## Migration actions

1. [ ] Finish/Address all **TODO**s from above 
1. [ ] On builder:
    1. [ ] `fab update build`
    1. [ ] Test DataCite 4.1 DOI registration
    1. [ ] Test DataCite update admin task
    1. [ ] `zenodo alembic stamp 1d4e361b7586`  (`invenio-pidrelations` initial recipes)
    1. [ ] Put up backup website for max 10min downtime
    1. [ ] `zenodo alembic upgrade bff1f190b9bd` (`invenio-oauthclient` Timestamp recipe)
    1. [ ] `fab deploy`
    1. [ ] Put down backup website

## Future Upgrades

[`github3.py >= 1.0.0`](https://github3.readthedocs.io/en/develop/project_changelog.html#id2): We're using `1.0.0a4` atm, which has some of the changes mentioned in the changelog.

**Comment by slint** [comment]
### Alex packages

- invenio-rest
    - CORS installed by default

**Comment by ChiaraBi** [comment]
- invenio-access v1.0.0
- invenio-accounts v1.0.0
- invenio-i18n v1.0.0
- invenio-mail v1.0.0

**Comment by lnielsen** [comment]
Deployed
