### ISSUE TITLE
api: Internal Server Error when updating metadata if field is missing

### ISSUE THREAD

**Issue by moble** [zenodo/zenodo#1447]
When using [the API](http://developers.zenodo.org/#update) to update the metadata for a previously published deposition, it is very easy to leave out some of the keys — like `doi`, for example.  When this is done, and the user tries to save or publish the updated version, the server returns a 500 error through the API.  If the user then tries to save or publish the updated version via the website, the same 500 error appears.  This case is even worse, because the web interface doesn't mark the DOI as a required field, so it is completely mystifying that the deposition can neither be saved nor published.

It would be much better if the error message could explain why the error is happening.  Or perhaps this could be avoided entirely when the metadata is updated.  In python, this would work by taking the required subset of the current metadata as a dictionary, and then updating that dictionary with the user's input dictionary.  If any of the required entries are changed by the user, they would be updated correctly, but the updated dictionary would retain any other required entries unchanged, while also allowing non-required entries to be added or altered.

**Comment by nuest** [comment]
Is there any way I can find out which field is causing the error? I am only changing one field value, everything else in unchanged, and I always get the same response:

```
{
  "error_id": "d7f928a617cb4b37872d100f046b2382",
  "message": "Internal Server Error",
  "status": 500
}
```

The sent JSON is

```
{'metadata': {'access_right': 'open',
              'communities': [{'identifier': 'zenodo'}],
              'creators': [{'affiliation': 'Institute for Geoinformatics, '
                                           'University of Münster',
                            'name': 'Daniel Nüst',
                            'orcid': '0000-0002-0024-5046'},
                           {'affiliation': 'University and State Library, '
                                           'University of Münster',
                            'name': 'Marc Schutzeichel',
                            'orcid': '0000-0001-9675-1893'},
                           {'affiliation': 'Institute for Geoinformatics, '
                                           'University of Münster',
                            'name': 'Markus Konkol',
                            'orcid': '0000-0001-6651-0976'}],
              'description': '<p>All blog entries of the blog for the research '
                             'project <strong>Opening Reproducible '
                             'Research</strong> (o2r, see also <a '
                             'href="http://gepris.dfg.de/gepris/projekt/274927273">Offene '
                             'Reproduzierbare Forschung</a> @ DFG GEPRIS), '
                             'online at <strong><a '
                             'href="https://o2r.info">https://o2r.info</a></strong>.</p>\n'
                             '\n'
                             '<p>o2r was funded by the German Research '
                             'Foundation (Deutsche Forschungsgemeinschaft, '
                             'DFG) under project numbers PE 1632/10-1, KR '
                             '3930/3-1 and TR 864/6-1.</p>',
              'doi': '10.5281/zenodo.1485438',
              'language': 'eng',
              'license': 'CC-BY-4.0',
              'prereserve_doi': {'doi': '10.5281/zenodo.1485438',
                                 'recid': 1485438},
              'publication_date': '2018-11-13',
              'title': 'Opening Reproducible Research: a research project website and blog',
              'upload_type': 'other',
              'version': '2018-11-16'}}
```

**Comment by moble** [comment]
@nuest Good question.  Just to be sure what's happening, am I right in thinking that you retrieved the metadata, altered one field, and then tried to `PUT` the new metadata onto the server?  Which field was it?  What happens if you delete your current draft, and just try to repeat those steps *without* actually changing the metadata at all?  If that also doesn't work, I'd say you should open a new issue because that would suggest to me that they've broken the metadata validation.

For what it's worth, your metadata all looks reasonable to me, and I've tried creating a brand new deposit in the sandbox with exactly your metadata, except for the `preserve_doi` tag.  I was actually able to alter the metadata via the API, but once I tried to publish it (either via the API or the web interface), it gave me an "Internal Server Error".

**Comment by nuest** [comment]
@moble Thanks for taking a look.

Yes, you guess correctly, the changed metadata field is `version`. Before I changed the metadata, it worked. The code is now online here, maybe it helps to find the culprit:

https://github.com/nuest/o2r-project.github.io/blob/master/zenodo_release_pdf.py

**Comment by nuest** [comment]
@lnielsen Anything we can do from our side to help at this point?

**Comment by slint** [comment]
https://github.com/zenodo/zenodo/pull/1681 Should solve this issue, or at least the part where the `doi` field is removed and then puts the deposit in an invalid state. The API will not return a 400 status with a proper message about which field is affected (the UI will error-highlight the DOI field as well). This is not yet deployed on https://zenodo.org though since we first want to go through some testing in https://sandbox.zenodo.org to make sure it doesn't break things.

Unfortunately, for deposits that are currently in this invalid state, the only solution is to perform an [`POST /api/deposit/depositions/:id/actions/discard`](http://developers.zenodo.org/#discard) call and then re-edit the deposit. **This will though discard any other changes made to the deposit, so keep a copy if needed.**

**Comment by nuest** [comment]
Is this deployed on sandbox.zenodo.org already? Would like to test.

**Comment by nuest** [comment]
I tried my script on sandbox.zenodo.org and it works. I had to remove the `metadata.doi` property from the updated metadata, because I got an error it may not be changed, yet it was not changed. _Would you consider handling that on the server side, i.e. before issuing an error the DOI may not be changed, check if the value is actually different?_

**Comment by nuest** [comment]
_Correction_: This also worked now on https://zenodo.org. From my side this can be closed.
