### ISSUE TITLE
deposit: BLR adding a new type of publication to Zenodo

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#145]
We would like to add another "Type of publication" for jounrals or  books, that this  something like "publication_part" or "publication_extract". These are just the one to few pages that cover a particular treatment we now can link to the original digital representation of the treatment with the DOI.

What would you suggest?

Related to this will be a followup request to add an element "part_of" to indicate the relationship between a treatment and the entire article from where it has been extracted. Similarly it would also be helpful to have an element "has_parts" to indicate the link between a publications and its parts, that are as such available on BLR

**Comment by lnielsen** [comment]
I was looking through some different vocabularies to see if there was already a term for a publication part, but I wasn't able to find something usable. The nearest was book section and report part.

I think "Publication part" is likely the most generic. Or could "Treatment" possibly be used (I guess not?)

Regarding hasPart/isPartOf relationships you can already add them in the related identifiers field:

![screen shot 2015-02-03 at 14 40 48](https://cloud.githubusercontent.com/assets/1698163/6021039/b3839ab2-abb2-11e4-9d46-7683af71efce.png)

Display we can perhaps think of better ways to display these relationships on the record.

**Comment by lnielsen** [comment]
Add "Deliverables", "Description of Work" as well

**Comment by myrmoteras** [comment]
we still struggle with the language. The botanists most likely will use "clipping", other terms could be "excerpt", "extract" which all are the same as "part of". The difference is only that clipping intends to display the sense that this piece has specifically be cut. I'd liked to know what the librarians use as term - if there is one
