### ISSUE TITLE
metadata: glottolog language code support

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#1454]
Reported by the user.

Glottolog (http://glottolog.org/) contains a more verbose language classification. This is perhaps a separate field to the already existing ``language`` field, which is ISO compliant and widely inter-operable, nonetheless, this is might be relevant for linguistics materials.

**Comment by lnielsen** [comment]
While it would be nice to support very detailed metadata, I think ISO is sufficient for nearly all records.
