### ISSUE TITLE
question: how to list items in a collection using the Zenodo Rest API  

### ISSUE THREAD

**Issue by monperrus** [zenodo/zenodo#1475]
I want to automate some tasks based on a Zenodo community, in particular to generate various exports.

How to list all items in a community using the Zenodo Rest API?

**Comment by monperrus** [comment]
ping?

**Comment by lnielsen** [comment]
```
curl -H "Accept: application/json" "https://zenodo.org/api/records/?communities=ecfunded"
```

Supported formats:
https://github.com/zenodo/zenodo/blob/master/zenodo/config.py#L770-L783

It's better to direct these questions to https://zenodo.org/support

**Comment by monperrus** [comment]
Thanks a lot for your answer.

> It's better to direct these questions to https://zenodo.org/support
>
If I ask the question there, will the question and its answer be indexed by Google?

**Comment by lnielsen** [comment]
> If I ask the question there, will the question and its answer be indexed by Google?

I don't know. The reason is that we prefer to keep user support separate from our development tasks.
