### ISSUE TITLE
records-ui: version field is not used in list of versions

### ISSUE THREAD

**Issue by melund** [zenodo/zenodo#1478]
I have added a lot of old versions of our code on Zenodo. 

Unfortunately, the system now shows the oldest version on top of the version list. And if I click the any version but the oldest zenodo tells me a newer version is available and point to oldest version :(

![image](https://user-images.githubusercontent.com/1038978/40388716-805efd70-5e10-11e8-97d4-ad30c9f2d40c.png)

Ideally, I would like to sort the version list by publication date or as workaround change their version index so things will appear in a sensible order.

The is also a small bug lurking here: Zenodo reports the version index instead of the version label  if the version is not part of the 5 latest records added. See the picture below where version "2.1.0" is reported as "Version 3". Zenodo is using the [version index here instead of the label](https://github.com/zenodo/zenodo/blob/90a91765ce3e3ef2521af4e5a6deae8baa62923d/zenodo/modules/records/templates/zenodo_records/box/versions.html#L27).

![image](https://user-images.githubusercontent.com/1038978/40388878-0b50cda0-5e11-11e8-8683-68f11fd454ec.png)

**Comment by lnielsen** [comment]
Versions are shown in the order they are added. We can reorder this for you, but could I just ask you to report the problem via https://zenodo.org/support.

The bug with "Version 3" we will fix here.

**Comment by lnielsen** [comment]
- [ ] Fix template

**Comment by melund** [comment]
> Versions are shown in the order they are added. We can reorder this for you, but could I just ask you to report the problem via https://zenodo.org/support.

Thanks a lot @lnielsen. I will send a request to support.  

I would still wish that the version-box and the 'all versions' page would sort using the publication date by default if the field existed. That should prevent problems if people, like me, upload in the incorrect order.
