### ISSUE TITLE
Zenodo returning inconsistent results for similar queries

### ISSUE THREAD

**Issue by punkish** [zenodo/zenodo#1493]
Take a query like the following (shown with a snippet of its response below it)

    https://zenodo.org/api/records/?communities=biosyslit&q=panicum&type=image&size=30&page=1

    {
    "aggregations": {
        "access_right": {
        "buckets": [
            {
            "doc_count": 37, 
            "key": "open"
            }, 
            {
            "doc_count": 33, 
            "key": "closed"
            }, 
            {
            "doc_count": 2, 
            "key": "embargoed"
            }
        ], 
        "doc_count_error_upper_bound": 0, 
        "sum_other_doc_count": 0
        }, 
        …
        
        
    }, 
    "hits": {
        …
        
        "total": 65
    }, 
    "links": {
        "next": "https://zenodo.org/api/records/?sort=bestmatch&q=panicum&communities=biosyslit&type=image&page=2&size=30", 
        "self": "https://zenodo.org/api/records/?sort=bestmatch&q=panicum&communities=biosyslit&type=image&page=1&size=30"
    }
    }

As you can see from the above, there are two issues:

1. The `aggregations` are reporting 72 documents while the `hits.total` key is reporting 65 documents. Which one should I believe?

    1a. A related problem is that while 37 are listed as **open**, 33 as **closed** and 2 being **embargoed**, the embargoed documents are not listed in the result at all. I would have expected at least the basic metadata of all the documents even if the link to the full document wouldn't be available for the closed and the embargoed ones. In fact, what is even the point of telling me something is there (2 are embargoed) but then not even showing me anything about those records?

2. And this one is the bigger problem. Not all the records have all the fields. The documents that are closed access don't have links to the images, for example. A similar problem occurs when the document is **open** but the image is `svg`. The thumbnail250 field is not present at all. I would have expected for the key to be there but be empty.

My contention is this: for a given query, Zenodo should *always* return consistent results. By *given query* I mean a query where the params are the same even if their values may be different. The response from Zenodo should always contain the same number of fields even if some of the fields may be empty. Otherwise it will become very difficult for the developer on the other end to be able to guess what results Zenodo might return for any given combination of query params and values.

**Comment by punkish** [comment]
Thanks @lnielsen. My response re. your logic for my first point: Your language "You hit checkbox on image" implies that you are mixing backend and frontend. In my view, the API should be agnostic vis a vis the frontend capabilities. And, if it does make any concessions for a frontend use case, that concession should be a subset of the more universal use cases. An application developer has no idea what the backend technology is, and should not have to worry about whether you are using ES or post-filters or whatever. All that matters is the response that I, the developer gets. That response should be completely self-describing and complete. As is, I get a number that sounds like "total" (heck, it is called total) except it doesn't equal to the total of the components that sound like components.

Look at my point-of-view. I conduct a query, I get a response, and I want to tell my user (doesn't matter if that is a human or an application) how many records I got back for my query. I have no way of doing that. In fact, in the case of "Panicum", I get 72 records, out of which 37 are open access so either 33 (closed) or 2 (embargoed) or 33+2 (closed+embargoed or, in other words, the not-open-access) have images. Except, only 9 of them have thumbnails. I really don't know what to tell my user?

This brings me to #2. I don't mind checking `if key in set` but how do I know what curveball the backend is going to throw at me next? In the beginning I assumed that all records had a **thumbnail** field until I found they didn't (because some were SVGs). Then I started checking for the presence of **thumbnail250** and life was good UNTIL I ran into records that didn't have images at all (the closed access records). A few months, year, decades down the line, I could run into yet some other edge case where Zenodo is not returning something I expect it to return. Wouldn't it be simply more logical to return all the fields for every record but just make them empty or null where they don't apply or are otherwise not available.

My view is that the backend should deliver a consistent, complete, self-describing, what-you-see-is-exactly-what-you-get response every single time, and then let the users manipulate it to their purpose as they see fit.

**Comment by punkish** [comment]
I had another interesting thought.

> a) query "panicum" has a total hit set of 72 records.
> b) you now apply a filter: type = image. hit set is now reduced to 65 records

The above assumes that given `?q=panicum&type=image` the main query is for "panicum" and the `type` is an after filter. But, what if the main query were for all the records that are of the type image, and then within those, the sub query was for records containing the string "Panicum"? 

Thankfully, we don't have the ambiguity because in the query string, all the query parameters are first class citizens and carry equal weight. In other words, query "Panicum" subquery type=image should yield the same result as query type=image subquery text contains string "Panicum"

**Comment by lnielsen** [comment]
This discussion is far easier to take chat of videocon. Frontend/backend is not mixed IMHO, and results are consistent. ``hits.total`` give you the exact number of records in result set[1]. Aggregations show correct counts[2] prior to application of any filters. There's two problems to address 1) documentation and 2) counts in an aggregation should take other filters into account except for it's own filter (in your simple case above, this will produce what you expect and my other use case still works).

Re 2) I think it's just because we didn't finish yet. We will provide a ``thumb250`` for all records, just that for closed access records it will be the same generic image (this we already discussed back in April when you were here). That said, when working with an API, edge cases are unavoidable. Take our Zenodo-GitHub integration, developing the first prototype was very easy, however getting it to work with all the different configuration of repositories, organisations, permissions and users was very hard. This is not because GitHub has a bad API, but more that they support lots of features.


[1] actually due to distributed nature of ES then sometimes it's actually an approximation (similar to google saying "roughly 10.000 results").
[2] note these counts can also be approximate, due to the distributed nature of ES

**Comment by lnielsen** [comment]
I've extracted two different tasks from this issue (#1497 + #1498) so they can be worked on independently and closing the issue. Ok?
