### ISSUE TITLE
docs: FAQ update

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#150]
Add structure to FAQ (e.g. deposit, github, policies, ...), and add many more common questions.

**Comment by lnielsen** [comment]
- "Can I add an existing upload to a community?"
- "How can I include the Zenodo DOI in the document?"
- "How can I replace an already published file?"
- "Can I remove my upload?"

**Comment by lnielsen** [comment]
Author list in GitHub

**Comment by LibrarPotter** [comment]
Add "data", "source code", and "interactive resources e.g. lessons" to the "What can I upload" section.

**Comment by benmarwick** [comment]
Can you point me to where I can find an answer to "How can I replace an already published file?" Thanks!

**Comment by lnielsen** [comment]
You will have to send a request to info@zenodo.org with the URL to the record - if the file is small just include it in the email. Note that since we issue DOIs for each upload, there's certain constraints on what's possible.

**Comment by pherterich** [comment]
Your current version (https://zenodo.org/faq as of today) contains the question "Why is my closed access upload not on the front-page?" twice btw.

**Comment by krzysztof** [comment]
@pherterich Thanks for catching this, it'll be fixed in the next update later today :+1:

**Comment by sm86** [comment]
I think you can close this issue. Is there anything need to be worked upon!

**Comment by krzysztof** [comment]
@sm86 Hey, this will require checking against our FAQ (help.zenodo.org) to see if it's still relevant, but it's not a good GSoC task.
