### ISSUE TITLE
previewer: zip files crash the web application

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1518]
Very large or malformed/non-standard zip files might cause an `std::bad_malloc` error when the previewer attempts to parse their header to produce the directory tree. The reason this happens also has to do with the underlying XRootD bindings probably, since if one attempts to do the same in the local filesystem, everything seems to work fine. 

The solution is probably to enforce a size limit directly to the previewer, which is checked beforehand instead of attempting the preview.

Example record/file: https://zenodo.org/record/1299599

Steps to reproduce in a shell:

```python
from zipfile import ZipFile
from invenio_files_rest.models import FileInstance

# With XRootD...
fi = FileInstance.query.get('c686ed52-f304-442b-91e9-e4fed713514b')
with fi.storage().open() as fp:
    zf = ZipFile(fp)
    # zf = ZipFile(fp, allowZip64=True)  # this doesn't change anything...
    # ...shell crashes with the following message:
    # terminate called after throwing an instance of 'std::bad_alloc'
    #   what():  std::bad_alloc

# Locally...
with open('1.0.0.zip', 'rb') as fp:
    zf = ZipFile(fp)
    print(len(zf.filelist))
    # 20024
```

As a counter-example, the following files, although larger than 2Gb, just raise an exception: https://zenodo.org/record/1298604

**Comment by siko1056** [comment]
Same problem here: https://zenodo.org/record/2547325

It just looks ugly and not professional, when you are welcomed by an preview error. I agree with the proposed solution of @slint :

> The solution is probably to enforce a size limit directly to the previewer, which is checked beforehand instead of attempting the preview.

**Comment by slint** [comment]
This has been fixed and deployed now via a patch in the underlying storage access library. Bigger ZIP files (that are not malformed), can be previewed normally now
