### ISSUE TITLE
openaire: Make RCD communities easier to find

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1523]
**User story:**

As a RCD-User, I want easily find OpenAIRE RCD Communities in the Zenodo deposit form, so that I can go directly to Zenodo to upload my research instead of going through the OpenAIRE RCD.

Upload form:
- Instead of connect logo display in tiny text: "Part of OpenAIRE Fisheries Community”.

**Comment by lnielsen** [comment]
Suggested change:

![dropdown](https://user-images.githubusercontent.com/1698163/42450926-04feffc2-8386-11e8-900c-617cd9e87983.png)

![unselected](https://user-images.githubusercontent.com/1698163/42451270-01af15ea-8387-11e8-9ebb-d935809810d0.png)

**Comment by slint** [comment]
`Filter by OpenAIRE communities` checkbox extracted into https://github.com/zenodo/zenodo/issues/1563
