### ISSUE TITLE
openaire: direct indexing of software

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1533]
- Update direct indexing rules to also send software to OpenAIRE.
- Needs to wait until the software has been launched in production on the OpenAIRE portal (eta September), otherwise, there will be broken links on Zenodo.

**Comment by lnielsen** [comment]
Also need to direct index ``other`` products

**Comment by alessiabardi** [comment]
Please double check how you are calling the direct indexing for products of type "other".
Looking at this: https://explore.openaire.eu/search/publication?articleId=od______2659::2738e0a07c0f6bd4e56db899b2749fe7 it looks like you are setting 

```
"resourceType":"0020",
"type":"publication"
```

while it should be `"type":"other"`.

For software, please ensure you use `"type":"software"`.

**Comment by ChiaraBi** [comment]
@alessiabardi Could you please tell me what's the `resourceType` for `software`?

**Comment by alessiabardi** [comment]
It's 0029. For the full list of available resourceType values: http://api.openaire.eu/vocabularies/dnet:publication_resource
