### ISSUE TITLE
global: could not find any downloads that satisfy the requirement Invenio-Kwalitee

### ISSUE THREAD

**Issue by bouzlibop** [zenodo/zenodo#158]
When trying to `inveniomanage runserver` I get this error msg: 
>Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/zenodo/bin/inveniomanage", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/adrian/.virtualenvs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "/home/adrian/.virtualenvs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/adrian/.virtualenvs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/adrian/.virtualenvs/zenodo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pillow==2.0.0,>=2.4.0

As described [here](https://bitbucket.org/rptlab/reportlab/issue/55/setuptools-80-cannot-install-reportlab-318):
>Because of changes to how version specifiers are interpreted in PEP 440, setuptools 8.0 (released 13 Dec 2014) interprets these conditions with and instead of or, and since it's not possible to install a version that's both 2.0.0 and greater than 2.4.0, it's not possible to use setuptools to install reportlab from PyPI anymore. 

I think the solution here is to move to the newer version of `reportlab`, where they fixed the requirements.

**Comment by lnielsen** [comment]
Are you sure you have the right requirements? You should have latest reportlab (v3.1.44) according to ``base.requirements.txt`` (see [here](https://github.com/zenodo/zenodo/blob/master/base.requirements.txt#L127)).

**Comment by bouzlibop** [comment]
@lnielsen you are right, false alarm - mine requirements file was outdated. Sorry for that ;/

Now I made sure that everything is up to date in my local env, but I still get some problems with the smooth installation process.

I got this error:
>Collecting Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))
  Could not find any downloads that satisfy the requirement Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))
  No distributions at all found for Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))

As I see `kwalitee` was added in the `dev.requirements.txt`. Shouldn't then `Invenio-Kwalitee` be removed from `extras_require` in `setup.py` ?

**Comment by lnielsen** [comment]
I think this can be closed now?

**Comment by bouzlibop** [comment]
I still got this problem with `Invenio-Kwalitee` when following [quick start quide](http://zenodo.readthedocs.org/en/latest/installation.html#quick-start) with fresh environment:

```
Obtaining Invenio from git+https://github.com/zenodo/invenio@pu-zenodo#egg=Invenio (from -r requirements.txt (line 29))
  git clone in /home/bouzlibop/.virtualenvs/zenodo-test/src/invenio exists with URL https://github.com/bouzlibop/invenio
  The plan is to install the git repository https://github.com/zenodo/invenio
Collecting Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))
  Could not find any downloads that satisfy the requirement Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external Invenio-Kwalitee to allow).
  No distributions at all found for Invenio-Kwalitee (from zenodo==1.0.0.dev0->-r requirements.txt (line 30))
```

Shall I prepare PR with changing [this line](https://github.com/zenodo/zenodo/blob/master/setup.py#L52) to `kwalitee` ? (this seems to solve the problem)
