### ISSUE TITLE
github: update README.md automatically

### ISSUE THREAD

**Issue by apeltzer** [zenodo/zenodo#1582]
Hi everyone,

many users utilize the badges to show Zenodo DOIs in their respective GitHub repositories. (example: https://github.com/nf-core/methylseq ) However, when new releases are created the current workflow is as such:

a.) A new release is generated
b.) Zenodo issues a DOI
c.) THe user has to copy the DOI/Badge to their Github repository / readme.md and update accordingly. 

This has a couple of (probably unwanted) side effects, mainly:

- the tagged release contains either no DOI badge at all or an outdated (from the previous version) one
- users have to manually update the DOI in their repository each time they release a new version

In an ideal world, creating a tag would be possible via e.g. a deployment trigger on CI -> then creating a DOI and attaching this to the Readme to push out a new release which is then also archived via Zenodo with correct DOI. 

Maybe I have missed that, but I couldn't find a way to do that right now instead of the manual approach?

**Comment by slint** [comment]
As @rettinghaus said, using the concept DOI mentioned under the versions box will always redirect to the latest version record of the repository on Zenodo:

![image](https://user-images.githubusercontent.com/1814661/45763687-4e6d3780-bc31-11e8-9c48-e6f0d376bcdf.png)

**Comment by katrinleinweber** [comment]
This dilemma has been discussed under https://github.com/zenodo/zenodo/issues/276#issuecomment-114731927 as well.

How about this (rough) idea sketch to solve it: The badge's `img`-`src` URL could be changed to an fixed URL, and Zenodo sets up automatic redirects on their end, which are updated with each release.

That way, a different badge visual could be displayed. GitLab redirected both the Gemnasium badge visual and its original link [after acquiring them](https://docs.gitlab.com/ee/user/project/import/gemnasium.html), see [some](https://adrianperez.codes/services-and-badges-increase-your-project-visibility-and-popularity/) of [these](https://github.com/prometheus/client_ruby/issues/88) example [READMEs](https://github.com/search?q=%22gemnasium.com%22+filename%3Areadme.md&type=Code). Kinda sneeky, but effective ;-D
