### ISSUE TITLE
Cannot see my personal access token in Zenodo

### ISSUE THREAD

**Issue by sdaau** [zenodo/zenodo#1586]
Some time ago, I have made a personal access token (PersonalNoPublish) on Zenodo, which gets shown in my profile's Applications:

![zenodo_token01](https://user-images.githubusercontent.com/26737749/44465678-90995e00-a61e-11e8-84aa-7dc1bcd5eb13.png)

However, when I click on this token, then I cannot see the GUID/token string anywhere?:

![zenodo_token02](https://user-images.githubusercontent.com/26737749/44465811-ef5ed780-a61e-11e8-9fba-017807233af8.png)

Is this how it's supposed to work? What happens if I lost my token string - is the only recourse deleting the old token and making a new one? If so, could the documentation please be updated to let users know?

**Comment by lnielsen** [comment]
Thanks for reporting the issue. Please, could I ask you to use our support line at http://zenodo.org/support for reporting this kind of issues? We prefer to have our development tasks separate from user support related issues, as usually support issues need to be digested into one or more development tasks.

The token is not shown again for security purposes, and there's a warning on the page that shows the generated token that you won't see the token again.
