### ISSUE TITLE
records: doi badge pop-up should display plain DOI

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1587]
Add plain DOI into the list of formats easy to copy/paste:

![screen shot 2018-08-23 at 15 09 50](https://user-images.githubusercontent.com/1698163/44527270-a70aec80-a6e6-11e8-92f8-13519cc54660.png)

**Comment by slint** [comment]
Closed via https://github.com/zenodo/zenodo/commit/e1dbc7ab7e381766c30bd4ba6101ae0947cb08e8
