### ISSUE TITLE
Issues generating DOIs for hippylib/hippylib repository

### ISSUE THREAD

**Issue by uvilla** [zenodo/zenodo#1592]
Good morning,

I am not sure if this is the correct outlet for this type of issues, but I also tried contacting Zenodo support without hearing back in several days.

Zenodo failed to generate DOIs for the last two releases (2.0.0 and 2.1.0) of my software with DOI [https://doi.org/10.5281/zenodo.596931](https://doi.org/10.5281/zenodo.596931).

I was hoping someone could help me understand and fix the issue.

The error message I am getting is simply:
```
{
 "errors": "Unknown error occured."
}
```
which, unfortunately is not of much help.

The GitHub payload is attached here: [GitHubPayload.txt](https://github.com/zenodo/zenodo/files/2340737/GitHubPayload.txt)

Between release 1.6.0 (the last release for which Zenodo was able to generate the DOI) and 2.0.0, two things changed:
- The tag for release 1.6.0 and all previous release looks like `v1.X.Y`, while I have dropped the `v` for the last two releases (for which Zenodo failed creating the DOI).
- I deleted the account of the GitHub user who created the `hippylib` organization (it was a dummy account called `hippylib-adm`), and transferred ownership to my personal GitHub account (@uvilla).

Thanks in advance!

**Comment by slint** [comment]
We're sorry for the slow response time on the support-line, because of the DB incident we had, we're allocating some extra effort in the recovery process. You will receive a reply concerning the issue, in our support line ASAP though :)
