### ISSUE TITLE
Permission required You do not have sufficient permissions to view this page.

### ISSUE THREAD

**Issue by wrathofquan** [zenodo/zenodo#1595]
I've submitted through the form multiple times now. Sorry if this is not the right place but I cannot edit uploads that I've made to a community that I [manage](https://zenodo.org/communities/berkeley-data-sciences/?page=1&size=20). Can someone advise on this?

**Comment by slint** [comment]
Editing records that you haven't uploaded yourself is not possible yet. We are planning to introduce multi-ownership capabilities for communities and their records in future features though.

*PS: In case the support form at https://zenodo.org/support didn't work, you can send us an email directly to info@zenodo.org. If you are the owner of the records and cannot edit them please contact us via email so we can have a better look*

**Comment by wrathofquan** [comment]
Hi Alexander,

I appreciate the reply. The issue is that I am the uploader, creator of
this Zenodo community, and a collaborator on the github repos that are
hooked into this Zenodo repository. I have a deadline for this project -
can you advise?

Thank you,
Josh
