### ISSUE TITLE
deposit: empty "_deposit.owners" and missing "_deposit.pid" for published deposits

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1597]
Some GitHub-originated deposits have  `_deposit.owners: []` and are missing the `pid` key even though they are published. This is a problem since users are not able to access the deposit (because of permissions) or delete/discard the deposit to correct the situation... The solution (from an admin POV) is to add the missing values correctly and then call `.discard()` on the deposit.

The most probable reason for that is that the deposit never goes through [this part](https://github.com/inveniosoftware/invenio-deposit/blob/f243ea1d01ab0a3bc92ade3262d1abdd2bc32447/invenio_deposit/api.py#L238-L244) of the creation process since there is no `current_user` during a GitHub release... There are deposits even from 2017-06, so this is related to introducing versioning probably.  

Another reason might be the non-`with` use of `db.session.begin_nested()` [here](https://github.com/zenodo/zenodo/blob/81ff5429c823b07c68d71710cae346ba7a150a13/zenodo/modules/github/api.py#L87).

Finding such records is possible via this ES query:

```python
from invenio_search.api import RecordsSearch

query = RecordsSearch(index='deposits').filter('missing', field='_deposit.owners')
for r in query.scan():
    print(r._deposit.id)
```

**Update:** to fix these broken deposit do the following:

```python
from zenodo.modules.deposit.resolvers import deposit_resolver
from invenio_db import db

depid, deposit = deposit_resolver.resolve(123456)
deposit['_deposit']['owners'] = [<correct owner>]
deposit['_deposit']['pid'] = {'type': 'recid', 'value': str(deposit['recid'])}
deposit.commit()
db.session.commit()
deposit.discard()
db.session.commit()
```

**Comment by ChiaraBi** [comment]
Example of records whit this problem:
- `c23d5a77-c674-4da0-bddd-3aa6790066db`
- `5f2f904c-977b-437e-97d9-3f97fd83fede`
