### ISSUE TITLE
records: tombstone pages

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#160]

**Comment by lnielsen** [comment]
- [ ] Tombstone page should include: DOI, date of deaccession, reason for deaccession, message explaining our policies, and a message that a copy of the metadata is kept for record keeping purposes as well as checksums of the files.
- [ ] Define default reasons for deaccession (removed by Zenodo staff, spam, removal requested by owner, ...).
- [ ] Store in record or in pidstore? Impacts if DOI should be updated to point to different URL, or if it should just keep point to the Zenodo DOI.
- [ ] Interface needed for object removal instead of using the communities.

**Comment by lnielsen** [comment]
Adding this as tentative for Sprint 8. It's related to DOI deprecation and data model changes, so might be easy to do together with related tasks.

See #256, #102 and #217.

**Comment by lnielsen** [comment]
Only remaining issue to deal with is to review information presented on tombstone page and policies.

**Comment by katrinleinweber** [comment]
Hi @lnielsen! Could you please post an example of such a tombstone page? I tried https://stats.datacite.org/?fq=allocator_facet%3A%22CERN+-+CERN+-+European+Organization+for+Nuclear+Research%22&#tab-datacentres but CERN doesn't have any "missing" DOIs ;-)

Maybe a mockup to include as a positive example in a presentation?

**Comment by lnielsen** [comment]
Here's an example: http://doi.org/10.5281/zenodo.1285476 

DOIs are still registered in the handle system (i.e. URL still resolves), but metadata is no longer available in DataCite.

You have to look in the "Hidden" column instead (i.e. ~14k). Most of these are spam records.

**Comment by katrinleinweber** [comment]
Ah, OK, thanks for the hint! That spam record's page is generated from [`/zenodo_records/tombstone.html`](https://github.com/zenodo/zenodo/blob/fb2fb960e2719b062655125d9bcb06d3ac2a70a6/zenodo/modules/records/templates/zenodo_records/tombstone.html), right?

But is there also an example that _does_ display the metadata of a non-spam record?

I tried [DataCite's "Top 10 DOIs: failures"](https://stats.datacite.org/?fq=prefix%3A%2210.5281%22&fq=datacentre_facet%3A%22CERN.ZENODO+-+ZENODO+-+Research.+Shared.%22&fq=allocator_facet%3A%22CERN+-+CERN+-+European+Organization+for+Nuclear+Research%22&#tab-resolution-report) and found: https://zenodo.org/record/1196421. Does the embargo page look the same as a tombstone with metadata?

**Comment by lnielsen** [comment]
> But is there also an example that does display the metadata of a non-spam record?

No, that's not the point of the tombstone. It's only to have a page that says the record is gone, why it's gone, and that in case you really really need to know what it was, then we still have a copy of the metadata for the record.

> I tried DataCite's "Top 10 DOIs: failures" and found: https://zenodo.org/record/1196421. Does the embargo page look the same as a tombstone with metadata?

That could have been related to the DataCite MDS being down some few times during the spring and the DOI thus not being registered immediately.

**Comment by katrinleinweber** [comment]
> [...] tombstone [...] only to have a page that says the record is gone, why it's gone, and that in case you really really need to know what it was [...]

Well, one can assume that whoever clicks the DOI/link, does want to know.

> then we still have a copy of the metadata for the record.

Are such requests vetted in any way, granted only in special circumstances, etc.?
