### ISSUE TITLE
licenses: support CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by ChiaraBi** [zenodo/zenodo#1601]
https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by mbobra** [comment]
Thanks for opening this issue @ChiaraBi !

**Comment by ChiaraBi** [comment]
The license is on Zenodo, so this issue can be closed.

**Comment by ChiaraBi** [comment]
The license is on Zenodo, so this issue can be closed.
