### ISSUE TITLE
stats, views, download does not work?

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1610]
https://doi.org/10.5281/zenodo.1412365 no views nor downloads are shown for this deposit

**Comment by slint** [comment]
We had some issues in our stats/search cluster during the past week, and thus computation of some stats has been delayed. The raw views/downloads data is stored, but the aggregated values shown in the UI will be updated by next week. There are some independent version views though which went through despite the issues:

![image](https://user-images.githubusercontent.com/1814661/46212494-5ebe9a00-c336-11e8-8606-838d03381277.png)
