### ISSUE TITLE
openaire: many-to-many OpenAIRE to Zenodo communities

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1615]
Changes required to support this:

**Deposit**
- [x] Deposit UI
  - [x] Fix OpenAIRE type choices computation logic
  - [x] Change text "Indexed in OpenAIRE ..." to support multiple comma-separated values
- [x] Deposit API
  - [x] Handle [OpenAIRE subtype validation](https://github.com/zenodo/zenodo/blob/a3bcfa8e66c9609a8ac7789dca4ed9ab46e3431f/zenodo/modules/records/utils.py#L85-L106)

**Export**

~~- [ ] Export formats, rendering OpenAIRE communities (i.e. DataCite and DublinCore)~~

**Comment by ChiaraBi** [comment]
Since we are exporting only the Zenodo communities, we don't have to update the export formats.
