### ISSUE TITLE
Demo records problem on new installation

### ISSUE THREAD

**Issue by fmarco76** [zenodo/zenodo#1637]
I have just installed a demo site with zenodo for some tests but I cannot make it works with demo data.
I have followed the installation instructions and I am running all the requested containers. The instance is up and I can access the pages but the demo records are available only among the record in the admin console, nothing in the pages. Additionally, the installation create two communities but when I access the ecfunded community the web container crashes without any log and I have to restart the compose.

I am running on debian 9.5 and using docker 18.06.1-ce and docker-compose 1.22.0

**Comment by fmarco76** [comment]
I have the same problem even if I do not load the demo record but create a new one. When I try to access the record the web container stop to work without any log

**Comment by slint** [comment]
The `docker-compose` version of the web/worker is not really up to date and tested at the moment (we usually develop Zenodo locally using virtualenvs, see https://zenodo.readthedocs.io/en/latest/installation.html#development-installation). The reason the records are not displayed is probably because they have to be indexed (`zenodo index reindex -t recid && zenodo index run`)

**Comment by fmarco76** [comment]
I have indexed the demo record as well as the new record I have created. Nevertheless, I cannot see the demo records but only the new one and if I try to access these the web container stop to works. Maybe the problem is with the container.

I will try to set-up the development environment with virtualenv to verify if the problem is in the setup.

**Comment by fmarco76** [comment]
I have tried several times to install zenodo using the virtual environment approach and I have still the problems with demo records. All but the record 7559 are not visible. During the load record I get the following error in the celery daemon for all the record containing one or more files:

```
[2018-11-09 16:27:52,243: ERROR/ForkPoolWorker-1] Task zenodo_migrator.tasks.migrate_record[6cafc7e9-60fa-4516-871f-f96dc0647c4d] raised unexpected: <ValidationError: "'file_id' is a required property">
Traceback (most recent call last):
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/flask_celeryext/app.py", line 78, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/debian/src/zenodo-migrator/zenodo_migrator/tasks.py", line 67, in migrate_record
    migrate_record_func(record_uuid, logger=logger)
  File "/home/debian/src/zenodo-migrator/zenodo_migrator/transform.py", line 54, in migrate_record
    record.commit()
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/invenio_records/api.py", line 267, in commit
    self.validate(**kwargs)
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/invenio_records/api.py", line 126, in validate
    _records_state.validate(self, self['$schema'], **kwargs)
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/invenio_records/ext.py", line 41, in validate
    **kwargs
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/home/debian/.virtualenvs/zenodo/lib/python3.5/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'file_id' is a required property

Failed validating 'required' in schema['properties']['_files']['items']:
    {'description': 'Describes the information of a single file in the '
                    'record.',
     'properties': {'bucket': {'description': 'UUID of the bucket to which '
                                              'this file is assigned.',
                               'type': 'string'},
                    'checksum': {'description': 'Checksum the file. Starts '
                                                "with '<algorithm>:' "
                                                'prefix, e.g.: '
                                                "'md5:1234abcd...'",
                                 'type': 'string'},
                    'file_id': {'description': 'UUID of the FileInstance '
                                               'object.',
                                'type': 'string'},
                    'key': {'description': 'Key (filename) of the file.',
                            'type': 'string'},
                    'previewer': {'description': 'Identifier for previewer '
                                                 'needed to preview this '
                                                 'file.',
                                  'type': 'string'},
                    'size': {'description': 'Size of the file in bytes.',
                             'type': 'integer'},
                    'type': {'description': 'File type extension.',
                             'type': 'string'},
                    'version_id': {'description': 'UUID of the '
                                                  'ObjectVersion object.',
                                   'type': 'string'}},
     'required': ['bucket',
                  'checksum',
                  'file_id',
                  'key',
                  'size',
                  'type',
                  'version_id'],
     'title': 'File schema.',
     'type': 'object'}

On instance['_files'][0]:
    {'bucket': 'c49ae40d-8a77-4103-85ed-516f19608356',
     'checksum': 'md5:151e9c3d62c47dcb8a72e8e7452186ac',
     'key': 'SummerStudentReport-MihaiPatrascoiu.pdf',
     'size': 1058705,
     'type': 'pdf',
     'version_id': 'fcd37abf-e096-4ec6-8552-2f466333e5ff'}
```

The demorecords do not have files but only the URL. Am I missing some libraries downloading the files?

**Comment by fmarco76** [comment]
I have found the bug for this problem. It is in invenio-migrator. I have opened an issue there and provided a pull-request with the solution

See https://github.com/inveniosoftware/invenio-migrator/issues/77

**Comment by slint** [comment]
Keep in mind that the demo records provided are pretty old and coming from the legacy Zenodo instance that was still using Invenio v2 and had a lot of old and inconsistent records (Zenodo was migrated to Invenio v3 on Sep 2016).

I know that they are there and are part of the developer guide, but this is just because we haven't spent the time to update our developer docs. When we actually develop and test out new features or bug fixes for Zenodo we don't migrate old records to set things up, we just create new ones through the REST API or Deposit UI form.

There is a value in having demo records to help with developing Zenodo, but fixing what's already there is not part of our current plans.

**Comment by slint** [comment]
The best path in these cases is dumping the legacy data (e.g. in plain JSON/XML) and doing the import on your new codebase via custom CLI commands (or the REST API if you want to make sure your legacy data would be compliant as if it was submitted with the new API). See e.g. https://github.com/zenodo/zenodo-migrator (which is a fork of invenio-migrator). 

If you're designing a new schema you probably want to clean up your data and start from a "fresh" POV. You can take inspiration from what we did on Zenodo, but this is work that was done more than two years ago in a "fire-and-forget" fashion (that the developers that contributed the bulk of the migration code are not part of the team anymore). Migrations (or fresh imports) are unfortunately a hard problem, providing a catch-all solution from Invenio wouldn't be an easy task...

**Comment by fmarco76** [comment]
My idea was to use the CLI but I had the same error I got loading the demo record, they are loaded with zenodo-migrator but this library make use of invenio-migrator to perform some tasks.

Thanks for the hints, I will see which works better in our case.
