### ISSUE TITLE
openaire: change urls from zenodo to openaire

### ISSUE THREAD

**Issue by ChiaraBi** [zenodo/zenodo#1639]
The search functionalities of OpenAIRE is now under the explore.openaire.eu portal. Thus, we should change the URLs from zenodo to openaire.

For example, on this page https://zenodo.org/record/1433636#.W-vuiBCxU5l 
the url https://www.openaire.eu/search/publication?articleId=od______2659::c10e01f530f07204168096a6c2a9b579 
should be 
https://explore.openaire.eu/search/publication?articleId=od______2659::c10e01f530f07204168096a6c2a9b579

Also, links to other result types of openaire should be: 
https://explore.openaire.eu/search/dataset?datasetId= 
https://explore.openaire.eu/search/software?softwareId= 
https://explore.openaire.eu/search/other?orpId=

**Comment by lnielsen** [comment]
What is the status of this one?
