### ISSUE TITLE
newspaper clips: what upload type

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1648]
https://doi.org/10.5281/zenodo.1682067
this is an op/ed I got published in todays Neue Zürcher Zeitung as a contribution in the current revision of Swiss Copyright Law (Urheberrechtsrevision). It is relevant to our work in the Biodiversity Literature Repository Community and thus I want to add it to document this side of its development too.

The question is what is the right upload type and if publication is chosen, the fight publication type? It is not obvious for me

**Comment by lnielsen** [comment]
Its' correct - publication > other
