### ISSUE TITLE
Bibtex differs (Zenodo export vs. DOI request)

### ISSUE THREAD

**Issue by mrustl** [zenodo/zenodo#1658]
Using the **Export Bibtex** on Zenodo for https://zenodo.org/record/1244103/export does include a value for **month**:

`@misc{michael_rustler_2018_1244103,`
`  author       = {Michael Rustler},`
`  title        = {aquanes.report (v0.5.0)},`
`  month        = may,`
`  year         = 2018,`
`  doi          = {10.5281/zenodo.1244103},`
`  url          = {https://doi.org/10.5281/zenodo.1244103}`
`}`

Whilst accessing it using the DOI (e.g. via https://www.doi2bib.org/bib/10.5281%2Fzenodo.1244103) does not return the **month**. 

`@misc{https://doi.org/10.5281/zenodo.1244103,`
 ` doi = {10.5281/zenodo.1244103},`
`  author = {Rustler,  Michael},`
`  keywords = {R package},`
`  title = {Aquanes.Report (V0.5.0)},`
`  publisher = {Zenodo},`
`  year = {2018}`
`}`

Is this a bug?

**Comment by mrustl** [comment]
Calling the DOI "https://doi.org/10.5281/zenodo.1244103" redirects the request to 

Response [https://data.datacite.org/10.5281%2Fzenodo.1244103]
  Date: 2018-12-10 15:14
  Status: 200
  Content-Type: application/x-bibtex
  Size: 216 B

The content of the answer again does not contain the **month** 

`@misc{https://doi.org/10.5281/zenodo.1244103,`
`doi = {10.5281/zenodo.1244103},`
`author = {Rustler, Michael},`
`keywords = {R package},`
`title = {Aquanes.Report (V0.5.0)},`
`publisher = {Zenodo},`
`year = {2018}`
`}`

**Comment by lnielsen** [comment]
We're not responsible for BibTeX serialization on doi.org - that's managed by DataCite.

If you want it from Zenodo you can do this:

```console
$ curl -H "Accept: application/x-bibtex" https://zenodo.org/api/records/1244103
@misc{michael_rustler_2018_1244103,
  author       = {Michael Rustler},
  title        = {aquanes.report (v0.5.0)},
  month        = may,
  year         = 2018,
  doi          = {10.5281/zenodo.1244103},
  url          = {https://doi.org/10.5281/zenodo.1244103}
```
