### ISSUE TITLE
Public not see the last version, we need new version as default PDF

### ISSUE THREAD

**Issue by ppKrauss** [zenodo/zenodo#1670]
I need to  change the page `https://zenodo.org/record/{MyID}` configuration to show last PDF version as default. Is only a page-interface problem, we can stay with same DOI.

Even changing  `https://zenodo.org/record/{MyFirstID}`   by   `https://zenodo.org/record/{MyLastID}`  the page shows preview of the PDF of `MyFirstID`: this problem with URL **seems a bug**. 

Is difficult for normal (and hurried) people see that there are a "videogame click-here" to change PDF preview, the correct is to show last version  as default... And is not correct to lost internet bandwidth for out of date at  default visualization. 

<br>NOTE: my documents  are *v0.X.Y*  draft versions... Only the *v1.X.Y* versions eventually (ideal is author's configurable decision) needs to show *v1.0.0* PDF as default preview, as publication-date reference or DOI reference. 

-----

PS1: I was submmited this issue at [zenodo.org/support](https://zenodo.org/support) but try-and-error, Internal server errors 274ba63994894d57b50b5739b23f5bd1 and  d31a4e1493de4dfca7080bfa22c8ab2f.

PS2: we can workaround, but the cost will be a lot of pollution in the DOI namespace.

**Comment by slint** [comment]
@ppKrauss I'm not entirely sure what is the issue. In any case, a better place for discussion would be our support email <info@zenodo.org> (the support form had a bug with vaildating email addresses, but is now fixed, so feel free to use it if you like).
