### ISSUE TITLE
Zenodo: BLR: multiple versions of the same article

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#168]
@lnielsen how do we deal with multiple copies of the same articles: an html, pdf, XML? How do we unite them all under one DOI, or assign each one a new DOI and link them? What about versions?

**Comment by lnielsen** [comment]
It would be highly preferable that it's only one DOI with multiple files. First file will be the one loaded in the preview.

New versions should however get a new DOI (see #34).

**Comment by myrmoteras** [comment]
how can we add multiple files to one doi in Zenodo?

**Comment by lnielsen** [comment]
Just send multiple calls to https://zenodo.org/api/deposit/depositions/:id/files (see https://zenodo.org/dev#restapi-res-files)
