### ISSUE TITLE
Zenodo: BLR: how to cite articles in Zenodo which do NOT have a Zenodo DOI

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#170]
How can we cite an article that is in Zenodo that has not local DOI but one from the publisher? See eg https://zenodo.org/record/15482#.VObyOS6rHLc . When you search on http://refindit.org  for its title " A revision of the New World species of Cremnops Förster (Hymenoptera: Braconidae: Agathidinae)" then you get only the treatments and the figure that we extracted from it and that have DOI,  (ie http://dx.doi.org/10.5281/zenodo.15479 and http://dx.doi.org/10.5281/zenodo.15479 ) but not the article proper.

Right now, the only way to link to the article is by this https://zenodo.org/deposit/23022/

**Comment by lnielsen** [comment]
In Zenodo you correctly have isPartOf 10.11646/zootaxa.3916.1.1 which is exposed in DataCite metadata (see http://data.datacite.org/10.5281/zenodo.15479). 

When I search refindit.org with the DOI "10.11646/zootaxa.3916.1.1" it does find the article: "A revision of the New World species of Cremnops Förster (Hymenoptera: Braconidae: Agathidinae)"  but of course not the version in Zenodo but the original on from Zootaxa. 


1) Refindit could harvest Zenodo via OAI-PMH, and they would be able to see that we have the DOI on record as well, and they would then just have two links to display. 

2) After looking a bit on refindit code, it looks like refindit could just search our upcoming record REST API, and would be able to find it that way.
