### ISSUE TITLE
Weird filename normalization

### ISSUE THREAD

**Issue by soshial** [zenodo/zenodo#1707]
When I uploaded a file "Культура латышской речи.pdf", it transformed one symbol "й" → into two symbols "и" +  &#772; (macron).

Same with any diacritics:
фуй_ёж_dūmķä.pdf → фуй_ёж_dūmķä.pdf 

<img width="613" alt="screen shot 2019-02-20 at 07 42 12" src="https://user-images.githubusercontent.com/100644/53066966-26854700-34e3-11e9-9d88-102f759ba6d2.png">

**Comment by mittagessen** [comment]
That's an artifact of your default font only having a proper glyph for й in Unicode NFC (one code point for й)  and the filename being normalized to NFD (two code points: и + combining character breve) causing the diacritic to be offset. This is purely a rendering issue and for any software with proper Unicode support they are identical. Have a look at [Unicode equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence).
