### ISSUE TITLE
deposit: Pluploader not working correctly in IE9

### ISSUE THREAD

**Issue by bouzlibop** [zenodo/zenodo#171]
There is a problem with `plupload` runtime (i.e. it's not properly configured - see [this](http://www.plupload.com/docs/Options) for the configuration options), which is causing the problem in `IE9`

**Comment by bouzlibop** [comment]
Gist on `Flask` browser detection -  https://gist.github.com/LeZuse/2578981

**Comment by lnielsen** [comment]
Replaced in sandbox by ng file upload
