### ISSUE TITLE
oairepository: GetRecord does not find record via identifier

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#172]
The record https://zenodo.org/record/6738 has OAI identifier ``oai:zenodo.org:6738`` (see MARCXML).

```
<datafield tag="909" ind1="C" ind2="O">
<subfield code="o">oai:zenodo.org:6738</subfield>
<subfield code="p">openaire</subfield>
<subfield code="p">user-zenodo</subfield>
<subfield code="p">user-cfa</subfield>
</datafield>
```

but is not available via an OAI-PMH ``GetRecord`` query:

https://zenodo.org/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:zenodo.org:6738

**Comment by lnielsen** [comment]
+ related to inveniosoftware/invenio#2962

**Comment by bouzlibop** [comment]
PR is ready [here](https://github.com/inveniosoftware/invenio/pull/2993). It needs a review though.
