### ISSUE TITLE
Errors in web service logs after zenodo first run

### ISSUE THREAD

**Issue by 486dx** [zenodo/zenodo#1724]
Hi, I'm trying to run Zenodo at my local. I executed `docker-compose -f docker-compose.full.yml build` and  `docker-compose -f docker-compose.full.yml up -d` commands. All zenodo service containers are up. But when i looked at web service logs by using `docker-compose -f docker-compose.full.yml logs -f web` command. I got this logs from web service and i couln't access the Zenodo service.

web_1       | KeyError: 'github'
web_1       | [pid: 39|app: 0|req: 20/38] 172.19.0.12 () {36 vars in 396 bytes} [Fri Mar  8 10:46:26 2019] HEAD /ping => generated 0 bytes in 9 msecs (HTTP/1.0 500) 0 headers in 0 bytes (0 switches on core 1)
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
web_1       |     return self.wsgi_app(environ, start_response)
web_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
web_1       |     return self.app(environ, start_response)
web_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 826, in __call__
web_1       |     return app(environ, start_response)
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
web_1       |     response = self.handle_exception(e)
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
web_1       |     reraise(exc_type, exc_value, tb)
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
web_1       |     response = self.full_dispatch_request()
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1607, in full_dispatch_request
web_1       |     self.try_trigger_before_first_request_functions()
web_1       |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
web_1       |     func()
web_1       |   File "/usr/local/lib/python2.7/site-packages/invenio_github/ext.py", line 79, in connect_signals
web_1       |     sender=GitHubAPI.remote._get_current_object()
web_1       |   File "/usr/local/lib/python2.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
web_1       |     return self.__local()
web_1       |   File "/usr/local/lib/python2.7/site-packages/invenio_github/api.py", line 84, in <lambda>
web_1       |     current_app.config['GITHUB_WEBHOOK_RECEIVER_ID']
web_1       | KeyError: 'github'

**Comment by lnielsen** [comment]
It means your configuration is broken. Check ``GITHUB_WEBHOOK_RECEIVER_ID``...it's expecting a ``github`` key.
