### ISSUE TITLE
Zenodo not depositing additional 'assets' from github release

### ISSUE THREAD

**Issue by duetosymmetry** [zenodo/zenodo#1728]
Github allows to add extra files, besides a tarball of the repo, to a release: see e.g. [this release](https://github.com/duetosymmetry/qnm/releases/tag/v0.2.3) which, under 'Assets', has a `data.tar.bz2` file, along with the Source code zip and tar.gz. With Zenodo integration turned on, creating the release triggers archiving of the Source code files, but **not** the extra assets (`data.tar.bz2` in this case).

**Comment by mriesch-tum** [comment]
I think that this issue has already been mentioned in #1235. Anyway, it would be a very nice feature!

**Comment by duetosymmetry** [comment]
Thanks, @mriesch-tum, for finding the relevant issue that has already been opened. I was unable to find it. Closing since already filed.
