### ISSUE TITLE
records: link to a specific export format

### ISSUE THREAD

**Issue by ChiaraBi** [zenodo/zenodo#1734]
Users would like to be able to share the link to a specific export format. To do so, we should add some [configurations](https://github.com/inveniosoftware/invenio-rest/commit/96cf02cf196fa2b17258d415124ec65771e34f66) to  let response content to be serialized according to the mime type (see [invenio-records-rest](https://github.com/inveniosoftware/invenio-records-rest/commit/6394643fbc5ded020d79764966dfdf1543516022#diff-23735a24d0f4818f9e71609ff7fbeba2)).

**Comment by lnielsen** [comment]
Isn't this already possible via e.g. https://zenodo.org/record/2579947/export/dcite4 ?

**Comment by slint** [comment]
To get it through the REST API though and have the response body be the final serialization, you cannot integrate the `Accept` header in a single link. The idea would be to be able to do something like:

```bash
$ curl https://zenodo.org/api/records/12345?format=dcite4

<?xml version='1.0' encoding='utf-8'?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
  <identifier identifierType="DOI">10.5281/zenodo.2579947</identifier>
  <creators>
    <creator>
      <creatorName>Jaakkonen</creatorName>
...
```
