### ISSUE TITLE
records: DCAT serialisation

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#1753]
Full documentation of the defined DataCite to DCAT-AP mappings:
 
https://ec-jrc.github.io/datacite-to-dcat-ap/
 
XSLT implementation:
 
https://github.com/ec-jrc/datacite-to-dcat-ap
 
The corresponding API – which can be used on top of an OAI-PMH endpoint:
 
https://github.com/ec-jrc/datacite-to-dcat-ap/tree/master/api

**Comment by Glignos** [comment]
Using the xslt tranformation we are getting the following result from [this record](https://zenodo.org/oai2d?verb=GetRecord&&metadataPrefix=oai_datacite&identifier=oai:zenodo.org:1039713)

`<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:adms="http://www.w3.org/ns/adms#" xmlns:cnt="http://www.w3.org/2011/content#" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcat="http://www.w3.org/ns/dcat#" xmlns:dct="http://purl.org/dc/terms/" xmlns:dctype="http://purl.org/dc/dcmitype/" xmlns:duv="http://www.w3.org/ns/duv#" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:frapo="http://purl.org/cerif/frapo/" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:gsp="http://www.opengis.net/ont/geosparql#" xmlns:locn="http://www.w3.org/ns/locn#" xmlns:org="http://www.w3.org/ns/org#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:prov="http://www.w3.org/ns/prov#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:schema="http://schema.org/" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:vcard="http://www.w3.org/2006/vcard/ns#" xmlns:wdrs="http://www.w3.org/2007/05/powder-s#">
   <rdf:Description rdf:about="https://doi.org/10.5281/zenodo.1039713">
      <rdf:type rdf:resource="http://www.w3.org/ns/dcat#Dataset" />
      <dct:type rdf:resource="http://purl.org/dc/dcmitype/Text" />
      <dct:identifier rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://doi.org/10.5281/zenodo.1039713</dct:identifier>
      <foaf:page rdf:resource="https://doi.org/10.5281/zenodo.1039713" />
      <dct:creator>
         <rdf:Description>
            <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Agent" />
            <foaf:name>Gall, Ruth</foaf:name>
            <foaf:givenName>Ruth</foaf:givenName>
            <foaf:familyName>Gall</foaf:familyName>
            <org:memberOf>
               <foaf:Organization>
                  <foaf:name>(Autor/in)</foaf:name>
               </foaf:Organization>
            </org:memberOf>
         </rdf:Description>
      </dct:creator>
      <dct:creator>
         <rdf:Description>
            <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Agent" />
            <foaf:name>Glauser, Daniela</foaf:name>
            <foaf:givenName>Daniela</foaf:givenName>
            <foaf:familyName>Glauser</foaf:familyName>
            <org:memberOf>
               <foaf:Organization>
                  <foaf:name>(Autor/in)</foaf:name>
               </foaf:Organization>
            </org:memberOf>
         </rdf:Description>
      </dct:creator>
      <dct:title>Scheiden tut weh... ...und s´Läbe fägt doch! Eine qualitative Untersuchung wie Jugendliche die Scheidung der Eltern verarbeiten</dct:title>
      <dct:publisher>
         <foaf:Agent>
            <foaf:name>Zenodo</foaf:name>
         </foaf:Agent>
      </dct:publisher>
      <dct:issued rdf:datatype="http://www.w3.org/2001/XMLSchema#gYear">2010</dct:issued>
      <dct:subject>
         <skos:Concept>
            <skos:prefLabel xml:lang="">gnd:4347842-6</skos:prefLabel>
            <skos:inScheme>
               <skos:ConceptScheme>
                  <dct:title xml:lang="">gnd</dct:title>
               </skos:ConceptScheme>
            </skos:inScheme>
         </skos:Concept>
      </dct:subject>
      <dct:subject>
         <skos:Concept>
            <skos:prefLabel xml:lang="">gnd:4013656-5</skos:prefLabel>
            <skos:inScheme>
               <skos:ConceptScheme>
                  <dct:title xml:lang="">gnd</dct:title>
               </skos:ConceptScheme>
            </skos:inScheme>
         </skos:Concept>
      </dct:subject>
      <dct:subject>
         <skos:Concept>
            <skos:prefLabel xml:lang="">gnd:4055676-1</skos:prefLabel>
            <skos:inScheme>
               <skos:ConceptScheme>
                  <dct:title xml:lang="">gnd</dct:title>
               </skos:ConceptScheme>
            </skos:inScheme>
         </skos:Concept>
      </dct:subject>
      <dct:issued rdf:datatype="http://www.w3.org/2001/XMLSchema#date">2010-08-15</dct:issued>
      <owl:sameAs rdf:resource="https://zenodo.org/record/1039713" />
      <adms:identifier>
         <adms:Identifier>
            <skos:notation rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">https://zenodo.org/record/1039713</skos:notation>
         </adms:Identifier>
      </adms:identifier>
      <dct:isPartOf rdf:resource="https://doi.org/10.5281/zenodo.1039712" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lara" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lara_sa" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lara_sa_hslu_sa" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lory" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lory_hslu" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lory_hslu_sa" />
      <dct:isPartOf rdf:resource="https://zenodo.org/communities/lory_hslu_sa_sa" />
      <dct:description>&lt;p&gt;Ist es möglich, dass Jugendliche zwischen 12 und 18 Jahren die Scheidung ihrer Eltern ohne oder mit nur wenigen Beeinträchtigungen verarbeiten können? Die Zeit der Pubertät und Adoleszenz ist für sie mit vielen Entwicklungsschritten und Herausforderungen verbunden. Dabei stellt die Scheidung der Eltern einen zusätzlichen Belastungsfaktor dar. Ergebnisse aus 15 Interviews mit Expertinnen und Experten sowie einer Gruppendiskussion, an welcher ehemals betroffene Jugendliche teilgenommen haben, wurden in dieser Forschungsarbeit zusammen getragen. Verschiedene Perspektiven zeigen auf, welchen Herausforderungen sich Jugendliche aus Scheidungsfamilien stellen müssen und veranschaulichen unterschiedliche Bewältigungsfaktoren. Dabei werden übereinstimmende oder divergierende Wahrnehmungen und Sichtweisen deutlich. Das Aufzeigen von Entwicklungsaufgaben, eine Entwicklungstheorie, vier Erziehungsstile, ein Resilienzkonzept sowie weiterführende Gedanken der Autorinnen erläutern die Forschungsergebnisse. Weiter definieren rechtliche Aspekte die unterschiedlichen Vorgehensweisen sowie die Rechte der Kinder bei einer Scheidung. Zusätzlich verdeutlichen statistische Fakten die Anzahl betroffener Ehepaare und unmündiger Kinder. Anschliessend werden die erworbenen Erkenntnisse mit der Sozialen Arbeit in Zusammenhang gebracht und vorhandene und visionäre Unterstützungsangebote aufgezeigt. Die Empfehlungen an die Soziale Arbeit zeigen weitere situationsspezifische Unterstützungsmöglichkeiten für Jugendliche und Eltern auf, die ein Scheidungsereignis verarbeiten müssen.&lt;/p&gt;</dct:description>
      <dct:description xml:lang="">+ Code Diss LU: hslusa basa 2010 be + Fussnote: Bachelor-Arbeit, Hochschule Luzern - Soziale Arbeit, Ausbildungsgang Sozialarbeit 2010</dct:description>
      <dct:accessRights rdf:resource="http://publications.europa.eu/resource/authority/access-right/PUBLIC" />
      <dct:accessRights>
         <dct:RightsStatement rdf:about="info:eu-repo/semantics/openAccess">
            <rdfs:label>Open Access</rdfs:label>
         </dct:RightsStatement>
      </dct:accessRights>
      <dcat:distribution>
         <dcat:Distribution>
            <dct:license rdf:resource="http://creativecommons.org/licenses/by-nc-nd/4.0/legalcode" />
            <dcat:accessURL rdf:resource="https://doi.org/10.5281/zenodo.1039713" />
         </dcat:Distribution>
      </dcat:distribution>
   </rdf:Description>
</rdf:RDF>`

**Comment by Glignos** [comment]
Implemented here https://github.com/zenodo/zenodo/commit/bc32d6b78679e6b4c7aa9d3b013f493445d9f9d1
