### ISSUE TITLE
Contact form: when there is not name, one cannot submit

### ISSUE THREAD

**Issue by jbenito3** [zenodo/zenodo#1759]
In the [contact form](https://zenodo.org/support), when the user has no name defined...the user cannot submit the request (because, of course, the field is disabled and they cannot edit it).

@slint @lnielsen, what would be a nice solution? filling the name field with something like 'no name' or 'undefined'? or maybe better...showing an easy-to-understand error with a link to the user profile, so the fill the name. What do you say?

**Comment by Glignos** [comment]
Solved in https://github.com/zenodo/zenodo/commit/3f9259dfdfcfc0893b3eaa8d1a82d12cd9c3d0f0
