### ISSUE TITLE
Is there a file Size limit for uploading with REST API?

### ISSUE THREAD

**Issue by wkpalan** [zenodo/zenodo#1764]
I am trying to upload a large file 1-2GB into Zendo sandbox. I keep getting a EPIPE error when I submit my request.

    data = {"filename":'test.tar'}
    files ={'file' : ("test.tar",open('test.tar','rb'),{'Expires': '0'})}

    r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions/274851/files',
                  params={'access_token': ACCESS_TOKEN},files=files,data=data)

The error I get is as follows

    ConnectionError: ('Connection aborted.', error("(32, 'EPIPE')",))

Is this due to a size limit imposed on the uploads?

**Comment by frankois** [comment]
Indeed there is a size limit old API, which supports up to 100MB per file. The new API supports up to 50GB per file and you can see how to use it at the following links:
- using curl: https://gist.github.com/slint/2263b2212743a68b2851b2cb7865675e
- using Python: https://gist.github.com/slint/92e4d38eb49dd177f46b02e1fe9761e1

This API is not completely stable, so it might change a bit in the future. As soon as we will develop a stable version, we will update the documentation here: http://developers.zenodo.org/#deposition-files

Let me know should you need further help.

**Comment by wkpalan** [comment]
Thank you for the reply @frankois. I will check the new API out.

**Comment by abubelinha** [comment]
I am a bit lost when I read about the new and old APIs. I cant find them.
Please @frankois could you provide the url to the documentation of each one?

Thanks a lot

**Comment by johanneskoester** [comment]
> 

Dear @frankois. Any update on stabilizing the API for bigger file sizes? Since your post is quite old, has this effort been abandoned?

**Comment by ppanero** [comment]
Hi @johanneskoester, some changes have been made since then to improve the files submission (e.g. offloading, instead of passing the files through the python app). Does the issue still persists?

**Comment by johanneskoester** [comment]
I actually haven't checked, I was just referring to the blue note here at the top:
https://developers.zenodo.org/#delete

It says that there is still a 100MB limit.
