### ISSUE TITLE
global: update pdf.js to latest version

### ISSUE THREAD

**Issue by ChiaraBi** [zenodo/zenodo#1788]
The preview of the following record does not render correctly: https://doi.org/10.5281/zenodo.3019412.
(Compare the four horizontal colored bands on the PDF to how they render, as well as the lightbulb in the center of the poster).

Updating `pdf.js` to the latest version should solve the problem.

**Comment by ctrl-alt-soneca** [comment]
Another example for this issue: 10.5281/zenodo.4775371 . When using Firefox as browser figures are displayed in blue or with a blue frame in the preview of the pdf.

**Comment by alejandromumo** [comment]
Another example related with the pdf previewer: https://zenodo.org/record/6505044

When rendered on a mobile device, the Table of Contents generated by LateX, which contains references, are not properly displayed. Red squares are shown on the side.

**Comment by cenouralm** [comment]
We should investigate it...
How can we tackle the issues with the previewer? We should discuss it...
