### ISSUE TITLE
New Github release removes community from Zenodo upload 

### ISSUE THREAD

**Issue by jdeplaa** [zenodo/zenodo#1795]
Dear developers,

I have experienced an issue with creating automatic Zenodo uploads using a Github release. When the release is a new version of a record that was uploaded to Zenodo before, then the communities that the previous Zenodo record was linked to are removed.

For example, a package of my colleague [dokester/BayesicFitting](https://zenodo.org/record/2597201) was linked to the [SRON community](https://zenodo.org/communities/sron/) after the first upload, but since their update to version 2.3.0, the record is no longer part of the SRON community.

I experienced the same with my own package [spex-xray/pyspextools](https://doi.org/10.5281/zenodo.3245804), where I had to add the SRON community to the upload manually again after the second Github release of the package. The Github release appeared to have deleted the community memberships of the associated Zenodo record.

Could this be fixed?

Thanks a lot, Jelle.

**Comment by Glignos** [comment]
Thank you for reporting this.
We have confirmed the issue and have now a PR addressing it.
After deploying and testing the solution we will close this GitHub issue.

**Comment by slint** [comment]
Closed via #1795
