### ISSUE TITLE
Regression in preview of JSON files

### ISSUE THREAD

**Issue by moble** [zenodo/zenodo#1804]
Until recently, most of my records automatically showed a preview of certain JSON files (which I actually designed to show the most relevant information in the zenodo preview window).  I believe it was usually the first JSON file in the file list.  In addition, it was possible to click the "Preview" icon in the file list, to actively select a file to preview.  But neither of those seem to work any longer; now all I see in the preview box is this message: 

> **Cannot preview file**
> 
> Sorry, we are unfortunately not able to preview this file.

See, for example, the metadata.json file in [this record](https://zenodo.org/record/2638445).  These JSON files were what our collaboration used to describe the record on the zenodo page (though mostly as a matter of convenience, because we have those files anyway), so if they're not displayed, all our records look very uninformative.

**Comment by slint** [comment]
The JSON previewer has been temporarily disabled because of an XSS security vulnerability. It will be enabled again once the underlying library has been patched and tested on Zenodo

**Comment by lnielsen** [comment]
For details please see:
- [Zenodo blog post](http://blog.zenodo.org/2019/07/15/2019-07-15-xss-vulnerability/)
- [Invenio blog post](https://inveniosoftware.org/blog/security-advisor-20190715/)
- [Invenio-Previewer security advisory](https://github.com/inveniosoftware/invenio-previewer/security/advisories/GHSA-j9m2-6hq2-4r3c)

The JSON previewer will be enabled again with a new deployment.

**Comment by moble** [comment]
OK.  Thanks for the explanation, and all the good work!
