### ISSUE TITLE
DOI registration fails when empty affiliation

### ISSUE THREAD

**Issue by jbenito3** [zenodo/zenodo#1809]
Somehow someone managed to get something like this in the db:

```
u'creators': [{u'affiliation': u'FOO University',
   u'name': u'Jose Glez'},
  {u'affiliation': u'',
   u'name': u'Pepe Lpz'},
```

My guess is that the person wrote some affiliation and then deleted it. But the key remained in the dictionary...but...that's just a guess :)

Anyway, DOI registration fails in datacite when you send somethign like `<affiliation/>` (which happens when you have somethign like the dict above.

**Comment by Glignos** [comment]
This cannot be reproduced through the API as correctly the field is cleaned up in the [post_dump](https://github.com/zenodo/zenodo/blob/7a52ff3af10369fd052840666c0a5e263c8b9899/zenodo/modules/records/serializers/schemas/common.py#L154) but it can be reproduced through the form if you clear the previously filled field.
