### ISSUE TITLE
error message: what does it mean?

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1810]
IN this case  https://zenodo.org/record/966100#.XTGGQugzbAQ

there is an error message displayed. What does it mean? It might have something to do with the references. @gsautter?

![image](https://user-images.githubusercontent.com/4609956/61523344-788bb380-aa14-11e9-9782-a43b7e46cde8.png)

![image](https://user-images.githubusercontent.com/4609956/61536012-f01d0b00-aa33-11e9-95c9-40b889ea16b6.png)

![image](https://user-images.githubusercontent.com/4609956/61536059-088d2580-aa34-11e9-930e-2ff859360aa4.png)

**Comment by lnielsen** [comment]
Probably because they switched the citation microservice to a new production system.
