### ISSUE TITLE
Can't find main Creative Commons licenses in license selector

### ISSUE THREAD

**Issue by nemobis** [zenodo/zenodo#1813]
The license selector fails to suggest any relevant license: if I type "Creative Commons" it only shows the whole set of NC options plus CC-BY 1.0 and 2.0; if I type "Zero" it doesn't find anything at all.

Possibly related to https://github.com/zenodo/zenodo/commit/7a52ff3af10369fd052840666c0a5e263c8b9899 ?

![ZenodoLicense](https://user-images.githubusercontent.com/901528/62165448-28bbbf00-b327-11e9-943c-c0b53828e0f8.png)

**Comment by lnielsen** [comment]
Typing ``CC0`` should do the job. We are aware the license selection is not that user friendly.

**Comment by nemobis** [comment]
Lars Holm Nielsen, 31/07/19 09:16:
> Typing |CC0| should do the job. 

Confirmed, thanks. I had tried "CC", "CC-0", "Zero" and others without 
success. I never had problems finding the CC-0 in the selector before.

> We are aware the license selection is 
> not that user friendly.

Maybe you could try using a simple dropdown. At least it would allow 
alphabetical browsing and autocompletion by whatever default the user's 
browser uses, and it would not unintentionally discriminate against free 
Creative Commons licenses at seems to be happening here for those who 
type "Creative Commons" (but not those who type "CC", curiously).

**Comment by slint** [comment]
We have made some small improvements on the search behavior of the dropdown (e.g. there's some "fuzzy" matching which will help with typos and small variations in the names).

Otherwise, it wouldn't be feasible to have a big dropdown since we have ~300 licenses, which although complete, wouldn't be that easy to scroll/filter through.
