### ISSUE TITLE
Organization's repositories do not show up in the list

### ISSUE THREAD

**Issue by ShixiangWang** [zenodo/zenodo#1814]
Dear developer,

I cannot find the repositories of my new organization.

I tried syncing the account

![image](https://user-images.githubusercontent.com/25057508/62269709-75f27a80-b466-11e9-90e4-ec885ff56403.png)

I also followed the instruction below to check if can access it.

![image](https://user-images.githubusercontent.com/25057508/62269735-8c003b00-b466-11e9-8118-d46c84ef1cd9.png)

And found that only the repositories of ropensic don't show up.

![image](https://user-images.githubusercontent.com/25057508/62269777-b2be7180-b466-11e9-8b2f-bf25e2d4ce27.png)

What's the problem?

Best,
Shixiang

**Comment by ShixiangWang** [comment]
The problem came from GitHub setting, sorry for reporting this.

**Comment by ltalirz** [comment]
Just to be clear, the only way I got this to work was to completely remove any access restrictions for third-party applications:
![Screenshot 2020-02-14 at 14 51 29](https://user-images.githubusercontent.com/1053245/74537024-8cab7b00-4f39-11ea-9bd7-b6308a0fe0dc.png)

I don't think this a good policy in general, and I think this is not what the zenodo developers had in mind when they wrote this:
![Screenshot 2020-02-14 at 14 53 34](https://user-images.githubusercontent.com/1053245/74537143-ced4bc80-4f39-11ea-9539-8badd75b19a2.png)

However, what is missing to me in the tutorial above is: how do I trigger the zenodo application to *request access*?

**Comment by lauraxijia** [comment]
Sorry, @ShixiangWang what did you change to resolve this?

**Comment by ShixiangWang** [comment]
@lauraxijia Sorry, I have forgotten. You should give the zenodo permissions from Github.

**Comment by lauraxijia** [comment]
@ShixiangWang  we (Organization owner) did grant ‘third-party access’ to Zenodo from the organization account, but still no repo from the organization account is showing up in my Zenodo’s list. And all repo are public repos.
Could it be the case that only organization owner can register repo and apply for a DOI in their Zenodo, but not contributors?

**Comment by alimanfoo** [comment]
Just hit this, previously authorized zenodo for github access under my github user account, but later created a github organisation, and none of the oganisation's github repos appear in zenodo. Here's how I solved it...

1. Go to the settings page for my personal github account - https://github.com/settings/applications - Zenodo should be listed there under the "Authorized OAuth Apps" tab.
2. Click Zenodo, scroll down to "Organization access" and grant access to the organization you want.
3. Go to Zenodo's Github settings - https://zenodo.org/account/settings/github/ - scroll down to "GitHub repositories" section, click "sync now", refresh the web page, then your repository should appear.
4. Flip the switch off to on

A webhook should now have been installed. You can check by going to the setting page for the specific github repo you want to archive, then look under the webhooks section.

Hth.

**Comment by lauraxijia** [comment]
Thanks so much for sharing!

I was able to fix the problem- the issue for me was that I wasn’t the
organization owner so I asked the owner to try and it got solved.

Thank you, again!

Alistair Miles <notifications@github.com>于2020年4月28日 周二上午4:46写道：

**Comment by jameshowison** [comment]
I had the same confusions, fwiw.  I was the repository owner, a colleague was a member of the github organization and an admin on the organizational repository we wished to archive with Zenodo.  The colleague logged into Zenodo using their Github account but didn't see the organizational repositories.  We then had much confusion. As organization owner I went to the third party access but couldn't see a "request" that I could approve.  We then wondered if my colleague had to be an organization owner, which seemed a bit heavyweight for just this.  Eventually we figured out that my colleague had to create a request for 3rd party access, by going to Github, looking at their 3rd party permissions, clicking on the Zenodo name, then "send request to owners".  This was the key github documentation:

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/requesting-organization-approval-for-oauth-apps

I was then able to approve that request (as org owner) at Github (after some confusion about why Zenodo needed access to "private data", I figure it's something about webhooks) and my colleague then hit the "Sync now" and was able to see the organizational repository.

Phew :)

**Comment by abhinava** [comment]
> Just hit this, previously authorized zenodo for github access under my github user account, but later created a github organisation, and none of the oganisation's github repos appear in zenodo. Here's how I solved it...
> 
> 1. Go to the settings page for my personal github account - https://github.com/settings/applications - Zenodo should be listed there under the "Authorized OAuth Apps" tab.
> 2. Click Zenodo, scroll down to "Organization access" and grant access to the organization you want.
> 3. Go to Zenodo's Github settings - https://zenodo.org/account/settings/github/ - scroll down to "GitHub repositories" section, click "sync now", refresh the web page, then your repository should appear.
> 4. Flip the switch off to on
> 
> A webhook should now have been installed. You can check by going to the setting page for the specific github repo you want to archive, then look under the webhooks section.
> 
> Hth.

Thanks so much! This worked!

**Comment by Ki-Seki** [comment]
> Just hit this, previously authorized zenodo for github access under my github user account, but later created a github organisation, and none of the oganisation's github repos appear in zenodo. Here's how I solved it...
> 
> 1. Go to the settings page for my personal github account - https://github.com/settings/applications - Zenodo should be listed there under the "Authorized OAuth Apps" tab.
> 2. Click Zenodo, scroll down to "Organization access" and grant access to the organization you want.
> 3. Go to Zenodo's Github settings - https://zenodo.org/account/settings/github/ - scroll down to "GitHub repositories" section, click "sync now", refresh the web page, then your repository should appear.
> 4. Flip the switch off to on
> 
> A webhook should now have been installed. You can check by going to the setting page for the specific github repo you want to archive, then look under the webhooks section.
> 
> Hth.

Really helpful! Thx!!!❤

**Comment by lm687** [comment]
> Just hit this, previously authorized zenodo for github access under my github user account, but later created a github organisation, and none of the oganisation's github repos appear in zenodo. Here's how I solved it...
> 
>     1. Go to the settings page for my personal github account - https://github.com/settings/applications - Zenodo should be listed there under the "Authorized OAuth Apps" tab.
> 
>     2. Click Zenodo, scroll down to "Organization access" and grant access to the organization you want.
> 
>     3. Go to Zenodo's Github settings - https://zenodo.org/account/settings/github/ - scroll down to "GitHub repositories" section, click "sync now", refresh the web page, then your repository should appear.
> 
>     4. Flip the switch off to on
> 
> 
> A webhook should now have been installed. You can check by going to the setting page for the specific github repo you want to archive, then look under the webhooks section.
> 
> Hth.

this did not work for me, although all the above seems fine. Is it because I am only a collaborator of the repo, instead of an admin?
