### ISSUE TITLE
REST API Create Deposit: Respose is Empty and Response Code 200

### ISSUE THREAD

**Issue by Kallo1994** [zenodo/zenodo#1816]
Hi,

I followed the Rest-Api to set up a deposition.
For this I use Postman to make the request. 

Url: http://sandbox.zenodo.org/api/deposit/depositions?access_token=MyAccesToken

Header: "Content-Type", "application/json"

Body: {} or 
{"metadata": {
        "title": "My first upload",
        "upload_type": "poster",
        "description": "This is my first upload",
        "creators": [
            {"name": "Doe, John", "affiliation": "Zenodo"}
        ]
    }} 

As a response I always received an empty Json "[]" and the response code "200". Both are not included in the documentation. Actually the code should be at "201".

What error did I make with the request or is the documentation incomplete?
I hope you can help me.

**Comment by lnielsen** [comment]
Are you making a POST request an not a GET request? Can I please ask you to submit your question via https://zenodo.org/support - we prefer to keep GitHub for development and not user support.
