### ISSUE TITLE
api: file upload fails with internal server error (sandbox)

### ISSUE THREAD

**Issue by sk1p** [zenodo/zenodo#1833]
When trying to upload a file to a deposition, the API [responds with](https://travis-ci.org/LiberTEM/LiberTEM/jobs/580197801#L259):

```
{'error_id': '48cb3c9ffb7c46a79cf1440a6dcfbc85',
 'message': 'Internal Server Error',
 'status': 500}
```

This may be a temporary error, as the same script used to work before.

Should a consumer of the API retry in case of status 500?

**Comment by sk1p** [comment]
Restarting the travis job leads to the same error; same when manually running the script.

**Comment by uellue** [comment]
This is the deposition: https://sandbox.zenodo.org/deposit/366444

Parent ID: 264899

When repeating the upload with our offline version of the script, the error occurs when uploading the tarball.

**Comment by Glignos** [comment]
Closing since it seems to be resolved.
