### ISSUE TITLE
GitHub: internal server error

### ISSUE THREAD

**Issue by casperdcl** [zenodo/zenodo#1867]
- tried accessing https://zenodo.org/account/settings/github/ to add more repos but now getting "Internal server error"
- tried disconnecting GitHub under https://zenodo.org/account/settings/linkedaccounts/ but attempting to re-connect still results in "Internal server error"
- if I sign out of GitHub as well, and sign out of zenodo, then sign into zenodo, then try to link github, it prompts for GitHub user/password, then 2FA verification, then back to zenodo "Internal server error"

See e.g. Error identifier: 8ff364fb93314a8d9d66041711fe47a1

Is 2FA not supported?

**Comment by casperdcl** [comment]
seems to be magically fixed now; hope it doesn't happen again

**Comment by slint** [comment]
FYI, the error was caused because of GitHub rate-limiting requests for your user

**Comment by casperdcl** [comment]
Ah nice. Would be nice if the Zenodo error page said "GitHub: rate limit exceeded" rather than "Internal server error"
