### ISSUE TITLE
Use Commend Line to download the file from Zenode

### ISSUE THREAD

**Issue by minygd** [zenodo/zenodo#1888]
Sorry to bother you, but I have faced with a problem for a long time. It's not stable for me to download the large dataset from **Zenode** using browser, however. So use 'wget' comes to my mind, but when I follow the approach provided in [Issues]( https://github.com/zenodo/zenodo/issues/1629), I have failed.

From the former Issue, I use:
```
curl  https://zenodo.org/api/records/3407840

```
I got the REST API: 
> https://zenodo.org/api/files/f0d7eb3a-9575-4297-8a9f-39564e383750/Center%28Left_Down%29.zip.001

But I got **404** just like not using the REST API.
```
wget -r https://zenodo.org/api/files/f0d7eb3a-9575-4297-8a9f-39564e383750/Center%28Left_Down%29.zip.001
```

Could you help me out? Thx!

**Comment by Glignos** [comment]
Since the files of this record are set to restricted access they are not publicly available, to access them you would need an access token to verify your identity, which you can create [here](https://zenodo.org/account/settings/applications/) or you should follow the procedure displayed .

**Comment by Glignos** [comment]
Closing this since it is not an error.

**Comment by balde-soul** [comment]
how to use the privated token? Any idea? Thaks very much

**Comment by thesby** [comment]
I need it too, anyone known ?

**Comment by keunwoochoi** [comment]
i'm curious too

**Comment by teito-dev** [comment]
@thesby @keunwoochoi 

Here are the steps to download the files 
from commandline itself


1- Accquire the personal token (which you probably already have)
2- run the following commands

curl --cookie zenodo-cookies.txt "https://zenodo.org/record/1117372?token=<your token here>"
replace that record number 1117372 with your appropriate one

Once you have generated the cookie file ,
now just get on your browser , right click on the download button and copy its url

it should look something like https://zenodo.org/record/1117372/files/musdb18.zip?download=1

now ,

just run this command on your terminal ,

curl --cookie zenodo-cookies.txt "https://zenodo.org/record/1117372/files/musdb18.zip?download=1" --output musdb18.zip

replace the download link with your particular download url
and it should start downloading ,

and replace the filename on --output musdb18.zip

with the appropriate file name you want

this is the method that works for me ,

Let me know if you face any issues,
Have a great day !

**Comment by xhlulu** [comment]
I was having trouble with the cookies approach, so instead I used the zenodo API approach (in Python).

First, I created a ** Personal access tokens** (NOT  Developer Applications), and assigned it to my variable `ACCESS_TOKEN`. Then I queried all the files available to download in my record:

```python
import requests

ACCESS_TOKEN = "replace this with your access token"
record_id = "replace this with your record"

r = requests.get(f"https://zenodo.org/api/records/{record_id}", params={'access_token': ACCESS_TOKEN})
download_urls = [f['links']['self'] for f in r.json()['files']]
filenames = [f['key'] for f in r.json()['files']]

print(r.status_code)
print(download_urls)
```

Now that I have the urls of the files I want to download as well as their name (i.e. key), I can just download them with `requests.get` and save them to a file:

```python
for filename, url in zip(filenames, download_urls):
    print("Downloading:", filename)
    r = requests.get(url, params={'access_token': ACCESS_TOKEN})
    with open(filename, 'wb') as f:
        f.write(r.content)
```

**Comment by vic4code** [comment]
I tried this and it worked for me:
https://gist.github.com/slint/d47fe5628916d14b8d0b987ac45aeb66#file-zenodo-restricted-curl-sh-L26

**Comment by drscotthawley** [comment]
Neither @teito-dev's nor @Falmi 's instructions are working for me, now 3 years later, for exactly the same dataset (MUSDB18).  
All I download in the end, despite using a new token and cookies file,  is a short file of 255 bytes.

**Comment by vigneshgarrapally** [comment]
> Neither @teito-dev's nor @Falmi 's instructions are working for me, for exactly the same dataset (MUSDB18). All I download in the end, despite using a new token and cookies file, is a short file of 255 bytes.

I have been facing the same. Instead, download cookies from chrome using any cookie downloader extension and use that extension to download the files. List all the files using https://zenodo.org/api/record/<record-id>/files/ and then grab the download links from that response. This worked for me!!

**Comment by yasamanparhizkar** [comment]
This worked for me:
https://stackoverflow.com/questions/21919156/how-do-i-copy-cookies-from-chrome

Basically, just get the full curl command from chrome and paste it to your terminal.

**Comment by zohaib2002** [comment]
@xhluca 

I modified your code to be able to resume downloads. I have not tested it though...

```
import requests
from tqdm import tqdm
import os

ACCESS_TOKEN = "Your Public Access Token"
record_id = "Your record ID"

# Get file metadata
r = requests.get(f"https://zenodo.org/api/records/{record_id}", params={'access_token': ACCESS_TOKEN})
r.raise_for_status()
files = r.json()['files']
download_urls = [f['links']['self'] for f in files]
filenames = [f['key'] for f in files]

# Download each file with resume support
for filename, url in zip(filenames, download_urls):
    temp_file = filename + ".part"
    headers = {'Authorization': f'Bearer {ACCESS_TOKEN}'}

    # Check if partial file exists
    downloaded = 0
    if os.path.exists(temp_file):
        downloaded = os.path.getsize(temp_file)
        headers['Range'] = f'bytes={downloaded}-'

    # Get total file size
    head = requests.head(url, headers=headers)
    total_size = int(head.headers.get('content-length', 0)) + downloaded

    print(f"Resuming download: {filename} ({downloaded}/{total_size} bytes)")

    with requests.get(url, headers=headers, stream=True) as r:
        print("Response code:", r.status_code)
        r.raise_for_status()
        with open(temp_file, 'ab') as f, tqdm(
            desc=filename,
            initial=downloaded,
            total=total_size,
            unit='B',
            unit_scale=True,
            unit_divisor=1024,
        ) as bar:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)
                    bar.update(len(chunk))

    # Rename after complete
    os.rename(temp_file, filename)
    print(f"{filename} download complete.")

```
