### ISSUE TITLE
Internal server error when changing previous version metadata

### ISSUE THREAD

**Issue by jemaf** [zenodo/zenodo#1903]
Hey there,

I am trying to modify the metadata of a previous version of a given repository but, whenever a try to publish it, I receive an Internal Server Error. Is it possible to perform such a change?

**Steps to reproduce**

1. Create a new repository.
1. Perform the first upload and name this version as 1.1.
1. Perform the second upload and name this version as 1.2.
1. Change the metadata of 1.1 (previous version).
1. Internal Server error should appear after trying to publish this change.

**Comment by Glignos** [comment]
After migration of our ES cluster we encountered some issues due to a bug in the elasticsearch API which was causing a mismatch of the versions. 

Closing this since the issue has now been resolved.
