### ISSUE TITLE
communities: uploading directly to community not working if user has to login (broken redirect?)

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1914]
To replicate:

1. Logout
2. Go to a community and click the "New upload" button
3. You're redirected to the login page
4. Login
5. You're redirected to the new upload page (`/deposit/new`), but the community `c` querystring parameter is lost 

> Relevant UV ticket: 242318

**Comment by cenouralm** [comment]
This is fixed in Zenodo RDM
