### ISSUE TITLE
Bibtex records swap names

### ISSUE THREAD

**Issue by aidhog** [zenodo/zenodo#1943]
Example:
https://zenodo.org/record/3483254/export/hx#.XjD3OGhKhPY

`@misc{luzuriaga_jhomara_2019_3483254,
  author       = {Luzuriaga Jhomara and
                  Hogan Aidan and
                  Muñoz Emir and
                  Rosales Henry},
  title        = {Wikitables},
  month        = oct,
  year         = 2019,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.3483254},
  url          = {https://doi.org/10.5281/zenodo.3483254}
}`

This interprets Jhomara as the second name and Luzuriaga as the first. Either (1) the names should be swapped, or (2) a comma put between them.

(1):

`@misc{luzuriaga_jhomara_2019_3483254,
  author       = {Jhomara Luzuriaga and
                  Aidan Hogan and
                  Emir Muñoz and
                  Henry Rosales},
  title        = {Wikitables},
  month        = oct,
  year         = 2019,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.3483254},
  url          = {https://doi.org/10.5281/zenodo.3483254}
}`

(2) 

`@misc{luzuriaga_jhomara_2019_3483254,
  author       = {Luzuriaga, Jhomara and
                  Hogan, Aidan and
                  Muñoz, Emir and
                  Rosales, Henry},
  title        = {Wikitables},
  month        = oct,
  year         = 2019,
  publisher    = {Zenodo},
  doi          = {10.5281/zenodo.3483254},
  url          = {https://doi.org/10.5281/zenodo.3483254}
}`

Option (2) is better if you know for sure what is the last name (e.g., in cases of people with three names, it can otherwise be ambiguous whether the middle name is really a middle name, or a paternal last name, etc.).

(Thanks for the great service!)

**Comment by eric-wieser** [comment]
Isn't this by design? Your issue is that your zenodo record has the names swapped. The export is faithfully matching the zenodo record.

**Comment by aidhog** [comment]
Ouch, yes. Apologies for the noise in that case! :)
