### ISSUE TITLE
doi does not resolve at DataCite

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#1947]
this doi https://doi.org/10.5281/zenodo.3668718  (https://zenodo.org/record/3668718#.XkjtsGhKhPY) does currently not resolve on DOI
![image](https://user-images.githubusercontent.com/4609956/74600723-c1344980-5095-11ea-9d69-4300da6e34b8.png)

**Comment by Glignos** [comment]
This was due to a temporary outage on the Datacite side which is the service we are using to register our DOI's since then it has recovered and we made sure to register that all the DOI's that failed to do so.

**Comment by Glignos** [comment]
Closing since this has been solved.
