### ISSUE TITLE
users: upper-case email causes issues with user profile

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1977]
Steps to reproduce:

1. Go to Zenodo (or an Invenio instance) without being logged-in
2. Sign up and put any part of the email address in upper-case letters (e.g. `SOME@example.com`)
3. After that go to the user profile account settings page and try to change your username or full name
4. An error is returned saying `some@zenodo.org is already associated with an account` (see screenshot)

![image](https://user-images.githubusercontent.com/1814661/80119699-54a06400-858a-11ea-9338-f2654634d3c3.png)

This is probably also an issue coming from `invenio-accounts`, so there should be an issue created there as well (and afterwards linked here)

**Comment by cenouralm** [comment]
We just reproduced the issue and it still is relevant.

**Comment by cenouralm** [comment]
Check on InvenioRDM

**Comment by cenouralm** [comment]
Move the issue to invenio-accounts.

**Comment by cenouralm** [comment]
Created issue on Invenio-accounts https://github.com/inveniosoftware/invenio-accounts/issues/435
