### ISSUE TITLE
deposit: em-dashes in DOI field

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1980]
Steps to reproduce:

1. Create a minimal deposit and insert `10.1234/foo–bar` in the DOI field
2. Save the deposit and reload the page (or navigate to the deposits search page)
3. Internal server error

The issue seems to be with generating the URLs for the resource. We either have to sanitize the input, or fix the URL generation, though DOIs with em-dashes are probably wrong and don't resolve properly at doi.org, so better go with sanitization.

**Comment by cenouralm** [comment]
Is this going to fixed in Zenodo RDM?
