### ISSUE TITLE
deposit: file upload with "#" in filename not possible

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#1981]
Steps to reproduce:

1. Create a new deposit
2. Choose to upload a file with a hash (#) in its name, e.g. `some-file-#-with-hash.txt`
3. Start the upload
4. Nothing happens
5. Refresh the page
6. The file is in the deposit, but its name misses the part after the hash

Probably an issue with how the JS uploader not url-encoding the filename properly and thus it is handled as an URL "anchor".

**Comment by cenouralm** [comment]
This is fixed in Zenodo RDM.
