### ISSUE TITLE
Issue with uploading files

### ISSUE THREAD

**Issue by Heiss** [zenodo/zenodo#1987]
Hello,

i am trying to upload files into my projects in (sandbox-)zenodo through my own service. Last week it works like a charm on the sandbox. Now i get in 2 of 3 cases a response with 500 httpcode. I took the tutorial snippet (https://developers.zenodo.org/#quickstart-upload) and change it a little bit. You can find my code here (https://github.com/Sciebo-RDS/Sciebo-RDS/blob/a8fb93c5de807aeec375857c202ffd8dde6e3484/RDS/circle1_adapters_and_ports/port_zenodo/src/lib/upload_zenodo.py#L178)

The variable _file_ is a werkzeug.FileStorage (https://tedboy.github.io/flask/generated/generated/werkzeug.FileStorage.html) and comes from a flask request (https://github.com/Sciebo-RDS/Sciebo-RDS/blob/connnectUI/RDS/circle1_adapters_and_ports/port_zenodo/src/api/project/files.py#L22)

You can see, that my implementation is a microservice with flask, which provides the ability to push files to zenodo.

I think it is a problem in zenodo, because it works last week without any problems and sometimes it works in my test cases, so i need to trigger the tests multiple times to get passed. 

Maybe you can take a look into this? I do not know, whether it is also a problem with the main zenodo service. I only tried it on the sandbox. This error occured also in the web interface, when i try to upload a file manually with the same possibilty to return an error.

Thank you and greetings,
Heiss

**Comment by awst-baum** [comment]
Can confirm, I also have intermittent issues with uploading files to sandbox. Sometimes it works, sometimes it doesn't (500).

**Comment by Heiss** [comment]
For me, it seems to be fixed.
