### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rtrimana** [zenodo/zenodo#2004]
Hi Zenodo,

I am seeing this issue again: https://github.com/zenodo/zenodo/issues/1660
I tried to sign up with a new account as well but with no success. Could anyone please help?

I first tried to use my Github account to login, then it failed with that screenshot. Then I tried to sign up  and create a new account. Again, I saw the same screenshot with the same Internal Server Error.

Thanks so much.

**Comment by jordynmoscoso** [comment]
I'm having the same issue today, so I have a feeling something is happening on their side!

**Comment by alexandreroberts** [comment]
I'm having the same problem. The Error identifier is `23eaebbcdae445c69220de3d3be3b16e`.

**Comment by gfursin** [comment]
The same here. 
We are storing different Machine Learning artifacts on Zenodo as a part of our [reproducibility initiative](https://cKnowledge.io/reproduced-papers) but all our [packages](https://cknowledge.io/c/package/model-tf-mlperf-ssd-mobilenet) are failing now with the "Internal server error" on Zenodo side :( . 
Any ideas when it can be resolved, please? 
Thank you!

**Comment by krassowski** [comment]
Should be back to normal according to https://twitter.com/ZENODO_ORG/status/1266677742629720065.

**Comment by gfursin** [comment]
Yes, it's working for me! Thanks a lot!!!

**Comment by alexandreroberts** [comment]
Works for me too now. Thanks for the fix!

**Comment by rtrimana** [comment]
Thank you Zenodo! Yes, it's working for me as well. Will close this issue then.
