### ISSUE TITLE
previewer: certain pdf files does not display

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#205]
Investigate why certain PDF files are not previewable:

E.g. https://zenodo.org/record/15813

**Comment by bouzlibop** [comment]
I took a look into that and as it turns out it's working in my local environment. So, as to see what's causing the problem here probably it would be necessary to look into production logs.

**Comment by lnielsen** [comment]
Problem due to bad extension data in bibdocfile (e.g. ``Deliverable_2.1.pdf`` has extension ``.1.pdf`` instead of ``.pdf``).

Possible quick fix. In previewer instead of relying on ``f.superformat`` simply calculate the extension ourselves:
``os.path.splitext(f.name+f.superformat)[1]``
