### ISSUE TITLE
"All versions" view of a record doesn't show version numbers

### ISSUE THREAD

**Issue by Herrner** [zenodo/zenodo#2051]
When clicking on "all versions" for a multi-version records, the list of search results doesn't tell the version numbers of the records.

https://zenodo.org/search?page=1&size=20&q=conceptrecid:%222656630%22&sort=-version&all_versions=True

**Comment by slint** [comment]
Hi Kai!

Is that what you mean or is there some other field/place?

![image](https://user-images.githubusercontent.com/1814661/111161665-b0f1e500-859b-11eb-898f-1ffb53d39010.png)

**Comment by Herrner** [comment]
My bad, sorry.
