### ISSUE TITLE
license CC BY-NC-ND (4.0) 

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#2096]
It seems, that there is no such license at Zenodo?

CC BY-NC-ND (4.0) 

would be needed here: https://zenodo.org/record/4447341#.YAWm7ehKiPo

**Comment by slint** [comment]
The license should be available if you search for "cc-by-nc-nd-4.0" in the License field:

![image](https://user-images.githubusercontent.com/1814661/106472457-f900f080-64a2-11eb-86cb-31170aafc189.png)

Programmatically, this refers to the license with code `cc-by-nc-nd-4.0`: https://zenodo.org/api/licenses/cc-by-nc-nd-4.0
