### ISSUE TITLE
deposit: accept table HTML tags in description

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#2147]
Currently we sanitize HTML input in the `description` field and strip out all tags except for [a curated whitelist](https://github.com/zenodo/zenodo/blob/7327dc80c124cf962f3e66e8b9c48cabeff17536/zenodo/modules/records/serializers/fields/html.py#L33-L55). AFAIK HTML tables do not pose an attack vector, so we can probably add the relevant tags in to the whitelist.

- [x] Update the whitelist with all table-related tags (e.g. `td`, `table`, `th`, etc)
- [x] Check how to enable tables in CKEditor
- [x] Update [Developer docs](https://github.com/zenodo/developers.zenodo.org/) "info" banner with new tags

**Comment by mitsosf** [comment]
Make sure this is merged as well before closing this

[https://github.com/zenodo/developers.zenodo.org/pull/44](https://github.com/zenodo/developers.zenodo.org/pull/44)
