### ISSUE TITLE
docker-compose .... build fails

### ISSUE THREAD

**Issue by rontrompert** [zenodo/zenodo#2154]
Browser & OS (see also https://www.whatismybrowser.com/): <Browser>:<OS>

## Describe the bug
Build fails due to issue with nodejs version,

## Steps to Reproduce
1. docker-compose -f docker-compose.full.yml build
After this the build failes with the following error:
Sorry, you are using node version v10.24.0, which is incompatible. Please install node 7.4.0
The command '/bin/sh -c /tmp/setup-npm.sh' returned a non-zero code: 1
ERROR: Service 'static' failed to build

## Expected behavior
succesfull build.

**Comment by infracritical** [comment]
Was this ever fixed?  I just tried running a build tonight, and it failed with the exact same error message.

**Comment by infracritical** [comment]
Was this ever fixed? I took a look at the commit and reviewed the newly added code. But within the master commit downloaded, the fix did not appear to be applied.  Is this suppose to happen?  BTW, the fixed setup-npm.sh script worked beautifully once applied. Thanks.

**Comment by AdamaSorho** [comment]
@rontrompert thanks, It works for me.
