### ISSUE TITLE
Concept DOI still resolving to the first version rather than the latest one

### ISSUE THREAD

**Issue by ctrl-alt-soneca** [zenodo/zenodo#2159]
## Describe the bug
Concept DOI resolving the first version of a specific record rather than the latest one.

## Steps to Reproduce
The Concept URL: https://zenodo.org/record/4629372 
Concept DOI: https://doi.org/10.5281/zenodo.4629372 
Version 1: https://zenodo.org/record/4629373 
Version 2: https://zenodo.org/record/4633183

## Expected behavior
Concept DOI to resolve the latest version of the record.

**Comment by slint** [comment]
Wrong conceptrecid redirect was fixed to point to latest version
