### ISSUE TITLE
Zenodo DOI badge not displayed

### ISSUE THREAD

**Issue by christianrickert** [zenodo/zenodo#2165]
## Browser & OS
https://whatismybrowser.com/w/WQ4Q37S

## Describe the bug
The Zenodo DOI badge is not displayed on my GitHub repositories.

## Steps to Reproduce
1. Create a new markdown document in GitHub
2. Enter the markdown code for the DOI badge:
`[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.2824830.svg)](https://doi.org/10.5281/zenodo.2824830)`
3. The markdown code is rendered as alternate text with link only:
`DOI`

## Expected behavior
The markdown code should show the badge.

## Additional context
It broke simultaneously on all my repos.

**Comment by sigven** [comment]
I experience the same for all of my repositories.

**Comment by boopsboops** [comment]
Same. Firefox 88.0 on Ubuntu Linux.

**Comment by Yomguithereal** [comment]
Same here: https://github.com/medialab/minet

I guess this comes from an erroneous `Content-Type` header:

```
curl -I https://zenodo.org/badge/169059797.svg
```

yields:

```
Content-Type: text/html; charset=utf-8
```

I think it should be `image/svg+xml; charset=utf-8` so that GitHub Camo cache correctly detects this as an image.

**Comment by wsdewitt** [comment]
This issue seems to be recurring. Should it be reopened?

**Comment by christianrickert** [comment]
Looks broken again. A couple of days ago I could refresh the page and it would load again, but now the badges seem missing again.

**Comment by iyanmv** [comment]
Just noticed this issue as well on both Firefox and Chromium. I think they were working fine just some days ago...

**Comment by YanzhaoW** [comment]
Still the same issue with Safari and Firefox.

**Comment by dwikler** [comment]
Tracing this for my own badge, the endpoint returns 403 with body "Access to this resource has been restricted due to unusual traffic from your network.
Could it be related to rate-limiting rules on the /badge/ endpoint?
