### ISSUE TITLE
Rest API upload Depositions issue

### ISSUE THREAD

**Issue by LibrarPotter** [zenodo/zenodo#218]
In trying to preform a batch upload, I received the following error from Zenodo's RestAPI:
{"status": 400, "message": "Bad request", "errors": [{"field": "conference_title", "message": "unknown field", "code": 10}, {"field": "description", "message": "unknown field", "code": 10}, {"field": "license", "message": "unknown field", "code": 10}, {"field": "title", "message": "unknown field", "code": 10}, {"field": "communities", "message": "unknown field", "code": 10}, {"field": "conference_dates", "message": "unknown field", "code": 10}, {"field": "upload_type", "message": "unknown field", "code": 10}, {"field": "publication_date", "message": "unknown field", "code": 10}, {"field": "keywords", "message": "unknown field", "code": 10}, {"field": "references", "message": "unknown field", "code": 10}, {"field": "creators", "message": "unknown field", "code": 10}, {"field": "access_right", "message": "unknown field", "code": 10}, {"field": "conference_place", "message": "unknown field", "code": 10}]}

As you can see, some of the fields being rejected are required fields for any upload.  My code is not returning any errors. Could this be a problem with the POST function of the API?

Here is an example of the json I dumped for reference:
{
        "conference_title": "The 10th HITRAN Database Conference",
        "description": "We present the latest results in modeling atmospheric absorption features in highresolution astronomical spectra, both, in the optical and near infrared at spectral resolutions of R=30,000 _ 100,000. By using a variety of meteorological input parameters to build realistic atmospheric profiles and by modeling the instrumental profile of our spectrographs, we achieve a fit to telluric lines at the 1% level. While this is often sufficient for the removal of such lines from stellar spectra, we outline the range for further improvements and identify the most likely reasons for the current limitations. We will further emphasize the prospects for using telluric lines as a restframe for precise radial velocity measurements in the near infrared, which may facilitate the detection of very low mass extrasolar planets around late type stars and brown dwarfs. Finally, we will give an outlook how telluric features in astronomical spectra may be used for monitoring climate changes by precise measurements of the column density of CO2 and CH4.",
        "license": "open",
        "title": "I-3. Precise Modeling of Atmospheric Absorption Features in High-Resolution Astronomical Spectra",
        "keywords": [
            "Astronomical spectroscopy",
            "HITRAN"
        ],
        "conference_dates": "22-24 June 2008",
        "upload_type": "presentation",
        "references": [
            "None"
        ],
        "communities": "hitran10",
        "publication_date": "2008-23-06",
        "creators": [
            {
                "affiliation": "Institute for Meteorology, Ludwig-Maximilians-University (LMU), 80333 Munich, Germany",
                "name": "Andreas Seifahrt"
            },
            {
                "affiliation": "Institute for Meteorology, Ludwig-Maximilians-University (LMU), 80333 Munich, Germany",
                "name": "Hans Ullrich Käuf"
            },
            {
                "affiliation": "Institute for Meteorology, Ludwig-Maximilians-University (LMU), 80333 Munich, Germany",
                "name": "Günther Zängl"
            }
        ],
        "access_right": "open",
        "conference_place": "Harvard-Smithsonian Center for Astrophysics"
    }

**Comment by lnielsen** [comment]
Hi @LibrarPotter,

I think the problem is that you need to enclose the JSON like this:

```{"metadata": ...<your json here>.... }```

See e.g. the Quick Start example point 9 on https://zenodo.org/dev
