### ISSUE TITLE
Get progress "error" when uploading 8GB zip file

### ISSUE THREAD

**Issue by jhnwllr** [zenodo/zenodo#2189]
On the web interface I get progress "error" when trying to upload an 8GB zip file. 

The file will upload completely but then have progress error when it reaches the final stage. 

The file does not appear to be saved when I refresh the page. The other meta data about the dataset is saved.

**Comment by ines-cruz** [comment]
Dear user, Could you kindly contact our support line at info@zenodo.org so we can help with this issue?

**Comment by fishbotics** [comment]
@jhnwllr , did you eventually get your data uploaded? I am having the same issue.
