### ISSUE TITLE
can't edit metatada

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#2250]
in this case https://zenodo.org/record/51882#.YaTK_NDML8D, when I want to edit the title, I get this message

![image](https://user-images.githubusercontent.com/4609956/143870264-9f4168d5-f1b6-423f-aaf4-deed0c377e83.png)

![image](https://user-images.githubusercontent.com/4609956/143870215-283fda93-bee7-4bb2-992f-f88de8e2ae81.png)

**Comment by ines-cruz** [comment]
Dear user, thank you for bringing our attention to this issue. I can see the problem persists, could you please contact our support team over at  info@zenodo.org  so we proceed with editing the record metadata?

**Comment by ines-cruz** [comment]
Note: The edit button redirects to a tombstone but when going to /deposit/record_id we can see the Edit form

**Comment by myrmoteras** [comment]
thanks for the hint - I corrected the title, so it is ok

![image](https://user-images.githubusercontent.com/4609956/154435975-5cf14e57-5d99-4a09-844d-d354db231a06.png)
