### ISSUE TITLE
support: names should be allowed to contain commas

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#2264]
We have a rule in the support form that doesn't allow the "name" field to contain commas. Maybe there was some legacy reason for this rule (e.g. email sending failing, since we build a `Smith, John <john.smith@mail.com>` string), but in any case, this doesn't make much sense, so we should look into this and remove the validation to support names with commas (which e.g. is a norm for user profile names).

To replicate the issue:

1. Open the support form
2. Type a name that contains a comma (e.g. "Smith, John")
3. See error about names containing commas

**Comment by sunarch** [comment]
Two notes on replication:
- At least for me, the fields are only validated on submit, not when typing.
- If the user is logged in, the name field is filled in automatically from the user profile and disabled, so that a change to the field is only possible via a change to the name on the profile.
