### ISSUE TITLE
GitHub repo is linked to Zenodo but has no webhook

### ISSUE THREAD

**Issue by dominiquesydow** [zenodo/zenodo#2281]
Browser & OS (see also https://www.whatismybrowser.com/): Chrome 97 macOS

## Describe the bug
Published new release on GitHub but cannot see the new release on Zenodo.

## Steps to Reproduce
1. Go to https://github.com/volkamerlab/opencadd/releases/tag/v1.0.1 &mdash; latest release is 1.0.1
2. Go to https://zenodo.org/record/5653543 &mdash; latest release listed is 1.0.0 (as shown in the screenshot below, the 1.0.1 is not listed at all &mdash; not failed, not pending).

## Expected behavior
See the 1.0.1 release on Zenodo.

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/7207093/149412496-95c2e72b-d059-41cc-98f9-976e69f7288f.png)

## Additional context
1. Thought I might try out triggering the release manually as described [in this issue](https://github.com/zenodo/zenodo/issues/1463#issuecomment-894548040) &mdash; this suggestion requires an access token.
2. Going to the repo's webhooks settings (via this URL: https://github.com/volkamerlab/opencadd/settings/hooks) and finding _no_ zenodo webhook.

Is it even possible to trigger an update on Zenodo if there is no webhook (incl. a webhook token) in this repository; if not, how do I add a webhook to GitHub (without knowing the Zenodo access token)?
Please note that my institution "volkamerlab" gives access to Zenodo under Settings > Third party access.

Thank you!

**Comment by zacjohnston** [comment]
I think this is because the toggle in the top right of your screenshot is set to "Off". Set it to "On" for automatic release monitoring.

**Comment by dominiquesydow** [comment]
Hi @zacjohnston, 

Thanks a lot! I could swear that I have toggled this off and on before, aiming to generate the zenodo GitHub webhook. 

Anyhow, did it again, finally found the webhook under my GitHub repository's Settings > Webhooks as described [here](https://ocean.sagepub.com/blog/how-to-get-a-doi-for-your-teaching-materials-with-zenodo#repository) and used [this trick](https://github.com/zenodo/zenodo/issues/1463#issuecomment-1007602828) to make zenodo pick up my old release (leaving this here just in case anyone else runs into this issue).

Thanks again - closing this issue now :)
