### ISSUE TITLE
Fails to produce DOI for release: Creators field is empty

### ISSUE THREAD

**Issue by chraibi** [zenodo/zenodo#2293]
Firefox 97 on macOS (Catalina)

For s GitHub-repository, Zenodo stopped producing DOI-numbers for releases. 

<img width="879" alt="Screen Shot 2022-02-17 at 18 40 50" src="https://user-images.githubusercontent.com/5772973/154539436-2b802e45-7890-47e8-abba-deb7797d6db7.png">

The error is 
```
{
    "errors": "{'metadata': {'creators': {1: {'name': [u'Field may not be null.', lu'Name is required.']}}}}"
}
```

I wonder why is the `creator's` name empty? Is this some settings in the GitHub-Repo?

**Comment by ines-cruz** [comment]
Dear user, thank you for bringing this issue to our attention. Could I kindly ask you to contact our support service over at  info@zenodo.org so we can take a closer look at the failed releases?

**Comment by ppanero** [comment]
As disccused through support line, the issues came from the `.zenodo.json` and `citation.cff` files formatting.
