### ISSUE TITLE
Add PeerReview as a publication type

### ISSUE THREAD

**Issue by thewilkybarkid** [zenodo/zenodo#2295]
## Is your feature request related to a problem? Please describe.

PREreview uploads peer reviews to Zenodo with a 'Journal Article' type (e.g. https://zenodo.org/record/6207581). This isn't correct, but there isn't a type suitable for peer reviews.

## Describe the solution you'd like

'Peer Review' added as a publication type.

## Describe alternatives you've considered

Using 'Other' as a type.

## Additional context

https://github.com/zenodo/zenodo/issues/2206 refers to changes based on the [DataCite 4.4 schema](https://schema.datacite.org/meta/kernel-4.4/), which added `PeerReview` as a `resourceTypeGeneral` property.

**Comment by Melissa37** [comment]
I second this request. Using the DataCite API I cannot identify Peer review items if they are not given the appropriate resource type
