### ISSUE TITLE
Link existing record to GitHub repo

### ISSUE THREAD

**Issue by johnomotani** [zenodo/zenodo#2310]
## Is your feature request related to a problem? Please describe.

I have a piece of software for which I've created a Zenodo record for existing releases. I would like to enable Zenodo's GitHub integration to create records for future releases. As far as I can tell, at the moment if I did that, the future releases would not be connected to the existing record.

## Describe the solution you'd like

An option to add GitHub integration to an existing record.

## Describe alternatives you've considered

Continue to add new versions to the existing record manually. Obviously works, but not ideal.

**Comment by ines-cruz** [comment]
Dear @johnomotani  could I kindly ask that you reach out to us via our support channel at [info@zenodo.org](mailto:info@zenodo.org) so we can look into this issue further?
