### ISSUE TITLE
Transfer ownership of project

### ISSUE THREAD

**Issue by balopat** [zenodo/zenodo#2324]
## Is your feature request related to a problem? Please describe.

I left an org that I setup Zenodo automation for from a Github repo. Now, we realized that the ownership was tied to my user account and I can't share the permissions (https://github.com/zenodo/zenodo/issues/151). Is there a way to transfer the ownership? 

## Describe the solution you'd like

Transfer the ownership of a project to another Github user until https://github.com/zenodo/zenodo/issues/151 is resolved. 

## Describe alternatives you've considered

None is available as far as I understand.

**Comment by ppanero** [comment]
Dear @balopat,

Thanks for opening the issue. Right now this can only be achieved via our support line, you can open a ticket here https://zenodo.org/support.

Whereas we cannot promise any dates at the moment, this is a very common request from users and we are taking steps towards a solution it in the current development sprints.

Have a nice weekend!
