### ISSUE TITLE
Can´t connect to GitHub : External service is already linked to account

### ISSUE THREAD

**Issue by mcvta** [zenodo/zenodo#2335]
Browser & OS (see also https://www.whatismybrowser.com/): <Browser>:<OS>

## Describe the bug
The login in Zenodo it´s ok. However when I try to conect to GitHub I get the following message:
External service is already linked to another account.

## Steps to Reproduce
1. Go to 'Zenodo'
2. Click on 'Linked accounts'
3. Scroll down to 'GitHub'
4. Click Connect
6. See error
"External service is already linked to another account."

## Expected behavior
I would like to see the list of GitHub repositories
## Screenshots (if applicable)
![Untitled](https://user-images.githubusercontent.com/45259660/172145320-d77d7682-a269-4858-97a0-028d3b74bde3.jpg)

**Comment by ppanero** [comment]
Dear @mcvta,

is there any chance you have "logged in with GitHub" at some point in the past? Could you contact us through our support line to further investigate you case?

Thanks!
