### ISSUE TITLE
Curator feedback

### ISSUE THREAD

**Issue by dbroemmel** [zenodo/zenodo#2348]
When a community curator receives a request to add a record to the community, the only options are accept/reject. There is no workflow in place which would enable a feedback between curator and owner of the record. Any missing/wrong information (e.g. keywords, funding body, typos that caused a reject) cannot easily be communicated. Since the creator of a record may not be one of the authors (or there may be many authors) any contact details are very difficult to come by. Of course, the record can only be changed by its creator. Ultimately, a reject may leave the person requesting the entry puzzled and the entry may not be added in the end.

While the options as such are fine, an easy, built-in way to provide hints on what to change/fix to get the record accepted is missing. Perhaps set the request to pending while updates are expected and provide a small comments box which will be sent to the creator of the request. While the request is pending, any comments sent or actions taken should stay visible and linked to the request. This should ideally be the case for the curator and the person requesting the addition to the community.

Obtaining the contact details of the record owner and communicating via email may work for a single or few such requests, but is impractical for a larger number of requests. It also breaks any direct link between records and the communication, making it harder to follow up later or obtain the status of requests.

**Comment by namurphy** [comment]
It looks like it's now possible to post a comment and have a conversation on a request for a record to join a community.  Is this issue therefore ready to be closed?

Also — a thank you for raising this issue, and also to everyone who implemented this great feature!

**Comment by dbroemmel** [comment]
Seems there is a lot more possible now, than just having a conversation with people submitting records. I had a quick look at the new UI on the sandbox and performed a short test, seems everything I had in mind is now possible. Great! Thanks for this effort!
