### ISSUE TITLE
Presented data volume on records statistics much higher than what's uploaded

### ISSUE THREAD

**Issue by ctrl-alt-soneca** [zenodo/zenodo#2350]
The statistics of a record are showing a much higher value of "Data volume" than what's really uploaded. The record in question is https://zenodo.org/record/6014422

<img width="290" alt="1" src="https://user-images.githubusercontent.com/79139616/177729003-08aa429e-3299-4345-a084-a39c2bd067d4.png">

<img width="596" alt="2" src="https://user-images.githubusercontent.com/79139616/177729017-3b8f511b-8854-4854-bbe0-c160c48816d2.png">

**Comment by ppanero** [comment]
Maybe I'm wrong but isn't the "Download volume" the _total_ size of the downloads? The specified record has 15 unique downloads for a data volume of 31GB (aprox data of this morning). If you multiply 15 *2 you get the 31GB (with the error margin generated by the other 500mb file hehe).

**Comment by ctrl-alt-soneca** [comment]
Ah, you are probably right!! I did not understand that! Thank you for the explanation! I'm closing the issue!
