### ISSUE TITLE
Can't upload from Google Drive

### ISSUE THREAD

**Issue by zhousun21** [zenodo/zenodo#2363]
Hello,
I am trying to transfer file directly from Google Drive to Zenodo using the web interface.  The Google Drive files are set to public: anyone with a link can view/download.  The test file is 50 mb, so fairly small.

From the web interface, I hit browse and enter the public link, but it says file not found.  When I enter the link in the browser itself it works fine, so using the browse function is obviously not the right way to do this.

Any advice on transferring files directly from Google Drive to Zenodo?

**Comment by ppanero** [comment]
Dear @zhousun21 transferring files directly from GDrive to Zenodo is not supported. You need to upload them from your PC.
