### ISSUE TITLE
scholarly citation

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#238]
We would like to suggest that Zenodo provides also scholarly citation that we use in our area of bibliographic citations.

For example, 
Smith, Helen M.. (2008). Synonymy of Homalopoltys (Araneae: Araneidae) with the genus Dolichognatha (Araneae: Tetragnathidae) and descriptions of two new species. Zenodo. 10.5281/zenodo.10091

Should also include the  the journal name, the volume, issue, first to last page.

For our ongoing discussion with CrossRef, we should make sure that the metadata should be available in form that CrossRef requires.

I hope this is possible - and if so, please let us know so we can define together the necessary specifications.

For us, this is very important to promote BLR in our community.

See also https://github.com/zenodo/zenodo/issues/191 
or for a couple of examples 
https://github.com/zenodo/zenodo/issues/144

**Comment by lnielsen** [comment]
Generate citation style language.

**Comment by lnielsen** [comment]
We are now generating the Citation Style Language JSON (See CSL in export section) which is used to generate the citation from.
