### ISSUE TITLE
Bad link for DOI

### ISSUE THREAD

**Issue by EHadoux** [zenodo/zenodo#243]
Hi,

Zenodo gives me a 404 link on http://dx.doi.org/10.5281/zenodo.17034.
The repository is Ehadoux/aptimizer.

Thanks

**Comment by lnielsen** [comment]
Hi,

There was a bit of a backlog in the ingestion system. It has been solved now and the record is available.

Best regards,
Lars

**Comment by EHadoux** [comment]
Thanks very much.
