### ISSUE TITLE
Cannot publish R package from GitHub because of incorrect License ID (GPL-3 or later)

### ISSUE THREAD

**Issue by japhir** [zenodo/zenodo#2451]
I'm on Firefox on Arch Linux.

## Describe the bug
I'm trying to link my github repo https://github.com/japhir/snvecR to generate a Zenodo publication with a DOI for a new R package.
I've done this many times before and it has always worked.

However, now I get the following error:
```
{
    "errors": "The license ID you have selected is not present in our system. For the available licenses please check in the following URL https://developers.zenodo.org/#licenses"
}
```

From https://github.com/zenodo/zenodo/issues/1933 I can see that you use the spdx list of license names.
From https://spdx.org/licenses/ I can see that since version 3.0 of this database, it expects to get `GPL-3.0-or-later`. 
Looking at the payload of my failed submission, it looks like Github has given it a `"spdx_id": "GPL-3.0", `, which is marked as deprecated.

How can I customize this value so that the github release triggers a zenodo archive correctly?

**Comment by japhir** [comment]
This might be on GitHub's API in stead of on Zenodo... Anyhow, the integration is not working as expected.

**Comment by japhir** [comment]
I've resolved this by updating the CITATION.cff file licence field to GPL-3.0-or-later. It seems like this is where Zenodo gets the info from!

**Comment by ozak** [comment]
@japhir how did you manage to include the `CITATION.cff` in the release? I tried following your suggestion, but the `cff` does not seem to be passed. I tried adding it to the release, but it still failed and generated the "Invalid value gpl-3.0.".

It is as if the citation file was not taken into account. Here's what it shows:
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/361f659e-5cee-4362-b0cb-c9d240187689">

and here is my [`CITATION.cff`](https://github.com/human-mobility-index/hmi/blob/main/CITATION.cff).

In my main branch, I see the `CITATION.cff` file, but not in the tagged release as shown below.

<img width="941" alt="image" src="https://github.com/user-attachments/assets/a4dc4f66-bc7f-42d7-b2ba-fc18a6809ad1">
<img width="943" alt="image" src="https://github.com/user-attachments/assets/9b41f945-b26e-437a-9085-81d8ee13b99c">
