### ISSUE TITLE
badge redirects to non-existent DOI

### ISSUE THREAD

**Issue by musoke** [zenodo/zenodo#2459]
Browser & OS (see also https://www.whatismybrowser.com/): 

both of

- https://whatismybrowser.com/w/HWFNTYN (Chrome, Linux)
- https://whatismybrowser.com/w/DK9W3TX (Firefox on Linux)

## Describe the bug

The badge [![DOI](https://zenodo.org/badge/265130304.svg)](https://zenodo.org/badge/latestdoi/265130304) at  https://github.com/musoke/UltraDark.jl/blob/e8b0f1d406f324c8f1ba404256f5ed313ab25bbf/README.md?plain=1#L3 redirects to an error page rather than a zenodo record.

## Steps to Reproduce

1. Go to https://zenodo.org/account/settings/github/repository/musoke/UltraDark.jl while logged in as me (yes, might be difficult, so I will give lots of screenshots)
![image](https://github.com/zenodo/zenodo/assets/16665084/c24f566e-9b6b-4fee-9ca2-6483d2eca013)

2. Click on button to get DOI badge
![image](https://github.com/zenodo/zenodo/assets/16665084/ff581f50-ce43-4ef9-b166-3d5639ed9a6b)

3. Box opens with possible codes to copy
![image](https://github.com/zenodo/zenodo/assets/16665084/4a52c90b-9b30-411a-ae75-af6149be6311)

4. Copy markdown
```
[![DOI](https://zenodo.org/badge/265130304.svg)](https://zenodo.org/badge/latestdoi/265130304)
```

5. See that this renders nicely on github: [![DOI](https://zenodo.org/badge/265130304.svg)](https://zenodo.org/badge/latestdoi/265130304)

6. See that the target https://zenodo.org/badge/latestdoi/265130304 redirects to https://doi.org/10.5281/zenodo.7811180

7. Get an error from doi.org
![image](https://github.com/zenodo/zenodo/assets/16665084/8da57834-4c67-47d0-a324-ad6cf3ff6729)

## Expected behavior

I expect to be redirected to the latest version of the release on zenodo

**Comment by mitsosf** [comment]
Hey @musoke 

The DOI registration must have failed on our end, which happens sometimes.
I have manually retriggered the DOI registration, so your DOI - and your badge - should be now resolving as expected.

If you encounter any similar issues in the future it is better to get in touch with us through [Zenodo support](https://zenodo.org/support)  to better keep track of your issue.
