### ISSUE TITLE
Can't enable GitHub repositories via integration with new sandbox.zenodo.org

### ISSUE THREAD

**Issue by alexlancaster** [zenodo/zenodo#2477]
Browser & OS (see also https://www.whatismybrowser.com/): Firefox:Linux

## Describe the bug
It looks the sandbox.zenodo.org has been updated to use the new system.  It looks the github integration isn't quite working. 

## Steps to Reproduce
1. Login to https://sandbox.zenodo.org/ using github credentials
2. Visit https://sandbox.zenodo.org/account/settings/github/
3. Refresh to get the list repositories, try and enable one using toggle

## Expected behavior
The repo should show an active "bar" next to it, and it should be clickable.  If you click the repo name, after it's enabled, the linked page just shows `Internal server error`.  Also just after you click "ON", it shows an error message (see screenshot):

```
Request failed with status: 400
```

## Screenshots (if applicable)
![Screenshot from 2023-09-22 18-22-23](https://github.com/zenodo/zenodo/assets/5281946/1dc373df-dac8-48ae-9686-4bc41240a52c)

**Comment by glevv** [comment]
It does not work on production website too. Can't connect sync or connect new repository.

**Comment by alexlancaster** [comment]
This seems to be resolved now on sandbox, I was able to enable the integration and publish a release, which uploaded it to Zenodo:

https://sandbox.zenodo.org/records/47315
