### ISSUE TITLE
REST API endpoint filtered returned 404

### ISSUE THREAD

**Issue by emarzini** [zenodo/zenodo#2483]
Browser & OS (see also https://www.whatismybrowser.com/): Everywhere

## Describe the bug
The record rest api endpoint seems that is not working anymore.
If I try https://zenodo.org/api/records/ the system return some data, but if I try to filter the records put a community filter it doesn't anymore.
I integrate the API in several website to retrieve automatically the records, but now I can't see anything.

## Steps to Reproduce
1. Go to [https://zenodo.org/api/records/?communities=biodt](https://zenodo.org/api/records/?communities=biodt)
2. See error

## Expected behavior
The expected behavior is to get all records for a specific community

**Comment by AlexanderPico** [comment]
+1 me too!  https://zenodo.org/api/records/?communities=wikipathways

**Comment by duncanmmacleod** [comment]
@emarzini, @AlexanderPico, I stumbled here because my API endpoint is also returning a 404 now  (https://zenodo.org//api/records/?page=1&size=10&q=conceptrecid:%22597016%22&sort=-version&all_versions=True), and I've been hacking at the API endpoints for a bit.

My case I think fundamentally boils down to the fact that the id 597016 returns a 404:

https://zenodo.org/api/records/597016

This is the URL provided by selecting the `links/parent` URL from the REST response of https://zenodo.org/api/records/8409995.

In your cases, does removing the trailing `/` address your issue, e.g.

- https://zenodo.org/api/records?communities=biodt
- https://zenodo.org/api/records?communities=wikipathways

?

Something has clearly changed with the API very recently, but according to the [changes](https://developers.zenodo.org/#changes) there hasn't been a change in just over 6 years.

**Comment by emarzini** [comment]
Thanks @duncanmmacleod . Your workaround works. I'm pretty upset to the fact that no changes are documented

**Comment by emarzini** [comment]
@duncanmmacleod Sorry to say that, but the workaround you found is not usable. If you compare the url you put in the comment you can see that they are the same records, due the fact the filter by communities is not working.

So with the trailing slash that worked before I receive a 404 error. If I don't use it the filter is ignored

@AlexanderPico do you find some other solution?

**Comment by AlexanderPico** [comment]
No solution found yet...

**Comment by AlexanderPico** [comment]
And via Python API, I get a different set of 25 records, none of them belonging to the wikipathways community as specified:

```
r = requests.get(f"{baseurl}/records",
                        params={'communities':'wikipathways',
                        'size':100,
                        'all_versions':0,
                        'access_token': f"{args.token}"})
```

**Comment by Raen111** [comment]
вт, 17 окт. 2023 г., 22:35 Alexander Pico ***@***.***>:

**Comment by duncanmmacleod** [comment]
> And via Python API, I get a different set of 25 records, none of them belonging to the wikipathways community as specified:
> 
> ```
> r = requests.get(f"{baseurl}/records",
>                         params={'communities':'wikipathways',
>                         'size':100,
>                         'all_versions':0,
>                         'access_token': f"{args.token}"})
> ```
> 
> This a snippet from code that I had been reliably running each month for over the past year, but failed for the first time on Oct 15 and continues to fail.

@AlexanderPico, in my fairly haphazard debugging for my usage, I found that the `all_versions` key seems to have been renamed to `allversions` (without the `_`), does that help you?

**Comment by AlexanderPico** [comment]
@duncanmmacleod Thanks for sharing the tip, but unfortunately no. I'm seeing the same set of random (not from wikipathways community) results in the return.

Also, the return used to be parsed by `hits`, e.g., following the requests.get line with :

```
list(r.json()['hits']['hits'])
```

But the structure of the returned JSON has changed and `hits` are no where to be found.

**Comment by AlexanderPico** [comment]
FIXED!

> Dear user,
Sorry for any inconvenience you may have experienced.
We have deployed some fixes regarding compatibility with the old REST API format. That means, retrying the example you provided it should give back the correct results.
Please let me know if there is anything else I can help you with.
Best regards,
Zenodo Support
