### ISSUE TITLE
Failure to upload large files with curl

### ISSUE THREAD

**Issue by fxcoudert** [zenodo/zenodo#2485]
## Describe the bug
I am following the documentation at https://gist.github.com/slint/2263b2212743a68b2851b2cb7865675e for file upload with curl. Upload of large files (2.3 GB) fails.

## Steps to Reproduce

```
curl --upload-file ~/Downloads/crystal_300K_volume_change0.tar "https://zenodo.org/api/files/56b80de7-c506-4c50-b918-8571eb6d0601/crystal_300K_volume_change0.tar?access_token=xxxxxxxxx"
{"status": 400, "message": "Bucket quota exceeded."}
```

At first, I got as error `413 Request Entity Too Large`, but I tried a couple of times (through curl, through Python, through the web browser) and the error later turned to `Bucket quota exceeded`.

## Expected behavior

Upload of large files should be possible.

**Comment by fxcoudert** [comment]
I should have added:

<img width="458" alt="Capture d’écran 2023-10-17 à 17 00 33" src="https://github.com/zenodo/zenodo/assets/1980544/a53080e9-de06-4720-b71c-21e5c4b9e7e6">

There is plenty of space left

**Comment by slint** [comment]
Hi @fxcoudert the issue has been fixed now, can you retry the upload (either via the UI or cURL)?

**Comment by fxcoudert** [comment]
Yes, it works now, thanks.

**Comment by kikislater** [comment]
Please reopen, it's not working even from gui or api
