### ISSUE TITLE
API Return No Longer Includes Bucket ID

### ISSUE THREAD

**Issue by AlexanderPico** [zenodo/zenodo#2495]
Our monthly update script for the Zenodo API stopped working after the recent update. The error is in the step that expects to find `bucket` within the `links` field for an existing record.  Checking by URL, you can see that it is indeed missing:

https://zenodo.org/api/records?communities=wikipathways&size=1

Here's are the Python calls that are failing:

```
r = requests.get(f"{baseurl}/records",
                        params={'communities':'wikipathways',
                        'size':100,
                        'all_versions':0,
                        'access_token': f"{args.token}"})

list(r.json()['hits']['hits'])[0]['links']['bucket']

#KeyError: 'bucket'
```

**Comment by jrfep** [comment]
I found something similar in the last few days, but the behaviour keeps changing, sometimes it returned an incomplete bucket link or the link was not accessible for upload operations. See  #2493

**Comment by AlexanderPico** [comment]
Zenodo team provided this note and workaround that addressed our needs.

;tldr get bucket id from deposit API

> We are aware that the "bucket" link cannot be found at the moment when you search for records. We are working on a fix but this will take some time to implement. In the meantime, I can propose to you some alternatives so you can have a working workflow as fast as possible.
> 
> The "bucket" link, assuming you want to upload a file for a specific record, at the moment is available only under deposit API i.e. `https://zenodo.org/api/deposit/depositions/<record_id>`. Probably you can query our system for every record your search returned and then act based on that record's response from the API. 

Thanks!
