### ISSUE TITLE
Support contact form on zenodo.org is not working (500)

### ISSUE THREAD

**Issue by Chilipp** [zenodo/zenodo#2527]
Hey lovely zenodo support!

sorry, I know that I should post bug reports via the support page at zenodo.org (https://zenodo.org/support) but I always get a 500 hundred error (see screenshot). 

![image](https://github.com/zenodo/zenodo/assets/9960249/536485bf-535d-4cc7-98a1-26e1d6b6954b)

I'd like to report a security issue but I do not know how if the support form is not working. Could you please tell me, where to report it?

**Comment by ElienDewitte** [comment]
same here, but I even do not have an internal error. I can click on "send request" but nothing happens. 
F12 inspector says also failed with status code 500

**Comment by Tc-Li** [comment]
The same for me.

**Comment by Haocun** [comment]
Same problem for me. Please solve it as soon as possible. Thanks

**Comment by carlinmack** [comment]
This issue has been fixed now :)
