### ISSUE TITLE
problems with all kind of forms

### ISSUE THREAD

**Issue by ElienDewitte** [zenodo/zenodo#2529]
Sorry to contact you here, but the contact form is not working at this moment (500 error)

I originally wanted to report a bug, but it seems impossible, so i add it here:
my colleague was pointing me to the fact that there is no longer a request form for datasets with restricted access... 
Has this changed place or something? we cannot find it anywhere anymore. The FAQ's say you should have a request form, but nothing to find https://help.zenodo.org/docs/share/access-requests/request-access/

I would like to report it as a bug, but nowhere to go at this moment :( 
![download_restricted_dataset](https://user-images.githubusercontent.com/88656081/312352449-2f92d99e-b777-4bc5-920b-8f6e1c949382.PNG)

**Comment by Tc-Li** [comment]
The same with me.

**Comment by Haocun** [comment]
Same problem for me. Please solve it as soon as possible.

**Comment by Raen111** [comment]
Я являлся владельцем зенодо,пока у меня обманом ее не украли ,назовем это так! Можете крес на этом имени и сайте поставить! Все преступники будут привлечены согласно законодательста

**Comment by Raen111** [comment]
Зенодо я лично похороню,чем и занят в данный момент,всем удачи

**Comment by carlinmack** [comment]
Not all restricted records have a request access form. The owner of the record can [disable or enable requesting access](https://help.zenodo.org/docs/share/access-requests/allow-requests/) to restricted records at any time. For example, a record with restricted access that you can request access to is https://zenodo.org/records/6406114
