### ISSUE TITLE
Sync with Github error (Request failed with status code: 504)

### ISSUE THREAD

**Issue by AliciaMstt** [zenodo/zenodo#2535]
Hi,

I'm trying to sync a github repo from an organization (of which I'm the onwer) with my Zenodo. This is something I have done before with other organization, but the problem is with a new one. I have enabled third-party access to the Zenodo application, however my new organization's repositories do not show up in the list. 

I think the problem is that my list of repos was updated 10 months ago, and the organization and repo I want to add are new.

<img width="946" alt="image" src="https://github.com/zenodo/zenodo/assets/5412404/e9a5c2d6-b1ec-41d5-945e-cbbec5747846">

However, when I click "Sync now" after few seconds I'm getting the error Request failed with status code: 504

<img width="948" alt="image" src="https://github.com/zenodo/zenodo/assets/5412404/10d7711c-1b22-49f4-a015-ff85e7457157">

My internet connection is stable and of 17 Mbps. Is there a gateway timeout problem from your side? Or what can I do? I'm having this problem since yesterday and it is starting to become urgent.

This issue is related to https://github.com/zenodo/zenodo/issues/1814 but since I think the problem is with the sync, I opened a new issue instead of reporting it in that thread. 

Thanks!

**Comment by AliciaMstt** [comment]
Well, after several refreshing attempts the sync just worked. So I suppose the server was just having a nap.

**Comment by joshmoore** [comment]
Running in to this now repeatedly for my account. I assume it's tied to a user's number of organizations. (I've run into this with other applications.) I'd suggest having a sync button per organization as well.

**Comment by wsnoble** [comment]
Also running into this.  My user is tied to multiple organizations, but I only need Zenodo to sync one of them.  Short of having a per-organization "sync" button, another option would be to be able to revoke Zenodo authorization on a per-organization basis. I don't see any way to do that from the [GitHub OAuth settings](https://github.com/settings/applications).

**Comment by joshmoore** [comment]
Thanks for the confirmation, @wsnoble. No maintainers have commented here, so I've filed an issue with https://zenodo.org/support (per https://github.com/zenodo/zenodo/issues/new/choose) cross-linking this page. I'll send any updates I receive.

**Comment by zimolzak** [comment]
I'm getting this a lot today (probably a dozen sync attempts over several hours). @joshmoore, is there a way that I can also follow the Zenodo support issue/ticket you filed? If not, I'll check back here.

Note that I am also in four different GitHub orgs, but only the repos associated with my own GitHub username are Zenodo-enabled. I do see repos from one org (where I am the owner) in the Zenodo list, but my repo list was last synced two months ago.

**Comment by joshmoore** [comment]
@zimolzak: I've not received any notification unfortunately.
