### ISSUE TITLE
Cannot create new version of Zenodo record with pre-existing, non-Zenodo, DOI 

### ISSUE THREAD

**Issue by jhpoelen** [zenodo/zenodo#2536]
To reproduce:

1. create a new Zenodo deposit
2. edit Zenodo  deposit draft to include a pre-existing DOI, include a publication.pdf file
3. publishing the Zenodo record
4. now, to correct a mistake the publication.pdf file, click "edit" on the published Zenodo record

expected:

Zenodo record can be edited and the updated publication.pdf file can be added.

actual:

the "new version" button is disabled.

For example, see sandbox deposit https://sandbox.zenodo.org/records/53899 and attached screenshot.  

Related to issue https://github.com/bat-literature/bat-literature.github.io/issues/3 .

![Screenshot from 2024-05-10 11-53-17](https://github.com/zenodo/zenodo/assets/1084872/e4569400-2d79-4841-ac5e-74e814f80d28)

**Comment by carlinmack** [comment]
We don't support versioning with non-Zenodo DOIs. Instead you can create a new upload and link it to the previous version by adding [a note](https://help.zenodo.org/docs/deposit/describe-records/descriptions/#note) or linking the DOI in the related identifiers field.

**Comment by jhpoelen** [comment]
@carlinmack thanks for your prompt reply. 

@myrmoteras given that Zenodo doesn't support versions for existing DOIs, we may want to reconsider were we place existing DOIs in our Zenodo metadata. I suggest to use related identifiers instead. Thoughts?

**Comment by jhpoelen** [comment]
Note also that for existing non-zenodo DOIs that already exist as DOIs for a Zenodo record, you cannot create another Zenodo record with the same DOI. 

See error message below.

![image](https://github.com/zenodo/zenodo/assets/1084872/bf4728d9-98ad-4b46-9c5a-8ec1d3f1c3e6)

**Comment by AdelieRanville** [comment]
Hi, I got the same issue, I put the publisher-provided DOI as existing DOI for a preprint and I wanted to put several versions of it... now I am stuck. I cannot generate a new DOI for the preprint version nor change the file.
It would be nice to be able to generate a zenodo DOI after we make the mistake to put the publisher-provided DOI in that field (or to have a little warning explaining that publisher-provided DOI should not be put there).

**Comment by Coolphy** [comment]
A Zenodo DOI should be generated for every upload, and other DOIs should be put in alternative identifiers by default.

**Comment by jhpoelen** [comment]
> A Zenodo DOI should be generated for every upload, and other DOIs should be put in alternative identifiers by default.

Yes, that would be my preference also.

**Comment by Ritwik-Sh** [comment]
Was a fix found for this? I put in a new doc with a pre-existing DOI

**Comment by AdelieRanville** [comment]
You can contact the support and ask for a file modification : https://zenodo.org/support

**Comment by carlinmack** [comment]
Yep, you can request file modification for Zenodo records and/or request to have the Zenodo DOI restored for a record with an external DOI (which would then enable you to use the versioning feature)
