### ISSUE TITLE
Linking to a heading in the same markdown document does not work

### ISSUE THREAD

**Issue by grakz** [zenodo/zenodo#2540]
If I upload a markdown document where I am linking to another spot in the same document and look at the preview, the internal links do not work. Neither adding a custom id using 

~~~
### Heading title {#custom-id}
~~~

nor using automatic ids works in the Zenodo markdown preview.

Indeed, linking to the manual id

~~~
[jump to heading](#custom-id)
~~~

or linking to an automatic id (turn the heading title into lowercase and replace spaces with dashes "-")

~~~
[jumpt to heading](#heading-title) 
~~~

do not work in the markdown preview.

See [markdownguide.org](https://www.markdownguide.org/extended-syntax/#heading-ids) for more information on the expected behavior.

**Comment by carlinmack** [comment]
Can you reopen this in https://github.com/inveniosoftware/invenio-previewer that's where the markdown previewer lives

**Comment by grakz** [comment]
Okay, done. Thank you!
