### ISSUE TITLE
deposit: add support for contributors

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#274]

**Comment by lnielsen** [comment]
Sames as #265

**Comment by bouzlibop** [comment]
This is what we want?

```700__ $a - Personal name $u - Affiliation $4 - Relator code```

* [700 - Added Entry-Personal Name][700]
* [MARC Code List for Relators][relators]

[700]: http://www.loc.gov/marc/bibliographic/bd700.html
[relators]: http://www.loc.gov/marc/relators/relacode.html

**Comment by lnielsen** [comment]
Almost :-) 

Instead we should use the DataCite list of contributor types:

ContactPerson
DataCollector
DataCurator
DataManager
Distributor
Editor
Funder
HostingInstitution
Producer
ProjectLeader
ProjectManager
ProjectMember
RegistrationAgency
RegistrationAuthority
RelatedPerson
Researcher
ResearchGroup
RightsHolder
Sponsor
Supervisor
WorkPackageLeader
Other

and map each one to a MARC relator code.

**Comment by lnielsen** [comment]
Perhaps let's start with a subset of contributors. Talk IRL

**Comment by bouzlibop** [comment]
Mapping table proposition:

DataCite| MARC
------------|---------
ContactPerson | ?mdc	Metadata contact ?prc	Process contact
DataCollector | col	Collector
DataCurator | cur	Curator
DataManager | dtm	Data manager
Distributor | dst	Distributor
Editor | edt	Editor
Funder | fnd	Funder
HostingInstitution | his	Host institution
Producer | pro	Producer
ProjectLeader | ?led	Lead ?rth	Research team head
ProjectManager | ?pmn	Production manager ?stm	Stage manager 
ProjectMember | ?rtm	Research team member
RegistrationAgency | ?pma	Permitting agency
RegistrationAuthority | ?
RelatedPerson | ?
Researcher | res	Researcher
ResearchGroup | ?
RightsHolder | cph	Copyright holder
Sponsor | spn	Sponsor
Supervisor | ?dgs	Degree supervisor
WorkPackageLeader | ?led	Lead ?rth	Research team head
Other | oth	Other

**Comment by bouzlibop** [comment]
![second_iter](https://cloud.githubusercontent.com/assets/8625570/8203897/49f5346a-14e5-11e5-977e-5065c55e23f8.png)

**Comment by lnielsen** [comment]
DataCite| MARC
------------|---------
ContactPerson | ?mdc	Metadata contact ?prc	Process contact
DataCollector | col	Collector
DataCurator | cur	Curator
DataManager | dtm	Data manager
Editor | edt	Editor
Producer | pro	Producer
Researcher | res	Researcher
RightsHolder | cph	Copyright holder
Sponsor | spn	Sponsor
Supervisor | ths
Other | oth	Other
