### ISSUE TITLE
accounts: verification email is not being sent

### ISSUE THREAD

**Issue by bouzlibop** [zenodo/zenodo#275]
:heavy_multiplication_x:  verification email is not being sent after sign up
:heavy_check_mark: verification email is sent using `Send verification email` button from `/account/settings/profile`

**Comment by SR--** [comment]
Tried with two different emails, cannot get the verification email. Resend button produces no effect.

**Comment by myoung02** [comment]
If anyone is still having trouble with this, I found that using a different browser (specifcially chrome) solved the issues, and the email sent.
