### ISSUE TITLE
deposit: add language field

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#293]
- [x] Update the record JSONSchema and ES mapping with top-level ``language`` field.
- [x] Update Deposit REST API (JSON serialisers/deserialisers)
- [x] Update Records REST API (JSON serialisers)
- [x] Add to UI form (need to decide exactly where on how it should be displayed)
- [x] Update Deposit REST API documentation.
- [x] Format updates:
   - [x] DataCite (language field)
   - [ ] BibTeX (not clear if needed)
   - [x] CSL (not clear if needed)
   - [x] OpenAIRE JSON export needs to be updated.

**Comment by elaeon** [comment]
Hi,

About this issue, do you have some news?

**Comment by lnielsen** [comment]
We will be starting work on this during June.

--


- [ ] OpenAIRE JSON export needs to be updated.

**Comment by elaeon** [comment]
Hi,

This field will be ISO 639-3?, there are plans to include multiple language in a resource?
Thanks,

**Comment by lnielsen** [comment]
Right we're not planning to allow multiple languages mainly due to DataCite Metadata Schema only allows for one language.

http://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf (The primary language of the resource.)

**Comment by krzysztof** [comment]
On our side we will be storing ISO 639-3 (three-letter code). One caveat is that DataCite will receive ISO 639-1 (two-letter code). Former is a wider set, hence some less common languages will not be reported in DataCite format.

**Comment by slint** [comment]
Closed via #1299
