### ISSUE TITLE
records: add support for zotero "add to bib"

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#297]

**Comment by astrojuanlu** [comment]
Was this ever added? I see a button to import into Mendeley, but not into Zotero:

![Screenshot_2021-04-06 poliastro poliastro poliastro 0 14 0 (COVID-19 edition)](https://user-images.githubusercontent.com/316517/113671976-5ab62480-96b7-11eb-9308-c5d8fdc8f1bb.png)
