### ISSUE TITLE
Sharing (communities and get a link)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#33]
- [x] Get a link (i.e. confidential peer-review).
- [ ] Community sharing (i.e. view of closed access records).
- [ ] Community UI revamp

**Comment by myrmoteras** [comment]
@lnielsen any idea when this is available? Probably within a month form now, we'll have a publication that makes extensively use of zenodo and we hope we can use this to leverage more input.

**Comment by lnielsen** [comment]
Unfortunately quite a lot more delayed that initially anticipated. I think early March now.

**Comment by lnielsen** [comment]
Closing as more specific tasks have been reported.
