### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#34]
- [ ] Versioned DOIs (one global DOI pointing to all releases, and one DOI per version).
- [ ] Deposit UI and REST API support.
- [ ] Move to new documents module.
- [ ] Move storage backend.

**Comment by benmarwick** [comment]
Yep, me too, this and #41 would save a bit of confusion when working with multiple releases from the same repo.

**Comment by dhalperi** [comment]
:+1:

**Comment by fedorov** [comment]
Will this feature also support versioning of datasets? This would be really great, as would enable correction of the errors discovered in the submission, or augmenting with new items. Really like "Versioned DOIs (one global DOI pointing to all releases, and one DOI per version)."

Hope the "Jan-March 2015" roadmap holds!

**Comment by lnielsen** [comment]
Yes, it will support versioning of datasets, and it's indeed a common use case that issues are found during the paper submission process and needs to be corrected.

The Jan-Mar roadmap won't hold. We got quite delayed with some sharing features. These however just went into QA, so we'll be starting work on this task once we're back from Easter.

**Comment by fedorov** [comment]
Thanks for the clarification - looking forward!

**Comment by Daniel-Mietchen** [comment]
What are the current plans around implementing this?

**Comment by fedorov** [comment]
@Daniel-Mietchen I've been waiting for this too (as well as download statistics #52), and in the end switched to figshare that already implemented this feature: https://figshare.zendesk.com/hc/en-us/articles/203922158-Does-figshare-support-version-control-. Disappointed about how this project addresses the users' issues, they are probably severely understaffed.

**Comment by lstagner** [comment]
I need this feature for a code I am about to release. Is there a work around?

**Comment by lnielsen** [comment]
Versioning support will be available in autumn. The reason for the heavy delay is that we have had a serve set-back in our underlying repo platform which we've had to address. This has been going on since September, and we're nearly through the problems.

Only workaround for now is to use the *related identifiers* field with has new version/is previous version relationships.

**Comment by lstagner** [comment]
Will there be a way to change an existing DOI to a Versioned DOI without breaking any references? I suppose all it would require is to change what the current DOI points to.

**Comment by lnielsen** [comment]
Yes, we plan to make all existing DOIs into versioned DOIs. Besides updating the URL redirect, there's also an update to the metadata registered in DataCite so that the version relationship between DOIs is discoverable. The two DOIs ``10.1234/foo.v1`` and 10.1234/foo.v2`` is technically two different DOIs that has nothing to do with each other (i.e. without the metadata that describes their relationship, discovery systems we see this as two different digital objects).
