### ISSUE TITLE
guides: move existing static pages to new pages module.

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#340]

**Comment by bouzlibop** [comment]
- [ ] migrate faq page
- [ ] migrate features page
- [ ] migrate api page?

**Comment by bouzlibop** [comment]
API page changes proposal by @zdennis

>* if the intention for the sandbox is for developer testing and integration 
before going live it would be helpful to have it listed early on in the API 
docs (possibly even have all examples in the docs use the sandbox and have 
a section telling them how to go live in production).

>* the accordions on the API docs hamper doc usability because their content 
is not searchable on the page until you manually click to expand them.

**Comment by otron** [comment]
Here is a bash script that downloads the existing static pages from github and does the required conversion:
https://gist.github.com/otron/afd5db0f829901d27871

The conversion/migration process consists of:

* Inserting values for config references (e.g. `{{CFG.SITE_NAME}}` --> `Zenodo`.
* Removing non-config references `{{ }}` blocks.
* Replacing Jinja2 comments w/ HTML comments.

The converted pages' source then have to be manually entered into the pages module, __with source view mode enabled in the editor.__

**Comment by otron** [comment]
[This commit](https://github.com/otron/zenodo/commit/e8cee8f54c171c0b6e5980f081df09f5de213007) removes the existing static pages, which is required to allow requests to the static page URLs (`/faq`, `/api`, etc) to go through the pages module.
