### ISSUE TITLE
Issue: Facets overlap footer

### ISSUE THREAD

**Issue by LibrarPotter** [zenodo/zenodo#351]
Browser Chrome Version 43.0.2357.81 (64-bit)
Mac OS 10.10.3
Scenario: Go on zenodo. Make an empty search. Scroll to the bottom of the page.

![issue](https://cloud.githubusercontent.com/assets/7935142/8499590/d3bd0108-2194-11e5-99cb-e0ebdd98cad4.png)

**Comment by lnielsen** [comment]
Fixed with latest development version
