### ISSUE TITLE
IsCompiledBy related identifier support

### ISSUE THREAD

**Issue by zdennis** [zenodo/zenodo#354]
We're looking to use the `IsCompiledBy` relation type to link our code repository to the data it is publishing. It doesn't appear that Zenodo supports this yet as it's not listed in the [docs](https://zenodo.org/dev#restapi-rep-meta) as a known related identifier.

For the time being we're using `isSupplementTo` but it doesn't feel like it's the best fit. Any chance that `IsCompiledBy` is supported but not documented or is it on the roadmap? 

Currently when trying to use `IsCompiledBy`, `isCompiledBy`, or `IsCompiledby` I receive the following response:

```
HTTP post https://sandbox.zenodo.org/api/deposit/depositions/?access_token=*******
Request Headers: {"Accept"=>"application/json", "Content-Type"=>"application/json"}
Response Headers: {"Date"=>"Wed, 08 Jul 2015 21:01:01 GMT", "Server"=>"Apache", "Strict-Transport-Security"=>"max-age=31536000", "X-Sentry-ID"=>"135c8a72b11e4a55b964b5963c44a5db", "Set-Cookie"=>"session=385d87a2ee544bb687f8ace8e5c5d388; Secure; HttpOnly; Path=/, sessionstub=HTTPS; HttpOnly; Path=/", "Content-Length"=>"309", "Vary"=>"Accept-Encoding,User-Agent", "Content-Type"=>"application/json"}
Response Body:
{"status": 400, "message": "Bad request", "errors": [{"field": "related_identifiers-1", "message": "relation", "code": 10}, {"field": "related_identifiers-1-relation", "message": "Not a valid choice", "code": 10}, {"field": "related_identifiers", "message": {"relation": ["Not a valid choice"]}, "code": 10}]}
```

Thanks!

**Comment by mfenner** [comment]
Is there a reason that not all DataCite relation_types defined in the Metadata Schema are supported?

**Comment by bouzlibop** [comment]
@zdennis, currently we don't support `isCompiledBy` (only `related_identifiers` mentioned in api docs). I'm pretty sure it wont't be a problem to add it to supported `related_identifiers`, am I right @lnielsen?

@mfenner, as far as I know. We started with only some subset of all `relationType`s metnioned by DataCite for the sake of brevity.

**Comment by mfenner** [comment]
Thanks @bouzlibop. If you and @lnielsen agree that linking datasets to software is an important use case, and that `IsCompiledBy` is the appropriate relation_type, then please add it to the supported identifiers.

**Comment by lnielsen** [comment]
@mfenner The reason why not all relationships types added, is primarily for usability. It's pretty hard to choose between some of the relationship types (e.g. cites/references).

``isCompiledBy/compiles`` however makes perfect sense so I've added it in #372.

**Comment by mfenner** [comment]
Thanks! And I agree about `cites/references`, have run into this myself.

**Comment by lnielsen** [comment]
This is in production now.
