### ISSUE TITLE
deposit: xrootd investigation

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#359]
Investigate how to use xrootd-python binding: http://xrootd.org/doc/python/xrootd-python-0.1.0/

- [x] Install xrootd and be able to connect to EOS via CLI.
- [x] Determine library dependencies which needs to be installed on our nodes.
- [x] Install Python binding and make it connect to EOS.
- [ ] Authentication via Keberos key tab (https://kb.iu.edu/d/aumh): Below is a code snipped that shows you what you need to append to the url to use the krb5 or gsi:
```
    kerberos: &xrd.wantprot=krb5&xrd.k5ccname=/tmp/krb_filexxx
```
- [ ] Make a proper Pythonic package out of xrootd-python binding so we can install it with pip (``python setup.py sdist`` creates a package that cannot be installed, likely due to MANIFEST not being specified).
- [ ] PyFilesystem integration (http://docs.pyfilesystem.org) similar to the S3 interface.

**Comment by lnielsen** [comment]
Possibly you need to do this via launching a CC7 Extra image on openstack.cern.ch (http://clouddocs.web.cern.ch/clouddocs/details/standard_images.html)

**Comment by lnielsen** [comment]
This seems to be the dependencies for CC7 Extras image:
```
yum install xrootd-client xrootd-client-devel
yum groupinstall 'Development Tools'
yum install git virtualenv
```

I haven't managed to install it on OS X yet.

Once installed, this can be used to test:
```python
from XRootD import client
from XRootD.client.flags import DirListFlags

# Without authentication
client.FileSystem('root://eospublic.cern.ch/).dirlist('/eos', DirListFlags.STAT)
# WIth:
client.FileSystem('root://eospublic.cern.ch/?xrd.wantprot=krb5&xrd.k5ccname=/root/user.keytab').dirlist('/eos', DirListFlags.STAT)
```

**Comment by otron** [comment]
Couldn't get `python setup.py sdist` to work on lxplus (`error: Invalid cross-device link`), though it worked fine on my mac.
