### ISSUE TITLE
search: finding articles on Zenodo

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#375]
how can we find articles deposited in Zenodo? The search function does not work (eg for Revision of African Apiocera (Diptera: Apioceridae), and we need an API to check whether an article is already in Zenodo. This does not work in most cases.

For our machine based search function we need this to assure too: http://refindit.org to automate batch uploads.

**Comment by lnielsen** [comment]
It seems to have troubles with the special characters if you search for either:

``title:"Revision of African Apiocera (Diptera: Apioceridae)"``

or 

``Revision of African Apiocera Diptera Apioceridae``

It finds the article.

**Comment by myrmoteras** [comment]
once again: if you search for  "Farkač" I only get one article.

What exactly does the search function do? Is it a full text search? Does it only search certain fields?

**Comment by lnielsen** [comment]
It's not a full text search. It only searches metadata. Our search engine will be replaced with native Elasticsearch in the upcoming release which should hopefully resolve these issues.

**Comment by myrmoteras** [comment]
Hi Lars

Is there a reason that I am getting now different search results as I got this morning: For example, I entered “revue Suisse de Zoologie 122” and got all the articles for the issue 122 (1 and 2), but now I only get those for issue (1). A problem might be that I only get 10, and then it stops. After I reloaded, I am getting all of them…

Cheers
Donat

**Comment by lnielsen** [comment]
Solved by sep 12 update
