### ISSUE TITLE
formatter: contributors included alongside with authors in brief view

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#387]
the search results window https://zenodo.org/search?ln=en&p=Revision+of+the+ant+genus+Myrmoteras+in+the+Malay+Archipelago+&action_search= displays the results in an unexepected way

     Revision of the ant genus Myrmoteras in the Malay Archipelago (Hymenoptera, Formicidae).
     Agosti, D. ; Cora, Joe ; Johnson, Norm

This reads, as if Cora and Johson are authors of the publication. Which they are not, 

see the window for the article https://zenodo.org/record/27078?ln=en#.VctuGPmqpBc 

     Revision of the ant genus Myrmoteras in the Malay Archipelago (Hymenoptera, Formicidae).
     Agosti, D.

     (show affiliations)

     Data Curator(s):
     Cora, Joe

     Editor(s):
     Johnson, Norm

Here the function of the Cora and Johnson are clear. Is it possible to change the search results page, so that the data curator and editor are not shown?

Thanks

Donat

**Comment by bouzlibop** [comment]
I see your point and I've prepared some solution for that. First I need to consult it with @lnielsen and hopefully will get back to you tomorrow.

**Comment by bouzlibop** [comment]
Two related PRs were opened correspondingly in `zenodo/invenio` and `zenodo/zenodo`, which must be applied simultaneously.
