### ISSUE TITLE
Zenodo: BLR: list of uploads

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#388]
I was querying the Zenodo API in an attempt to obtain a list of all the depositions associated with Plazi's BLR admin account. The result was some waiting time (so it looks like there was something happening behind the API), and then an HTTP 504 Gateway Timeout response.

I tried this from my own machine first, and then via wget from one of the Plazi servers, in case my local web connection was the one causing the timeout. But the timeouts continued to occur.

So, could you have a look at your logs to shed some light? The last attempt was from IP address 158.121.253.11 (plazi.cs.umb.edu) at 21:21 CEST today, Aug 10th, 2015, returning the error response 21:22:52 that date.

**Comment by lnielsen** [comment]
Fully fixed in new version
