### ISSUE TITLE
H2020 funding info in zenodo metadata

### ISSUE THREAD

**Issue by joschirr** [zenodo/zenodo#400]
Are zenodo metadata (oai_dc and oai_datacite) prepared to record H2020 grant agreement strings?

I found a record in zenodo that relates to a H2020 project in dc:description but is without
info:eu-repo/grantAgreement/EC/H2020 ... in dc:relation!

https://zenodo.org/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:zenodo.org:22615

**Comment by lnielsen** [comment]
Not yet. We still need to import the h2020 grants and make them available to end-users

**Comment by lnielsen** [comment]
This is being deployed in production on Monday.
