### ISSUE TITLE
Request: display the ORCID identifiers of authors

### ISSUE THREAD

**Issue by wetneb** [zenodo/zenodo#401]
It is possible to give ORCID ids to paper authors using the API.
For instance, "Pablo E. Schilman" was given an ORCID in the following record:
https://sandbox.zenodo.org/record/392#

It would be nice if this information was available on the webpage (for instance as an affiliation).
It is already taken into account in the DataCite export:
https://sandbox.zenodo.org/record/392/export/dcite3

The metadata submitted to Zenodo was:
<pre>
{
    "metadata": {
        "doi": "10.1016/s0001-706x(01)00095-x", 
        "description": "It has been observed that Triatoma infestans and Rhodnius prolixus females stridulate to reject copulatory attempts performed by males. In addition, triatomines stridulate when disturbed or handled. In the present study, the temporal structure and frequency spectra of vibrational signals produced by mechanically disturbed T. infestans, T. sordida, T. guasayana, R. prolixus and Dipetalogaster maxima were analysed and compared. The inter-ridge distances of the prosternal stridulatory organ of the same species were also measured. The frequency spectra and repetition rates were similar, despite individuals of these five species have different sizes, their stridulatory grooves have different inter-ridge distances, and also their vibratory signals exhibited different temporal patterns. The hypothesis that disturbance stridulations are non-specific signals and could function to deter predators was discussed.", 
        "license": "cc-by", 
        "title": "Comparison of disturbance stridulations in five species of triatominae bugs", 
        "journal_title": "Acta Tropica", 
        "journal_pages": "171-178", 
        "journal_volume": "79", 
        "upload_type": "publication", 
        "publication_date": "2001-05-01", 
        "creators": [
            {
                "orcid": "0000-0003-1485-1650", 
                "name": "Schilman, Pablo E."
            }, 
            {
                "name": "Lazzari, Claudio R."
            }, 
            {
                "name": "Manrique, Gabriel"
            }
        ], 
        "journal_issue": "2", 
        "publication_type": "article"
    }
}
</pre>

**Comment by lnielsen** [comment]
If an ORCID exists for a creator it will now be displayed next to the name. See e.g. https://sandbox.zenodo.org/record/18401

**Comment by wetneb** [comment]
@lnielsen: Fantastic! Keep up the excellent work!

**Comment by lnielsen** [comment]
@wetneb Just in case you haven't seen it yet: https://github.com/zenodo/zenodo/wiki/Planned-intervention - if you experience any problems with the REST API don't hesitate to open a GitHub issue or shoot us an email on info@zenodo.org. We'll be on standby for fixing urgent integration issues after the big migration on Monday.

**Comment by wetneb** [comment]
@lnielsen: Got it, I'll monitor how things go on our side. Thanks a lot!
