### ISSUE TITLE
previewer: zip preview not appearing on specific record

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#412]
https://zenodo.org/record/33466

**Comment by lnielsen** [comment]
Fixed via new Invenio-Previewer.

**Comment by nschorgh** [comment]
I have the same problem.
http://zenodo.org/record/48851

**Comment by lnielsen** [comment]
We have a larger update coming out early May where this is fixed. For now the problem is fixed in the code, so stay tuned for the update.
