### ISSUE TITLE
authors: input format

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#413]
Are there any rules how to format the affiliation of an author? Do you want to enter also emails if they are provided in the articles?  

e.g. Muséum d’histoire naturelle, C.P. 6434, CH-1211 Genève 6, Switzerland. E-mail: john.hollier@ville-ge.ch 

What about ORCID?

![image](https://cloud.githubusercontent.com/assets/4609956/11037132/842f551e-86fc-11e5-8fc7-65ae134f2742.png)

**Comment by lnielsen** [comment]
Currently the format is as in the help text. ``Family name, Given names``. Exception is that it can also be organisational names. ORCID/GND support is only available in the API and there's not support for registering email addresses.
