### ISSUE TITLE
migration: records export api

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#421]
- Export API
  - REST API must support exporting in: 
    - [x] JSON
    - [ ] BibTeX
    - [x] DataCite
    - [x] Dublin Core
    - [x] MARCXML
    - Remove EndNote, NLM, RefWorks, MARC
  - [ ] UI must support display record export from API (small angular app).

**Comment by switowski** [comment]
Create a sub-task for each of the packages.
Start with MARCXML package.
