### ISSUE TITLE
migration: oauthclient

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#436]
URLS

- [x] /oauth/authorize
- [x] /oauth/authorized//
- [x] /oauth/disconnect//
- [x] /oauth/errors/
- [x] /oauth/info/
- [x] /oauth/invalid/
- [x] /oauth/login//
- [x] /oauth/ping/
- [x] /oauth/signup//
- [x] /oauth/static/
- [x] /oauth/token
- [x] /account/settings/linkedaccounts/
- [x] /account/settings/linkedaccounts/static/

- [ ] Migration of existing tokens (encryption?)

**Comment by lnielsen** [comment]
@krzysztof Similar I think this one can be closed because of https://github.com/inveniosoftware/invenio-migrator/commit/87b3f766a31d16337cc38c1804e885f80468929d ?

**Comment by krzysztof** [comment]
@lnielsen yes
