### ISSUE TITLE
Internal Server Error upon trying to upload

### ISSUE THREAD

**Issue by kyleniemeyer** [zenodo/zenodo#445]
I'm getting Internal Server Errors when trying to upload software releases that came from GitHub. I'm at the stage after publishing a release, at the "Upload" page on Zenodo. I have two releases I'm currently trying to upload, and I'm getting the error on both. I first tried last night (~12 hours ago) and now again this morning, and I'm seeing the same error.

This appears similar to the (closed) issue #213.

**Comment by kyleniemeyer** [comment]
Well, this seems to have resolved itself—my unsubmitted uploads now show up as submitted.

**Comment by lnielsen** [comment]
@kyleniemeyer Unfortunately due CERNs annual closure most staff was away on leave, which caused the long reaction time from our side. Apologises for the inconvenience it have caused.
