### ISSUE TITLE
upload date / prereserved doi

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#447]
For new articles, we prereserve a DOI so that the DOI can be added to the respective article
![image](https://cloud.githubusercontent.com/assets/4609956/12258000/8835ee84-b90b-11e5-937b-bf076931fefe.png)

So, the upload date should correspond with the publication date, or at least with the date, when the respecitive article is uploaded (either 12/31/2015 - publication date or 1/11/2016 upload of the final article, replacing the dummy article uploaded when reserving the DOI on Nov 19, 2015). However, in the display this is not the case

![image](https://cloud.githubusercontent.com/assets/4609956/12258058/f506941e-b90b-11e5-9f9f-e5ac001675f1.png)

This is confusing, since in taxonomy the date of publication is relevant, and thus we need to figure out that the respective date (publication, or upload of the final article) is displayed.

**Comment by lnielsen** [comment]
I think this might have been fixed with the new version, since the upload date is the record creation date which should be the day you press the "publish" button.
