### ISSUE TITLE
search functionality

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#448]
Why does the search function not deliver all the articles? E.g. searching for "Löbl" shows only one article, 

![image](https://cloud.githubusercontent.com/assets/4609956/12258140/9b876110-b90c-11e5-97e3-77cd7432b274.png)

not two, the one above as well as this one http://dx.doi.org/10.5281/zenodo.34001

**Comment by lnielsen** [comment]
This is working properly now in the sandbox: https://sandbox.zenodo.org/search?page=1&size=20&q=creators.name:Löbl
