### ISSUE TITLE
tests: jasmine + selenium testing

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#46]

**Comment by otron** [comment]
Status:
minimal flask app w/ a simple selenium test in a repo integrated with Travis-CI: https://github.com/otron/flask-travis-selenium-minimality
The test runs on Travis (https://travis-ci.org/otron/flask-travis-selenium-minimality)

Jasmine? Haven't started looking into it yet.

**Comment by lnielsen** [comment]
Closed via 45354f6512b99091d0fd22c7e430770b9644a0aa
