### ISSUE TITLE
previewer: limit previews of zip files with many files inside

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#465]
https://zenodo.org/record/46392

**Comment by lnielsen** [comment]
Fixed via inveniosoftware/invenio-previewer#8

**Comment by Herrner** [comment]
Would it be difficult to tell why files cannot be previewed? Especially if the reason is size?

**Comment by lnielsen** [comment]
In this case, it will say in the top that not all files in the zip is being displayed.

**Comment by Herrner** [comment]
I mean records like this one: https://zenodo.org/record/2547325

**Comment by lnielsen** [comment]
That's a bug which throws an exception and thus the error message is not very informative. The bug is https://github.com/inveniosoftware/xrootdpyfs/issues/85

**Comment by lnielsen** [comment]
Not the bug only exists on Zenodo because we use XRootD protocol to access our storage system.
