### ISSUE TITLE
setup: Docker recipe for Zenodo demosite on Linux

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#479]
## Description

Zenodo docker installation guide (http://zenodo.readthedocs.org/en/latest/installation.html#docker-installation) doesn't seem to work on Linux systems.

The ``web`` node in docker-compose fails with the following error:
``web_1      | pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application``

As far as I have gotten to finding the problem was to find out that the docker-compose ``static`` node doesn't mount the ``./code`` properly. Thus, all nodes that read the volumes from ``static``, i.e. nodes ``web``, ``worker`` and ``frontend`` will fail:
```
web:
  (...)
  volumes_from:
    - static
```

I was able to reproduce the problem on Ubuntu 15.04 and Archlinux (~03.2016) using newest ``docker-machine`` and ``virtualbox`` from package repositories.

## Tasks

- [ ] Fix the docker recipe so it works on Linux machine
- [ ] Confirm that it still works on OSX

**Comment by ddaze** [comment]
The problem with `web_1 | pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application` is that the local src folder is 'mounted' into the Docker container
with the volume option in the docker-compose.yml file.
And with that the needed `zenodo.egg-info` folder is not existing.
