### ISSUE TITLE
testing: test validation of record jsonschemas and ES mappings

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#481]
JSONSchemas for record metadata, as well as elasticsearch mappings should be tested.

The unit tests should simply create some rich examples for all record types used in Zenodo and make sure the validation is passing/not-passing where expected.

**Comment by rajat1994** [comment]
@krzysztof ... i'd like to work on this issue..could you please tell which files do i need to look for?

**Comment by krzysztof** [comment]
This involves first getting familiar with the Zenodo metadata model, which is described (and validated) using JSON Schema, here: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/jsonschemas/records/record-v1.0.0.json

This model describes structure and some required fields for Record's metadata.

This schema is just for the record (*record* is sometimes referred to as *published* record on Zenodo). There are two other important schemas:
- Deposit (unpublished record): https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/jsonschemas/deposits/records/record-v1.0.0.json
- "Legacy" Deposit, which is an older version of Deposit schema (we need to keep this for old REST API compatibility): (https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/jsonschemas/deposits/records/legacyrecord.json)

The task is to:
1) Define some minimal/exhaustive test metadata for record (some are already in the conftest), deposit and legacy deposit according with the schema specification
2) Validate it according to their corresponding schemas

Having unit tests like these protects from introducing "breaking" changes to the schema w.r.t. structure and "required" fields.

For start there are already two "minimal" and "full" test metadata fixtures:

https://github.com/zenodo/zenodo/blob/master/tests/unit/conftest.py#L316-L329
https://github.com/zenodo/zenodo/blob/master/tests/unit/conftest.py#L406-L548

And there are even tests which test the "minimal" metadata constraints:
https://github.com/zenodo/zenodo/blob/master/tests/unit/records/test_schemas.py#L36-L38

At first it would be good to add similar validation for full_record fixture.

**Comment by rajat1994** [comment]
@krzysztof ..... i have validated some of the parameters of Deposit schema. Could you please check?
Link of gist :  https://gist.github.com/rajat1994/be2dea187460b2ed621419d55ca7bae4

**Comment by krzysztof** [comment]
Hey @rajat1994,

That would be the general idea for task, however:

1) You don't have to define your own schema - Zenodo already has some defined as I mentioned above.
2) Instead of using "validate" from jsonschemas, use the Record.create method to create. Internally the metadata will be validated according to the schema referred-to by the '$schema' value. The test should look like the ``test_minimal_json`` test above, just using full_record metadata fixture.
3) Add this to unit tests and create a PR.
