### ISSUE TITLE
records: finish marcxml mapping

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#501]
See #500 

Full marc example: 
https://github.com/zenodo/zenodo/blob/production/zenodo/base/testsuite/test_jsonext.py#L31-L206

**Comment by hachreak** [comment]
fields:
- [ ] 024
- [ ] 035
- [ ] 100
- [ ] 245
- [ ] 260
- [ ] 347
- [ ] 500
- [ ] 520
- [ ] 536
- [ ] 540
- [ ] 542
- [ ] 650
- [ ] 653 @hachreak
- [ ] 700
- [ ] 711
- [ ] 773
- [ ] 909
- [ ] 970
- [ ] 980
- [ ] 999
