### ISSUE TITLE
stats: expose metrics via records rest api

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#52]

**Comment by lnielsen** [comment]
Possibly support download per date as well.

**Comment by moorepants** [comment]
It would be great to see download counts for our shared items. A vote from me!

**Comment by fedorov** [comment]
+1

I would also consider reporting geo locations with counts (without exposing IPs, of course).

See example how we do this for our internal publications database: http://www.spl.harvard.edu/publications/statistics/?midasid=2037

Also see another example of reporting statistics for software downloads:
http://download.slicer.org/download-stats/

**Comment by lnielsen** [comment]
@fedorov Thanks a lot for the examples and ideas. We'll try to see if we can make it possible.

**Comment by fedorov** [comment]
It's unfortunate this issue is not even on the road map anymore.

**Comment by lnielsen** [comment]
@fedorov We're quite low on man-power right now, and we're focusing on getting some core stability issues fixed first as it impacts all the rest of the operation. On top of that, we've been having to deal with very persistent human spammers which have also taken up resources. From October 1st we'll be having more hands, and we will be making progress much faster including on providing download stats.

**Comment by fedorov** [comment]
with all due respect, my next dataset goes to figshare

![image](https://cloud.githubusercontent.com/assets/313942/10514810/12a41660-731e-11e5-85fa-1ba76fcad9f6.png)

**Comment by slint** [comment]
Closed via #1538
