### ISSUE TITLE
deposit: tests - migrate file operations tests

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#543]
https://github.com/zenodo/zenodo/blob/production/zenodo/modules/deposit/testsuite/test_zenodo_api.py#L83-L248

**Comment by lnielsen** [comment]
Use this pattern:
https://github.com/inveniosoftware/invenio-deposit/blob/master/tests/test_views_rest.py

**Comment by hachreak** [comment]
I think this issue i closed by by https://github.com/inveniosoftware/invenio-deposit/commit/86a127e925edc4868dd63b2c9042674854c656a6 ?
