### ISSUE TITLE
PDF viewer

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#551]
There is an issue with the current pdf viewer that parts of the pdf are not properly shown

original.
![image](https://cloud.githubusercontent.com/assets/4609956/14976153/85479208-1109-11e6-8228-2bd6a1723c4b.png)

Zenodo-viewer

![image](https://cloud.githubusercontent.com/assets/4609956/14976175/a3402ee6-1109-11e6-9124-aef613c07ed3.png)

http://dx.doi.org/10.5281/zenodo.50824

**Comment by lnielsen** [comment]
Thanks for the report. I'm quite sure we have it fixed in the new sandbox, but I'll check it once we load the record in the next production dump.

**Comment by lnielsen** [comment]
This problem have been fixed by an update of PDF.js - see https://sandbox.zenodo.org/record/50824
