### ISSUE TITLE
deposit: legacy schema fields need to implement

### ISSUE THREAD

**Issue by hachreak** [zenodo/zenodo#570]
We shound implement some missing fields on deposit legacy schema:
- [ ] deposit['files']
- [ ] deposit['state']

**Comment by lnielsen** [comment]
https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/schemas/legacyjson.py#L225-L239

Implement in particular these attributes:
- ``submitted``: (True if deposit is published)
- ``state``: ``"inprogress"`` if in draft mode else ``"done"``.

**Comment by hachreak** [comment]
in the quickstart we have also `'state': u'unsubmitted'`.
How we should handle it?
