### ISSUE TITLE
zenodo service unavailable

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#601]
Over the last three days, this often happened

![image](https://cloud.githubusercontent.com/assets/4609956/15983983/46e56f1a-2fba-11e6-9942-e22d8d586659.png)

**Comment by lnielsen** [comment]
This should have been resolved by now.

**Comment by ayssi** [comment]
Hi all,
I stil have that ertor
![zenodo_issue](https://user-images.githubusercontent.com/7836892/65391657-8981d980-dd63-11e9-802d-aba6265252ed.png)
