### ISSUE TITLE
deposit: race conditions with REST calls

### ISSUE THREAD

**Issue by lomigmegard** [zenodo/zenodo#627]
Hi, 

I was testing the new sandbox with automated integration tests and I was surprised to get strange results non-deterministically. 

My test is calling the following endpoints in order, waiting the response from each call before continuing. Note that sometimes it fails with shorter chains, or directly at the second call.
- POST https://sandbox.zenodo.org/api/deposit/depositions?access_token=xxx
- PUT https://sandbox.zenodo.org/api/deposit/depositions/55501?access_token=xxx
- POST https://sandbox.zenodo.org/api/deposit/depositions/55501/files?access_token=xxx
- POST https://sandbox.zenodo.org/api/deposit/depositions/55501/actions/publish?access_token=xxx

The error is a 403 code with message

    You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

The tests are all perfectly working when I add a small sleep between each calls. 

Can you tell me if this is a know issue, and how to address it?

**Comment by lnielsen** [comment]
@lomigmegard Thanks for the report. It's a known issue. You currently need to implement a 1-2 secs delay after the first POST request. We will get rid of this prior to launch. The 1-2 seconds delay is the time it takes for Elasticsearch to make the record available in a given index.

**Comment by lomigmegard** [comment]
Thanks for the response. I will add a small sleep after the first POST then. 

Please let us know when this is fixed (HBP-BBP SP5 team).

@samuel-kerrien FYI

**Comment by lnielsen** [comment]
We've deployed a fix now, so you should no longer experience the 403 errors.

**Comment by lomigmegard** [comment]
Thanks, tested on my side.
