### ISSUE TITLE
deposit: file checksum prefix

### ISSUE THREAD

**Issue by lomigmegard** [zenodo/zenodo#628]
My old integration test that was working on the old sandbox (the current prod) is failing due to an unexpected "md5:" prefix to the checksum value of deposition files. 

Can you tell me if it's a bug? If it's not, it should be reflected on the documentation and it means the API is **not backward compatible**. I would personally prefer the value without the prefix.

**Comment by lomigmegard** [comment]
@samuel-kerrien FYI

**Comment by lnielsen** [comment]
It's a bug in some of the file serialisations methods and will be fixed. MD5 checksums will be reported without the prefix ``md5:``.  We have revamped the internal store to add support for other checksum algorithms, and *may* propagate this change to the REST API in the future (with proper deprecation notice of course). For now however we stay with MD5.
