### ISSUE TITLE
Generating short-living token programmaticaly

### ISSUE THREAD

**Issue by lomigmegard** [zenodo/zenodo#662]
Hi, 

We discussed with Tom a few months ago regarding the possibility to have an API to manage tokens. We would like to know the status of this feature.

Our use case would be to allow access to private files to specific users (that don't have a Zenodo account). The idea was to generate an expiring token (using our master token) and to build with it a valid URL that can be used for a short amount of time. 

Do you think this is reasonable? Do you foresee any other solution? 

Also on what technology the authentication and authorization are based? Is there a way to have a deeper integration with it?

Thanks! 

Lomig, on behalf of the HBP-NIP team.

**Comment by lnielsen** [comment]
Dear Lomig,

We unfortunately can't start the feature until we have launched the new version of Zenodo. Once we have release the new version, will provide a road map with expected launch dates.

The token generation and validation already exists in [zenodo/zenodo-accessrequests](https://github.com/zenodo/zenodo-accessrequests/blob/master/zenodo_accessrequests/models.py#L58) so we just need to expose it via a REST API. I.e. technically it is not very difficult (~1 week).

The method generates an encrypted JSON Web Token which holds all authentication information as well as an expiry date.

Cheers,
Lars

**Comment by lomigmegard** [comment]
Thanks Lars for the quick response.

This is good news for the future. Do you have an ETA for the new version of Zenodo?

Thank you again.
Lomig

**Comment by lnielsen** [comment]
We've been pretty bad so far for giving reliably estimates so better I don't give any dates. We are near feature complete and are just testing and polishing features the last bits. Afterwards we will deploy a full production dump to the sandbox and have a short verification period to ensure that the migration will go smoothly.

After the launch we will also work hard to provide reliable time estimates for future features.
