### ISSUE TITLE
auth: AAI authentication (eduGAIN)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#67]

**Comment by Edugate** [comment]
What is the current status of this enhancement, it seems to be have been targeted for September and then removed from the road map??

**Comment by lnielsen** [comment]
It's targeted for spring/summer now. We unfortunately have some issues in the underlying infrastructure that we've had to focus all attention on, and thus drop the regular road map until solve. We hope to be through this soon and will launch a revamp either before Christmas or right after New Year.
