### ISSUE TITLE
deposit: ui form styling

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#671]
- [x] Actions bar in top + bottom. (Save, Delete) `S`
- [x] Resource type: remove description, check if all icons can be on one line. `M`
- [x] Missing field titles: e.g. books. `S`
- [x] Check required fields red-star mark. `S`
- [x] Check placeholder texts (e.g. authors). `S`
- [x] Check icons for all fields. (ui-select form elements have an unconfigurable template...) `S`
- [x] Check panels a) optional vs required b) open vs closed c) titles. `S`
- [x] Panels descriptions should go out of panel header and into body - e.g. communities. `M`
- [x] help text/description text in small. `S`
- [x] Remove field description in right column. `S`
- [x] Authors: remove help text. `S`
- [x] Authors: Match style of "Add author". `M`
- [x] Contributors: subfield on one line. `S`
- [x] Thesis is missing. `M`
- [x] Related identifiers: relations list should match reduced set from zenodo, hide scheme. `M`
- [x] Array/List fields: remove box around. `M`
- [x] Funder field - ~~funder + grant~~ - by default set to European Commission. `L`
- [x] Fix sortable lists (requires https://github.com/angular-ui/ui-sortable and sortOptions). `L`
- [x] Publication date/embargo date: date selector ([datepicker](https://github.com/Textalk/angular-schema-form-datepicker)) `M`
- [x] Select/Checkbox default values (can only be set in the deposit jsonschema). `M`
- [x] Add enhanced Markdown editor to Description ([ckeditor](https://github.com/webcanvas/angular-schema-form-ckeditor)) `L`
- [x] References: see if textarea field can be used, and process/split lines aferward. Use array list instead. `M`
- [x] License: placeholder text (click and type...), default to CC-BY-4.0, ~~if dataset CC0-1.0~~. `L`
- [ ] ~~Pre-reserve DOI button-click~~ Use ``{'metadata': {'prereserve_doi': {'doi' : ....}}}`` and add it to DOI on 'Save'.  `L`

**Misc enhancements**
- [x] Override/overwrite templates from other modules.
- [ ] Validation styling for all types of fields (green/tick, red/cross)

**Comment by lnielsen** [comment]
Can you check alignment of the form as well. Probably just a ``<div class="container">`` missing somewhere:

Correct:

<img width="438" alt="screen shot 2016-08-05 at 15 41 22" src="https://cloud.githubusercontent.com/assets/1698163/17438490/5df0ee5c-5b23-11e6-88ff-5a8dccf150bb.png">

Incorrect:
 
<img width="303" alt="screen shot 2016-08-05 at 15 40 24" src="https://cloud.githubusercontent.com/assets/1698163/17438486/5bd01f94-5b23-11e6-8ef8-81d167f52eef.png">

**Comment by lnielsen** [comment]
- [ ] Authors/contributors/thesis supervisors placeholder: ``Family name, Given names`` (mistake in production form)
