### ISSUE TITLE
Deposit API: 500 errors

### ISSUE THREAD

**Issue by wetneb** [zenodo/zenodo#681]
From Dissemin's logs:
<pre>
### Checking the access token
--- Request to https://zenodo.org/api/deposit/depositions?access_token=*****
Status code: 200 (expected 200)

### Creating a new deposition
--- Request to https://zenodo.org/api/deposit/depositions?access_token=*****
Status code: 201 (expected 201)

Deposition id: 143433
### Uploading the PDF
--- Request to https://zenodo.org/api/deposit/depositions/143433/files?access_token=*****
Status code: 500 (expected 201)

Server response:
{"status": 500, "message": "Internal Server Error"}
</pre>

The user tried to upload twice in a row (09:58 and 10:01 UTC+2) and both failed in the same way. I can provide (privately) the PDF file they tried to upload if it can help you debug.

**Comment by krzysztof** [comment]
We have had a temporary issue with our system, can the user try to upload the file again? If it still errors, they should try to upload the file under a new deposit.

**Comment by wetneb** [comment]
Hum, I do not know this user and Dissemin does not store any email
addresses, so it will be hard for me to run after them. But thanks for
the quick reply anyway!
