### ISSUE TITLE
openaire: update RCD communities

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#738]
Phase 1:
- Create community for openaire EGI community
- Export community identifier in DC\

Phase 2:
- Reserve namespace for openaire communities
- Export community creation via rest api

**Comment by krzysztof** [comment]
@lnielsen Requires better explanation

**Comment by dnet-team** [comment]
Was this for us?

Lars, let us know if you need any clarification. 

Paolo

----
Paolo Manghi
Istituto di Scienza e Tecnologie dell'Informazione "A. Faedo" - CNR
Tel: +39 050 315-2038 - Fax: +39 050 315-3464
Web: http://www.isti.cnr.it/People/P.Manghi
InfraScience Research Group: http://nemis.isti.cnr.it/groups/infrascience

**Comment by lnielsen** [comment]
@dnet-team No it's for me :-)

**Comment by alessiabardi** [comment]
Hi Lars,

please find attached the list of openaire-connect communities.
The file is a csv with three columns:
1. communityid: string that identifies a community in OpenAIRE. This is the value to use to link a product to an OpenAIRE community.
2. communityname: the name of the community (for display purposes)
3. zenodo communities: a ';' separated list of zenodo communities that can be mapped into the OpenAIRE community. The mapping is of course preliminary (I made a very basic search among the Zenodo community). If you know about other communities that should be mapped, feel free to enrich the csv and let me know.

If you think it is worth it, feel free to add the csv to github. 

[openaire-zenodo_communities_2017-10-24.csv.txt](https://github.com/zenodo/zenodo/files/1411332/openaire-zenodo_communities_2017-10-24.csv.txt)

**Comment by paolomanghi** [comment]
We should add a prefix to the communities above, of the likes:

OpenAIRE-Connect - <community name>

Any other suggestion is welcome.

**Comment by krzysztof** [comment]
Mapping translation from the CSV file to Google docs: https://docs.google.com/spreadsheets/d/1L3ZK8hvsgjHF-q50fog3fyZBY7FhF7NzzE83BTDvZJ8/edit#gid=0

**Comment by mirima2** [comment]
Hi all,

To the csv file should be added one entry related to the new communit Instruct-ERIC:

OpenAIRE_ID: eric; 
OpenAIRE_name: Instruct-ERIC; 
Zenodo_ID: Instruct, West-Life Virtual Research Environment for Structural Biology

**Comment by alessiabardi** [comment]
Hi @krzysztof ,

we have some updates on the OpenAIRE/Zenodo communities. We cannot edit the google doc, so I am attaching an updated csv file.
[openaire-zenodo_communities_2018-03-09.csv.txt](https://github.com/zenodo/zenodo/files/1797528/openaire-zenodo_communities_2018-03-09.csv.txt)

**Comment by alessiabardi** [comment]
Sorry, the correct csv is the one attached here
[openaire-zenodo_communities_2018-03-09_fixed.csv.txt](https://github.com/zenodo/zenodo/files/1797680/openaire-zenodo_communities_2018-03-09_fixed.csv.txt)

**Comment by mirima2** [comment]
Hi @krzysztof,

another update for the communities in the attached file
[openaire-zenodo_communities_2018-04-27.txt](https://github.com/zenodo/zenodo/files/1955652/openaire-zenodo_communities_2018-04-27.txt)

**Comment by slint** [comment]
Closing, as RCD communities have been updated via the latest file and the workflow for updating them in the future has been agreed to be done via the official support line by selecting the `OpenAIRE` category.
