### ISSUE TITLE
deposi: /deposit/:id should show error message if deposit is not in edit mode

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#764]

**Comment by guptavaibhav18197** [comment]
@lnielsen I would like to go about fixing this issue.
Can you please provide some more details of the enhancement, and the reference to where the related code resides?

**Comment by krzysztof** [comment]
Or better - it should just open the deposit for editing just like POST to the record.

**Comment by krzysztof** [comment]
Fix has been integrated here https://github.com/zenodo/zenodo/pull/1241

The solution is to change the state of deposit to editable when the deposit page is opened.
