### ISSUE TITLE
GitHub integration issues (internal server error)

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#772]
- [x] ~~DOIs are not being minted for GitHub releases.~~
- [x] ~~If you previously have made GitHub releases with automatic archiving in Zenodo, you will get Internal Server Error when you a viewing you the details for a specific GitHub repository~~
- [ ] Some existing DOI badges are currently giving 404 Not found errors.

**Comment by montesi** [comment]
New user here, so no "previously have made GitHub releases with automatic archiving in Zenodo". I get a Internal Server Error when trying to connect to GitHub from my Zenodo account.

**Comment by krzysztof** [comment]
@montesi Can you please try again now - you should be able to connect your Zenodo account properly.

**Comment by montesi** [comment]
Thanks, it's working!

**Comment by krzysztof** [comment]
Pre-migration GH releases are now being displayed correctly.

**Comment by DemetraDanae** [comment]
Hello! I have recently got a doi number for my project in GitHub but when I click on it, I get a "DOI Not Found" error. I can see that this is one of your known issues. My question is can I use this doi as a reference or after fixing this issue I'll have to get a new doi?

**Comment by krzysztof** [comment]
@DemetraDanae Yes, your DOI is safe to use as is, once we have fixed other issues it will resolve by the URL (hopefully later this week).

**Comment by cpicanco** [comment]
Hi, any news about the issue? error id c63ea9c29f834b75a0ba50d7f06123d9

**Comment by DemetraDanae** [comment]
Hello again! I would like to know if there are any news for the DOI Not Found error for the dois related to GitHub repositories. I still have a problem with mine and I was wondering if this problem is still a general issue.

Thanks in advance

**Comment by JasperHG90** [comment]
Hello,

I wasn't sure where to turn with this issue, but I'm experiencing a similar problem. The GitHub integration 'works' in that a new release triggers a new DOI. I copy-pasted the badge and added it to my README.md. However, if you try to go to the web page, you see the following error.

![image](https://user-images.githubusercontent.com/8079803/51683701-bb7f4800-1fea-11e9-8378-811f67973ed4.png)

Repository in question: https://github.com/JasperHG90/Phonorm

Not sure how to fix this. Do you have any pointers?

Thanks in advance!

Jasper.

**Comment by JasperHG90** [comment]
Never mind it literally just started working!
