### ISSUE TITLE
oaiserver: OAI harvesting fails

### ISSUE THREAD

**Issue by joschirr** [zenodo/zenodo#783]
I try to harvest from
https://zenodo.org/oai2d
and encounter several serious issues:

* html tags in dc:description, e.g. https://zenodo.org/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:zenodo.org:19746
* resumptionTokens are not accepted and resulting in badResumptionToken responses or internal server errors
* incremental harvesting with day-granularity doesn't work, e.g.
https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc&from=2016-01-01

**Comment by lnielsen** [comment]
Thanks Jochen for reporting.

### HTML tags in description

This was also the case previously. I've added task to strip tags: #792

**Comment by lnielsen** [comment]
### Resumption token
Looks we currently require ``metadataPrefix`` to still be specified. We will look into fixing it.

https://zenodo.org/oai2d?verb=ListRecords&resumptionToken=.....

```
Stacktrace (most recent call last):

  File "flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "webargs/core.py", line 438, in wrapper
    return func(*new_args, **kwargs)
  File "invenio_oaiserver/views/server.py", line 100, in response
    e_tree = getattr(xml, args['verb'].lower())(**args)
  File "invenio_oaiserver/response.py", line 304, in listrecords
    record_dumper = serializer(kwargs['metadataPrefix'])
```

**Comment by lnielsen** [comment]
### Selective harvesting

Seems like we have a bug with the parameter naming (``from_`` -> ``from``):

https://zenodo.org/oai2d?verb=ListRecords&metadataPrefix=oai_dc&from_=2016-01-01

**Comment by lnielsen** [comment]
Issues opened:
- inveniosoftware/invenio-oaiserver#88
- inveniosoftware/invenio-oaiserver#87

**Comment by joschirr** [comment]
thank you.
Could you give an ETA when the fixes will be deployed.
You can imagine there are already several user requests waiting for the records ...

**Comment by lnielsen** [comment]
Probably not until Monday or Tuesday....... the from_ -> from already has a fix, but the resumptionToken not yet.

**Comment by lnielsen** [comment]
https://github.com/inveniosoftware/invenio-oaiserver/pull/91

**Comment by lnielsen** [comment]
Fixed except for the HTML tags which is logged in task #792
