### ISSUE TITLE
previewer: csv previewer should not load big csv files

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#79]
Due to performance issue with d3.js CSV rendering, we should not render CSV files bigger than X kb/mb but instead ask the user to actively press a load button.

**Comment by mdlincoln** [comment]
I'm curious what the size cutoff was set to? A ~100mb csv we've uploaded is causing browsers to hang because Zenodo is automatically trying to render it: https://zenodo.org/record/3572854
