### ISSUE TITLE
deposit: non-Zenodo DOI prevents editing

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#793]
E.g. https://zenodo.org/record/153946

**Comment by guptavaibhav18197** [comment]
@lnielsen I would like to go about fixing this issue. 
Can you please provide some more information about the bug and how can I reproduce the same?

**Comment by krzysztof** [comment]
I have checked and I could no longer reproduce this problem. This has been fixed in the meanwhile..
