### ISSUE TITLE
previewer: support image preview for larger images

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#794]
- Easy solution: Click to load if larger than X MB

**Comment by krzysztof** [comment]
Or use IIIF and cache lightweight thumbnails.

**Comment by slint** [comment]
CDSLabs is already using IIIF, so we might do for `flask-iiif` a cross-section mini-sprint (there are only minor issues at the moment) at some point to refine the package into something production-ready.

**Comment by lnielsen** [comment]
Fixed in early April

**Comment by Herrner** [comment]
Just saw this [here](https://zenodo.org/record/1287281#.Wyj_fqczY-U) - what technology was used in the end?
