### ISSUE TITLE
openaire: direct indexing of Zenodo records into OpenAIRE

### ISSUE THREAD

**Issue by dnet-team** [zenodo/zenodo#798]
When a user deposit a record in Zenodo, the record should be instantly visible in the OpenAIRE index. OpenAIRE already has APIs to do this, please refer to ticket https://issue.openaire.research-infrastructures.eu/issues/1804 . 
Here you can find an example of json record you can send to the API for direct indexing:
[test_record.json.txt](https://github.com/zenodo/zenodo/files/474804/test_record.json.txt)

**Comment by dnet-team** [comment]
Hi Lars, any plans on when this feature will be available? If you need any support on the API usage, do not hesitate to ask.

**Comment by lnielsen** [comment]
I would it expect it to land in production during December. I'll get in contact before we start implementing it.

**Comment by dnet-team** [comment]
Hi Lars, any news on this feature? It would be great to have it tested and in production in time for the review, as initially planned.

Alessia from D-Net/OpenAIRE Tech team
