### ISSUE TITLE
preview: zip file previewer should not try to preview split zip files

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#812]
https://zenodo.org/record/45900/#.V-I872VSVTM

**Comment by slint** [comment]
Actually this happens only for large splitted zipfiles files, and it probably also depends the tool/platform that was used for the splitting (Windows/Linux/OSX). Smaller files are properly previewable: https://sandbox.zenodo.org/record/61437#.V-KFZ-0vBhE. 

What can handle this properly at the moment, is catching the possible BadZipFile exception and aborting.

**Comment by slint** [comment]
Resolved through https://github.com/zenodo/zenodo/pull/786/commits/0498ad069efe7300dd5e8da196fd03cdf489457e
