### ISSUE TITLE
oaiserver: publications related to EL-CSID / H2020-693799 not exposed via zenodo OAI

### ISSUE THREAD

**Issue by joschirr** [zenodo/zenodo#825]
The community page is:
https://zenodo.org/communities/el-csid/?page=1&size=20
But the corresponding OAI link returns no records:
https://zenodo.org/oai2d?verb=ListRecords&set=user-el-csid&metadataPrefix=oai_dc
and they are also not exposed in the 'openaire' set.

What is wrong?

**Comment by lnielsen** [comment]
Jochen, we still need to run an update Monday before this is fully working.

**Comment by joschirr** [comment]
Hi,
have you initiated the update in zenodo?

**Comment by lnielsen** [comment]
It's been applied now.

**Comment by lnielsen** [comment]
I've just run https://zenodo.org/oai2d through http://oval.base-search.net which reports that date based granularity is not working even though it is, e.g:

https://zenodo.org/oai2d?verb=ListRecords&set=user-el-csid&metadataPrefix=oai_dc&from=2016-09-12&until=2016-09-13

Is this a false positive reported?

**Comment by joschirr** [comment]
The request URL you mention returns no records.
If I try with
https://zenodo.org/oai2d?from=ListRecords&metadataPrefix=oai_dc&from=2016-01-01
I get no records as well which is strange.

**Comment by joschirr** [comment]
forget about my previous comment ;-)

**Comment by joschirr** [comment]
seems the issue with validation of the incremental feature in OVAL is known already but not solved yet:
https://github.com/pietsch/oval/issues/4

**Comment by lnielsen** [comment]
👍 Thanks for checking.

**Comment by joschirr** [comment]
I provided a comment in https://github.com/pietsch/oval/issues/4
Strictly speaking the behaviour of Oval regarding incremental harvesting checks is correct concerning the OAI spec:

> the from argument must be less than or equal to the until argument

**Comment by joschirr** [comment]
still missing this record
oai:zenodo.org:153945
grouped in sets 'user-ecfunded' and 'openaire'
:-(

**Comment by krzysztof** [comment]
@joschirr FYI, we are currently working on a generic solution and patch to the system, which will address all missing records from OAI sets. Sorry about the issues so far...

**Comment by joschirr** [comment]
Could you please give an ETA?
Unfortunately, it is very urgent to have up to date metadata in OpenAIRE.
Also related is #849 , so OAI-harvesting of all records doesn't work without issues.

**Comment by lnielsen** [comment]
I hope monday.
