### ISSUE TITLE
Fail to upload larger file via API to sandbox

### ISSUE THREAD

**Issue by 7048730** [zenodo/zenodo#833]
Hello there,

when I try to upload a test file > 100 MB via python requests and Zenodo API (sandbox) using the following code

```
data = {'filename': 'test.zip'}
files = {'file': open(filename, 'rb')}
r = requests.post("https://sandbox.zenodo.org/api/deposit/depositions/%s/files?access_token=TOKEN" % deposition_id, data=data, files=files)
```

it returns http error code `413` ("413 Request Entity Too Large" which btw is not documented in zenodo API Documentation).

The same code tested with files < 100 MB works and returns `201`.

Have I reached the file size limit? (if so, it would be good to add this to the documentation). Or maybe this is due to the "requests" package - do I have to multipart put the data?

**Comment by lnielsen** [comment]
You will have to use our new file upload API (which we haven't published yet) to get files bigger than 100MB uploaded. This is because the current API uses ``application/mulitpart-formdata`` to upload the file which is not very efficient. In the new API you stream the binary content of the file in a PUT request which is much faster and doesn't require any encoding/decoding in either ends. I'll send you an example a bit later today.

**Comment by 7048730** [comment]
Thank you for looking into this! I'm excited about the example of the new API.
Maybe you want to consider the python package "requests-toolbelt" that would also allow for streaming multipart form-data objects. But I guess any solution without enconding requirements is appreciated.

**Comment by lnielsen** [comment]
Apologies for the long delay in replying to this one:

1) Find your bucket URL:
```console
$ curl -H "Accept: application/json" -H "Authorization: Bearer <access token>" "https://www.zenodo.org/api/deposit/depositions/<deposit id>"
{
  "links": {
    "bucket": "https://www.zenodo.org/api/files/<bucket id>",
    ...
  },
...
```

2) Upload a file into the bucket
```console
$ curl -X PUT -H "Accept: application/json" -H "Content-Type: application/octet-stream" -H "Authorization: Bearer <access_token>" -d @<path to local file> https://www.zenodo.org/api/files/<bucket id>/<filename>
```

Note the bucket is versioned, so in order to completely remove a file again you must use the version link. Find it from listing the bucket:
```console
$ curl -H "Accept: application/json" -H "Authorization: Bearer <access token>" "https://www.zenodo.org/api/files/<bucket id>”
{
  "contents": [
    {
      "links": {
        "version": "https://zenodo.org/api/files/<bucket id>/<filename>?versionId=<versionId>", 
        ...
      }, 
      "key": "<filename>", 
      ...
    }, 
   ...
```

Deleting the file:
```console
$ curl -X DELETE -H "Accept: application/json" -H "Authorization: Bearer <access_token>" https://www.zenodo.org/api/files/<bucket id>/<filename>?versionId=<versionId>”
```

**Comment by jakelever** [comment]
Just in case anyone comes across this, here's some Python to do the file upload part using the new API. This is equivalent to the CURL call outlined above to upload a single file. I've tested it out with 160MB file that failed with the [documented API](http://developers.zenodo.org/#quickstart-upload). This also uses requests (that the documented API uses) and simply makes a new submission and uploads a file.

``` python
r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions',
                        params={'access_token': ACCESS_TOKEN}, json={},
                        headers={"Content-Type": "application/json"})

print r.status_code

bucket_url = r.json()['links']['bucket']

deposition_id = r.json()['id']
filename='bigfile.txt'
r = requests.put('%s/%s/' % (bucket_url,filename),
                data=open(filename, 'rb'),
                headers={"Accept":"application/json",
                "Authorization":"Bearer %s" % ACCESS_TOKEN,
                "Content-Type":"application/octet-stream"})

print r.status_code
```

**Comment by 7048730** [comment]
@lnielsen @jakelever 
Do you think it is possible to stream a chunked file into the bucket using `requests.put`?
Context:
I have a set of large files that I want to zipstream without greating a zipfile in memory or on disk beforehand. I would like to pass a generator object to octet-stream of the request method.

**Comment by rdmpage** [comment]
Stumbled across this while trying to upload files using the API. For me the streaming API failed as only about half of a 986 Kb file was uploaded, resulting in a corrupt PDF. Based on http://killtheradio.net/tricks-hacks/curl-cli-not-sending-full-file-data-when-using-data-binary/ I then substituted ```-d @<path to file>``` with ```-T <path to file>``` in the curl command line and the entire file uploaded.

**Comment by ikiskin** [comment]
> Stumbled across this while trying to upload files using the API. For me the streaming API failed as only about half of a 986 Kb file was uploaded, resulting in a corrupt PDF. Based on http://killtheradio.net/tricks-hacks/curl-cli-not-sending-full-file-data-when-using-data-binary/ I then substituted `-d @<path to file>` with `-T <path to file>` in the curl command line and the entire file uploaded.

This really saved me for the uploading of a `.zip` file. Thank you. @jakelever I would suggest you could add a note to it in the original comment unless there is an entirely new method of uploading I am not aware of. Thank you!

**Comment by Ravi2712** [comment]
> Just in case anyone comes across this, here's some Python to do the file upload part using the new API. This is equivalent to the CURL call outlined above to upload a single file. I've tested it out with 160MB file that failed with the [documented API](http://developers.zenodo.org/#quickstart-upload). This also uses requests (that the documented API uses) and simply makes a new submission and uploads a file. Note that the URL used is the sandbox one.
> 
> ```python
> import requests
> 
> r = requests.post('https://sandbox.zenodo.org/api/deposit/depositions',
>                         params={'access_token': ACCESS_TOKEN}, json={},
>                         headers={"Content-Type": "application/json"})
> 
> print r.status_code
> 
> bucket_url = r.json()['links']['bucket']
> 
> filename='bigfile.txt'
> r = requests.put('%s/%s' % (bucket_url,filename),
>                 data=open(filename, 'rb'),
>                 headers={"Accept":"application/json",
>                 "Authorization":"Bearer %s" % ACCESS_TOKEN,
>                 "Content-Type":"application/octet-stream"})
> 
> print r.status_code
> ```

I had to change how to get the `bucket-url,` but other than that everything else was life saver. Thank you for sharing this. I confirm uploading 5GB of files with this code.

```
ACCESS_TOKEN = ''
ZENODO_ID = ''

r = requests.get(f'https://zenodo.org/api/deposit/depositions/{ZENODO_ID}',
                        params={'access_token': ACCESS_TOKEN}, json={},
                        headers={"Content-Type": "application/json"})

bucket_url = r.json()['links']['bucket']
print(bucket_url)
```
