### ISSUE TITLE
deposit: provide more information about the deposit bucket size on upload form

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#847]
Currently all buckets have a 50GB limit (only mentioned in fixed description).
The actual limit (which can be changed) is not indicated anywhere, nor is the current usage.
Additionally, uploading a file which would exceed the limit should raise an error with a relevant message about quota being exceeded.

**Comment by lnielsen** [comment]
> file which would exceed the limit should raise an error with a relevant message about quota being exceeded.

I thought this was already happening

**Comment by guptavaibhav18197** [comment]
@krzysztof Sir,
I would like to add this enhancement. 
Can you please give a description like what/where/how exactly is to be displayed.
What is the actual limit(the one you mentioned above)?
Where can I find the related code?

**Comment by lnielsen** [comment]
Same as #1392
