### ISSUE TITLE
deposit-ui: show a warning before publishing that files cannot be replaced

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#848]
There used to be a popup just before clicking the "Publish" button that warned about this. As of yet, there is nothing indicating that files are unchangeable after the DOI has been minted.

**Comment by lnielsen** [comment]
Currently there's:
![screen shot 2016-10-28 at 14 45 24](https://cloud.githubusercontent.com/assets/1698163/19806778/3b4c25c4-9d1d-11e6-9cc6-b5f68a6a7d12.png)

**Comment by krzysztof** [comment]
I know, but this is probably easier to sub-consciously "filter-out" than the previous pop-up. Once in a while I have file change request, where user is surprised that files cannot be changed post publishing.

**Comment by krzysztof** [comment]
I am seeing regular emails from users either discovering it post-factum or surprised that the files are frozen once the DOI is minted.

**Comment by krzysztof** [comment]
On first publishing of the deposit (and only first one, see how the button "Delete" "Discard changes" in top left are rendered), display a boostrap modal with some placeholder text and "I understand" button which continues with the publishing process.

See boostrap modal in cation: http://getbootstrap.com/javascript/#live-demo

**Comment by jrios6** [comment]
I would like to work on this enhancement :)

**Comment by jrios6** [comment]
Just to confirm that the modal is suppose to popup when the publish button is pressed for the first publish right?

**Comment by slint** [comment]
@jrios6 Yes, this is correct. You are probably going to need to include this in this [actions.html](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html) template. To determine inside the template if a deposit is already published you can use the [`recordsVM.invenioRecordsArgs.templateParams.is_published` key](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/deposit/static/templates/zenodo_deposit/actions.html#L16).

**Comment by jrios6** [comment]
@slint Thanks, will get started on it!

**Comment by jrios6** [comment]
I'm almost done with the modal. Would welcome any suggestions for the header, content, confirmation button title for the modal.
<img width="678" alt="screen shot 2017-03-25 at 5 46 50 pm" src="https://cloud.githubusercontent.com/assets/3249947/24321273/2c05fd58-1183-11e7-9702-cd9632fda2b2.png">

**Comment by jrios6** [comment]
My pull request didn't pass the Travis test. Do I have to edit any test files to account for the change in UI for publishing a record?

**Comment by rajat1994** [comment]
@jrios6 ... take a look at the travis error 
https://travis-ci.org/zenodo/zenodo/jobs/215026282

**Comment by jrios6** [comment]
@rajat1994 Saw it. Didn't get how my changes to action.html cause tests/unit/records/test_schemas_marcxml.py to fail though

**Comment by krzysztof** [comment]
Fix has been integrated here https://github.com/zenodo/zenodo/pull/1241
