### ISSUE TITLE
records-ui: long filenames should be wrapped or truncated

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#856]
Long filenames are causing buttons to extend beyond the files div:
https://zenodo.org/record/154486
Perhaps we should truncate long filenames, e.g. "Long_long_long_filename.zip" -> "Long_long_long_file..." or break it mid filename ?

**Comment by lnielsen** [comment]
I would go for wrap

**Comment by ranjanam** [comment]
@krzysztof I would like to take up this issue.

**Comment by rajat1994** [comment]
@krzysztof ... i would like to work on this issue if ranjanam is not working on it.

**Comment by krzysztof** [comment]
@rajat1994 I guess you can start taking a look
@ranjanam are you actively working on this?

**Comment by ranjanam** [comment]
@krzysztof Yes. I am working on this.

**Comment by krzysztof** [comment]
@ranjanam I guess word wrap would be better.

**Comment by jrios6** [comment]
Hi, is this bug resolved yet? @ranjanam @krzysztof

**Comment by kishansag** [comment]
@krzysztof Hey, I have tried to fix this. Are you expecting something like this https://github.com/zenodo/zenodo/pull/1076?

**Comment by krzysztof** [comment]
Fix has been integrated here https://github.com/zenodo/zenodo/pull/1241
