### ISSUE TITLE
github: review organization permision changes

### ISSUE THREAD

**Issue by bouzlibop** [zenodo/zenodo#86]
See: https://developer.github.com/changes/2014-12-08-organization-permissions-api-preview/

>Preview period:
"Staring __today__ [...]"

>Migration period:
"At the end of the preview period, we will announce the start of a migration period [...] We expect the migration period to last for four weeks [...]"

**Comment by lnielsen** [comment]
https://github.com/blog/1941-organization-approved-applications
https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/
https://developer.github.com/v3/repos/#list-your-repositories

**Comment by lnielsen** [comment]
Builds are failing in PR #135 so I move it to Sprint 4.

**Comment by bouzlibop** [comment]
@lnielsen, I've just fixed the failing tests (there was no endpoint created for `GET /user/repos`). It should works now. 

Another thing is that to make all of it working (to test new github API), I'm changing the `Accept` header to: `application/vnd.github.moondragon+json`.
