### ISSUE TITLE
record-ui: display subjects in the record info

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#860]
Since we display keywords for the record, it might make sense to display "Subjects" as well as they provide even more precise description of the record.

**Comment by behrica** [comment]
Thanks, for this. I made the original request.

We are currently evaluating to use zenodo for EFSA purposes. We see the usage of 'subjects' as an important ( internal) step to give 'standard keywords from a controlled vocabulary'.

That is why we are of course very intersted, that the 'subject' feature is working fully (in UI and acccessible via API)

**Comment by lnielsen** [comment]
@slint Has this been merged?
