### ISSUE TITLE
search: not possible to search by "subjects"

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#861]
Searching by "subjects" field is yielding no results, even query as simple as: https://zenodo.org/search?page=1&size=20&q=_exists_:subjects.

The same is true for all "nested" elastic search mapping types:
https://zenodo.org/search?page=1&size=20&q=_exists_:thesis
https://zenodo.org/search?page=1&size=20&q=_exists_:related_identifiers

see "nested" type: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/mappings/records/record-v1.0.0.json#L210

Perhaps chaning it to "object" would solve it. E.g. "contributors" field works just fine: 
https://zenodo.org/search?page=1&size=20&q=_exists_:contributors
https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/mappings/records/record-v1.0.0.json#L311

**Comment by slint** [comment]
FYI Here's an explanation between "object" and "nested" types in ES: https://www.elastic.co/blog/managing-relations-inside-elasticsearch.

From the looks of it, it seems like switching to "object" won't actually affect us. Plus, just having the ability to search I guess counters lack of it :smile:

**Comment by lnielsen** [comment]
This should just be solved with copying the required values to a common field https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/mappings/records/record-v1.0.0.json#L141

**Comment by slint** [comment]
@lnielsen I tested this and it seems to be working:
``` json
"subjects": {
  "type" : "nested",
  "properties": {
    "term": {
      "type": "string",
      "copy_to": "subject.term"
    },
    "identifier": {
      "type": "string",
      "index": "not_analyzed",
      "copy_to": "subject.identifier"
    },
    "scheme": {
      "type": "string",
      "index": "not_analyzed"
    }
  }
},
"subject": {
  "type": "object",
  "properties": {
    "term": {
      "type": "string"
    },
    "identifier": {
      "type": "string",
      "index": "not_analyzed"
    }
  }
},
```

What is the benefit though of keeping an almost duplicate key of type "nested", since we are not (at least to my knowledge) using it for any searches?
