### ISSUE TITLE
bug in metadata subjects example

### ISSUE THREAD

**Issue by bneron** [zenodo/zenodo#865]
on the web documentation API Documentation for developers ( https://zenodo.org/dev)
Resources > Representations > Deposition metadata > subjects

the example of json object for subject is :
[{"term": "Astronomy",
 "id": "http://id.loc.gov/authorities/subjects/sh85009003",
 "scheme": "url"}]

but id is not supported and the json is rejected 
the field must named 'identifier'

**Comment by krzysztof** [comment]
Closed via #866 Thanks!
