### ISSUE TITLE
duplicate

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#873]
I just discovered that we have a series of duplicates in the system. That is one record, but also one in the draft driectory https://zenodo.org/deposit?page=1&size=20&status=draft&q=communities:biosyslit

How can we clean this up? It is obvious that these are duplicates because if I want to publish the drafts, the system would not allow them, because the respective DOI are already in the system. I also find the record. These are about 200 drafts. Most likely these are leftovers from our first attempt to uplod via API. But not all drafts are in fact duplicates. possibly all the come from xBio:D Automated Upload

Is there a chance that you can on your side delete the duplicates, or do I have to do it one by one - which of course I could and spend a couple to hours

cheers
donat

**Comment by lnielsen** [comment]
We can delete **all** drafts (i.e. some 289) if that's what you want. Alternatively, it's not too hard to script in your end.

This will get you all the drafts deposits:

``GET https://zenodo.org/api/deposit/depositions/?status=draft&q=communities:biosyslit&size=300``

The iterate over the list and decide if it should be deleted. If it is to be deleted, then simply issue a 

``DELETE https://zenodo.org/api/deposit/depositions/<id>``
