### ISSUE TITLE
records-ui: info fields partial metadata display

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#875]
In record details, fields that are built from nested metadata objects ("part_of", "imprint", "journal", etc) should be checked during template rendering for some "minimum required" fields.

Example:
"Published In" field is missing publisher, but still displays only a page number: https://sandbox.zenodo.org/record/59917/export/json#.WBdjW3UrJhE

**Comment by vedantrathore** [comment]
@slint I was thinking of solving this but I was unable to find the relevant section of code, any hints?

**Comment by slint** [comment]
This has to mostly do with templates that get rendered in the "details" part of a record page (the light-grey box in the right). These templates are organized inside [zenodo/modules/records/templates/zenodo_records](https://github.com/zenodo/zenodo/tree/master/zenodo/modules/records/templates/zenodo_records).The example I mention is related specifically to [this line](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/templates/zenodo_records/box/info.html#L104), but of course there can be improvements to other parts of the page.

Keep in mind that since this is a visual/content change you should also include here in the comments screenshots of how the specific UI element looks like before and after your commit.
