### ISSUE TITLE
add different version to an existing document

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#886]
in our BLR workflow we upload PDFs, create a DOI. Sometimes, these articles are based on scans, and the data extraction is poor. For that reason we take the article, run  OCR outside, and create a new PDF with OCR underlying. 
Is there a chance that we can add this new article to the existing article as "an alternative of the same, just with OCR included"?

**Comment by lnielsen** [comment]
How soon after the publish do you want to replace the file? a day, week, month or year?

**Comment by myrmoteras** [comment]
to be cautious: openended
