### ISSUE TITLE
deposit: saving problem

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#913]
when changing the access right from closed access to open access CCBY, the document cannot be stored saved and published again . See eg https://zenodo.org/deposit/160532

**Comment by guptavaibhav18197** [comment]
@lnielsen I would like to go about fixing this issue.
Can you please provide some more information about the bug and how can I reproduce the same?

**Comment by myrmoteras** [comment]
Dear Vaibhav

Here is the issue.

https://zenodo.org/deposit/322659

This is the deposition that I made manually and then got changed through the use of our API. In this step, the author name changed, the author affiliation got deleted, the date got changed.

When I wanted to change this again, it would not work. I think, you can change this again,

The publication date should be 2017-03-31
The author should be González-Solís, David
The affiliation El Colegio de la Frontera Sur, unidad Chetumal. Av. Centenario Km 5.5, Chetumal, Quintana Roo 77014, México. E-mail: dgonzale@ecosur.mx<mailto:dgonzale@ecosur.mx>

The author should be Mariaus, Jean
The affiliation Muséum d’histoire naturelle de Genève, CP 6434, CH-1211 Geneva 6, Switzerland

The description should also include: uploaded for Revue Suisse de Zoologie by Plazi.

Access right should be Open Access, CC BY

thanks for looking into this

donat

**Comment by guptavaibhav18197** [comment]
@myrmoteras 
Sorry ,but I cant make the required changes in the above deposit as I dont have enough permission to edit it.
Still I would like to fix the bug, that is causing the problem you have mentioned.
