### ISSUE TITLE
files: scan ZIP files for  __MACOSX and  .DS_Store

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#929]
A lot of records have those hidden OSX cache files packages with the data.
Unzipping the archive and repackaging might be heavy on our servers but we should at least look at the ZIP header and alert users right in the deposit form that they have packaged it and encourage to remove them from the archive.

**Comment by krzysztof** [comment]
This task can be broken down into several simpler steps. First part of this ticket could be to write a simple function which takes a file object, checks it it's a ZIP and then returns True/False if __MACOSX or .DS_Store are present in the files (nested).

Then this could be hooked to form to display a warning next to the uploaded file.

**Comment by rusrushal13** [comment]
I want to get started with it, can I work on it?

**Comment by krzysztof** [comment]
@rusrushal13 Sure :+1: 

Best to start with a simple function which can detect if ZIP file contains any of those files inside (also in nested structures, not only root).

**Comment by rusrushal13** [comment]
@krzysztof Okay I am done with the function using the zipfile module of python
and checking the filenames. One thing I want to know is that what does nested structures meant?

**Comment by krzysztof** [comment]
Nested structure simply means looking for those files within subdirectories, not only root
