### ISSUE TITLE
pages: outdated link on Policies page

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#931]
The section "Metadata types and resources" on Policies page: https://zenodo.org/policies needs to be updated. The URL is no longer resolving properly.

**Comment by satwikkansal** [comment]
@krzysztof I'd like to work on this. As the link is broken, I tried to find an alternative link to schema, but couldn't find suitable link in https://www.openaire.eu or http://inveniosoftware.org/ 
Could you please provide the link (if you have any) or shall we considering removing this link?

**Comment by krzysztof** [comment]
Hey, this has already been fixed - we're migrating to a different documentation system.

Sorry about the confusion.
