### ISSUE TITLE
HTTP 504 error on production API

### ISSUE THREAD

**Issue by wetneb** [zenodo/zenodo#934]
Our users are not able to deposit papers in Zenodo due to an HTTP 504 error in the Zenodo API.

URL: `https://zenodo.org/api/deposit/depositions?access_token=[...]`
Server response:
```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>

```
Dissemin issue: https://github.com/dissemin/dissemin/issues/336

**Comment by wetneb** [comment]
I should mention that @sje30 tried to deposit his paper three times and the deposits all failed due to this error. There were 9 minutes between the first and the last deposit. Let me know if you need more info from the logs.

**Comment by lnielsen** [comment]
This was due to an outage of the CERN storage backend which we depend. File upload/download was down from 17:57-~20:20.  Usually we post these things on Twitter.

**Comment by wetneb** [comment]
Thanks a lot! @sje30, feel free to retry.

**Comment by bschilder** [comment]
I think this same issue might be occurring again. Though I don't see any notes about this out the Zenodo  Twitter today (just some from [Sept 1st](https://twitter.com/ZENODO_ORG/status/1565307575360421889?s=20&t=UCdrr-avyIb74wPIeSqxAA))
