### ISSUE TITLE
Broken link in email to accept/reject dataset in community

### ISSUE THREAD

**Issue by peterdesmet** [zenodo/zenodo#936]
Just got my first request to accept/reject a dataset to a community I curate. The link at the bottom has encoded apostrophes `&#39;` which Gmail renders together with the link, resulting in a broken link:

![screen shot 2017-01-03 at 14 38 05](https://cloud.githubusercontent.com/assets/600993/21609420/9a39f4a6-d1c2-11e6-954a-0419aac60344.png)

Probably better to generate the email with an unquoted link.

**Comment by slint** [comment]
Fixed via https://github.com/inveniosoftware/invenio-communities/commit/173f93ca60e2da2ea4ec0808fffbdb2b8b639b36. Pending `invenio-community` release to be integrated in Zenodo.

**Comment by slint** [comment]
`invenio-communities v1.0.0a15` is deployed now with the fix
