### ISSUE TITLE
File upload via REST API does not use the filename attribute

### ISSUE THREAD

**Issue by johanneskoester** [zenodo/zenodo#940]
When following the quickstart guide, the code

```
>>> data = {'filename': 'myfirstfile.csv'}
>>> files = {'file': open('/path/to/myfirstfile.csv', 'rb')}
>>> r = requests.post("https://zenodo.org/api/deposit/depositions/%s/files?access_token=ACCESS_TOKEN" % deposition_id, data=data, files=files)
>>> r.status_code
201
>>> r.json()
{u'checksum': u'2b70e04bb31f2656ce967dc07103297f', u'filename': u'myfirstfile.csv', u'id': u'eb78d50b-ecd4-407a-9520-dfc7a9d1ab2c', u'filesize': u'27'}
```

seems to ignore the filename attribute. When I specify something else than `myfirstfile.csv`, the file will still be named like that.

**Comment by Suor** [comment]
I make extra API call now:
```python
# Rename file, see Zenodo bug https://github.com/zenodo/zenodo/issues/940
file_desc = res.json()
if file_desc['filename'] != filename:
    res = request.zenodo.put(file_desc['links']['self'], json={'filename': filename})
    res.raise_for_status()
```

**Comment by Suor** [comment]
P.S. for me file is always named just `file`, but I am uploading from `StringIO`

**Comment by nerkn** [comment]
I tried to rename, it worked but file type is not pdf

**Comment by nerkn** [comment]
Requests takes filename from open object. filename has no effect.

**Comment by krzysztof** [comment]
You can try using the new file uploads REST API (yet undocumented, sorry), where you make a PUT to the desired filename directly:
```python
# Provide the Deposit ID, access token
depid = DEPOSIT_ID
params = {'access_token': ACCESS_TOKEN}
filename = 'CMSSM.hdf5'

# Get the deposit resource as in the old API
headers = {'Content-Type': 'application/json'}
r = requests.get('https://zenodo.org/api/deposit/depositions/{depid}'.format(depid=depid),
                 params=params, json={}, headers=headers)

# In new files API we use a PUT request to a 'bucket' link, which is the container for files
bucket_url = r.json()['links']['bucket']  # bucket url looks like this: 'https://zenodo.org/api/files/12341234-abcd-1234-abcd-0e62efee00c0' 
# We pass the file object (fp) directly to request as 'data' for stream upload
# the target URL is the URL of the bucket and the desired filename on Zenodo seprated by slash
with open(filename, 'rb') as fp:
    requests.put(bucket_url + '/' + filename,
                 params=params, headers=headers,
                 data=fp)
```

**Comment by nerkn** [comment]
I store files to my computer then post to zenodo :)

  filesF = requests.get('http://myserver/publications/%s/zenodo' % pub['id'], params={}, headers=headersWaset)
  fileobj = open(filename, 'w');
  fileobj.write(filesF.content)
  fileobj.close();
  fileobj = open(filename, 'r');

**Comment by frankois** [comment]
Thanks for raising the issue. Indeed the proper attribute to set the filename is 'name':
``data = {'name': 'myfirstfile.csv'}``

This has now been fixed in the documentation: https://github.com/zenodo/developers.zenodo.org/commit/447077a47b98bcf876300965b3fcc0ca2784b271
