### ISSUE TITLE
lektor for general docs

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#946]
- [x] about/help

**Comment by krzysztof** [comment]
- [ ] Fix the sub nav-bar
- [ ] Fix the non-rendering icons/images
- [ ] Fix the whatsnew page
 - [ ] Write a model for tiling the features
 - [ ] Full-page layout
- [ ]

**Comment by egabancho** [comment]
@krzysztof unfortunately I couldn't do my, always underestimated, educational work, and show you an example of what computer security can do for you in your daily basis ;-)

**Comment by krzysztof** [comment]
- [ ] Zenodo.org changes:
  - [ ] Unify Zenodo.org footer with new footer from Docs.
  - [ ] Add redirects to pages (/contact, /about, etc.)
- [ ] Set up travis key authentication
- [ ] Fix the sub-navigation shadow on the hover items (should extent to full height of the bar)

**Comment by krzysztof** [comment]
Done in the docs, Zenodo.org changes in https://github.com/zenodo/zenodo/pull/968
