### ISSUE TITLE
openaire: harvest grants from all funders in openaire

### ISSUE THREAD

**Issue by lnielsen** [zenodo/zenodo#949]

**Comment by krzysztof** [comment]
This requires some work on invenio-openaire in order to have the grants/funders being updated periodically. At the moment it's a one-pass task which gets everything and pushed everything.

**Comment by krzysztof** [comment]
Related: https://github.com/zenodo/zenodo/issues/617

**Comment by krzysztof** [comment]
This is probably fast (1-2 days) once #617 is done.

**Comment by krzysztof** [comment]
All supported funders and grants were added around Oct. 10th. We still need to work-out a solution for automatic re-harvesting. Closing since this issue is more relevant to that: https://github.com/zenodo/zenodo/issues/617
