### ISSUE TITLE
viewer

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#953]
Are there any plans to develop a viewer that allows to see mutliple images at the same time? May be even deselect or move them around?  An example is this viewer from GBIF

https://demo.gbif.org/occurrence/gallery?basis_of_record=PRESERVED_SPECIMEN&taxon_key=6

![image](https://cloud.githubusercontent.com/assets/4609956/22116838/122616d2-de72-11e6-9c48-bc999ee6ceec.png)

**Comment by lnielsen** [comment]
Duplicate of #962
