### ISSUE TITLE
Problem installing Zenodo with Docker

### ISSUE THREAD

**Issue by suso2** [zenodo/zenodo#956]
Hi.
When I run "docker-compose up", I constantly get this error:

_frontend_1 | 172.17.0.12 - - [28/Jan/2017:12:47:59 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
db_1       | ERROR:  relation "pages_page" does not exist at character 347
db_1       | STATEMENT:  SELECT pages_page.created AS pages_page_created, pages_page.updated AS pages_page_updated, pages_page.id AS pages_page_id, pages_page.url AS pages_page_url, pages_page.title AS pages_page_title, pages_page.content AS pages_page_content, pages_page.description AS  pages_page_description, pages_page.template_name AS pages_page_template_name_

Thanks for your help

**Comment by suso2** [comment]
I tried to follow the instructions and I have a new problem. When I run
"docker-compose run --rm web zenodo fixtures loaddemorecords" I get this error.

jmartin@ubuntuzenodo:~/zenodo$ docker-compose run --rm statsd bash /init.sh
{"acknowledged":true}jmartin@ubuntuzenodo:~/zenodo$ docker-compose run --rm web zenodo fixtures loaddemorecords
/usr/local/lib/python3.5/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
Traceback (most recent call last):
  File "/usr/local/bin/zenodo", line 11, in <module>
    load_entry_point('zenodo', 'console_scripts', 'zenodo')()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/cli.py", line 345, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1055, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1094, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.5/site-packages/flask/cli.py", line 316, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.5/site-packages/flask/cli.py", line 201, in load_app
    rv = self.create_app(self)
  File "/usr/local/lib/python3.5/site-packages/invenio_base/app.py", line 159, in create_cli_app
    app = create_app(debug=get_debug_flag())
  File "/usr/local/lib/python3.5/site-packages/invenio_base/app.py", line 133, in _create_app
    app.wsgi_app = wsgi_factory(app, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/invenio_base/wsgi.py", line 66, in create_wsgi
    wsgi_app = factory(app, **kwargs) if factory else app.wsgi_app
  File "/code/zenodo/zenodo/factory.py", line 97, in create_wsgi
    client = StatsClient(prefix=prefix, host=host, port=port)
  File "/usr/local/lib/python3.5/site-packages/statsd/client.py", line 139, in __init__
    host, port, fam, socket.SOCK_DGRAM)[0]
  File "/usr/local/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

Any suggestion is welcome. Thanks

J. Martin

**Comment by lnielsen** [comment]
It looks like it does not find the [StatsD server]( https://github.com/zenodo/zenodo/blob/master/docker-compose.yml#L79-L88). Did you initialize it - i.e. ``docker-compose run --rm statsd bash /init.sh``?

**Comment by suso2** [comment]
Thanks for your answer. I tried again:
1. Clean installation Debian-8.7.1-amd64
2. Docker client and server 1.13.0
docker-compose version 1.10.0, build 4bd6f1a

3. git clone https://github.com/zenodo/zenodo.git (ok)
4. cd zenodo
5. git checkout master (ok)
6. docker-compose build (error)

Step 16/24 :
/usr/local/lib/python3.5/site-packages/dojson/contrib/to_marc21/model.py:22: UserWarning: MARC21 undo feature is experimental
  warnings.warn('MARC21 undo feature is experimental')
npm WARN package.json zenodo@3.0.0-dev20150000 No description
npm WARN package.json zenodo@3.0.0-dev20150000 No repository field.
npm WARN package.json zenodo@3.0.0-dev20150000 No README data
npm WARN package.json zenodo@3.0.0-dev20150000 No license field.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webcanvas/angular-schema-form-ckeditor.git /root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webcanvas/angular-schema-form-ckeditor.git /root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e: fatal: unable to connect to github.com:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webcanvas/angular-schema-form-ckeditor.git /root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e: github.com[0: 192.30.253.112]: errno=Connection timed out
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webcanvas/angular-schema-form-ckeditor.git /root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e: github.com[1: 192.30.253.113]: errno=Connection timed out
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/webcanvas/angular-schema-form-ckeditor.git /root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-webcanvas-angular-schema-form-ckeditor-git-4e90803e'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.112]: errno=Connection timed out
npm ERR! github.com[1: 192.30.253.113]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/var/instance/static/npm-debug.log
ERROR: Service 'static' failed to build: The command '/bin/sh -c zenodo npm     && cd ${APP_INSTANCE_PATH}/static     && npm install     && cd /code/zenodo     && zenodo collect -v     && zenodo assets build' returned a non-zero code: 1

I tried three times and always got the same error...

Thanks for your help

**Comment by suso2** [comment]
Firewall problem. Thanks...
