### ISSUE TITLE
error disconnecting github

### ISSUE THREAD

**Issue by satra** [zenodo/zenodo#957]
i'm trying to add an organization that wasn't added when i first signed up. it seems there is no way to do using the zenodo ui. so i decided to disconnect and reconnect github, but when i click disconnect, it results in the following message.

```
 Internal server error
Error identifier: 71e44156105346c69b03914aeb77eaac
```

**Comment by satwikkansal** [comment]
I tried to reproduce the error you're facing but I can't. For me it works as expected.

**Comment by slint** [comment]
Related to https://github.com/inveniosoftware/invenio-github/issues/46

**Comment by slint** [comment]
Closed via https://github.com/inveniosoftware/invenio-github/pull/53
