### ISSUE TITLE
Text search (communities): case sensitive

### ISSUE THREAD

**Issue by par4dise** [zenodo/zenodo#964]
When [searching for communities](https://www.zenodo.org/communities), if you don't type the community title **exactly** as it was defined by the creator, no chance find what you're looking for.
Check by yourself:

1. [Search for "human brain"](https://www.zenodo.org/communities/?p=human+brain) --> no result
2. [Search for "Human Brain"](https://www.zenodo.org/communities/?p=Human+Brain) --> expected result

Very, very restrictive in my opinion.

**Comment by krzysztof** [comment]
@jainaman224 Feel free to take a look. I don't think anyone else is looking into this right now.

**Comment by slint** [comment]
@jainaman224 This is related to https://github.com/inveniosoftware/invenio-communities/issues/99, which as you can see though resides in another repository of the Invenio framework that Zenodo is based on. This will involve pushing changes to `invenio-communities`. To start, first fork the `invenio-communities` repository, fix the issue locally, test it, and once you're done let us know here (include a URL to your fork). We will then take a look at it and help you open a PR on `invenio-communities`.

**Comment by jainaman224** [comment]
@slint Thank you.

**Comment by jainaman224** [comment]
@slint Please have a look at https://github.com/jainaman224/invenio-communities/tree/patch-1.

**Comment by slint** [comment]
@jainaman224 Looks good! It would be also great if you could also write some basic tests for these changes. Take some inspiration from the already existing tests in [the tests directory](https://github.com/inveniosoftware/invenio-communities/blob/master/tests), and create a similar `test_models.py` file, where you test some basic use cases for your changes.

**Comment by jainaman224** [comment]
@slint @krzysztof Please have a look at https://github.com/inveniosoftware/invenio-communities/pull/100.

**Comment by krzysztof** [comment]
The PR has been merged: https://github.com/inveniosoftware/invenio-communities/pull/100

invenio-communities release and integration is still needed.

**Comment by lnielsen** [comment]
Closing in favour of #1050
