### ISSUE TITLE
Licenses controlled list missing in API docs

### ISSUE THREAD

**Issue by 7048730** [zenodo/zenodo#965]
Small issue here: there seems to be a dead end in [this line](https://github.com/zenodo/zenodo/blob/cc9b16034be0b837aec8c8a9a8873a72c63f9826/zenodo/modules/fixtures/data/pages/api.html#L1413)

`zenodo/zenodo/modules/fixtures/data/pages/api.html`

    ...
    <a href="https://zenodo.org/kb/export?kbname=licenses&format=kba">here</a>
    ...

I was hoping to find the controlled vocabulary for the zenodo license sets.

**Comment by lnielsen** [comment]
Solved via the new REST API documentation in developers.zenodo.org

**Comment by rusrushal13** [comment]
Are the new Rest API documentation is released?
