### ISSUE TITLE
preview: error messasges

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#966]
recently, this message often shows up when downloading for the first time the image

![image](https://cloud.githubusercontent.com/assets/4609956/23101929/79aeb49a-f69f-11e6-9652-4e8e6159ff13.png)

sometimes this broken images shows up 
![image](https://cloud.githubusercontent.com/assets/4609956/23101944/b0b59e36-f69f-11e6-81de-ad8e6f4b91ac.png)
 https://zenodo.org/record/293171#.WKmCjagrLAQ

**Comment by lnielsen** [comment]
Are you stilling persistently having this issue?
