### ISSUE TITLE
oauth2server: revoke token endpoint

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#967]
We (or `invenio-oauth2server`) seem to be missing a token revocation endpoint, which causes the `/account/settings/applications/` view to crash for users that have Authorized Applications because of failure to generate the [revoke token url](https://github.com/inveniosoftware/invenio-oauth2server/blob/master/invenio_oauth2server/templates/invenio_oauth2server/settings/index.html#L86).

**Comment by lnielsen** [comment]
@slint was this fixed?

**Comment by slint** [comment]
Yes, we were just waiting confirmation also from a ticket before closing. Revoke button renders and works as expected.
