### ISSUE TITLE
serialization: DataCite serializer changes all-caps words

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#969]
See for example capital "JSON" and "TSV" in the title here: https://zenodo.org/record/268568
and its DataCite serialization: https://zenodo.org/record/268568/export/dcite3#.WKv2wPH6wUE ("Json", "Tsv").
The up-case serialization is also what ends up in DataCite: https://search.datacite.org/works/10.5281/ZENODO.268568

**Comment by satwikkansal** [comment]
@krzysztof I found that the serializer `datacite_31` is initialized in  `zenodo/modules/records/serializers/__init__.py`.

And there's an import in that file
```py
from invenio_records_rest.serializers.datacite import DataCite31Serializer
```
But `invenio_records_rest` but it's not the part of zenodo repository. So where exactly should I make changes :sweat_smile:

**Comment by AvaisP** [comment]
Hey @satwikkansal 
I'm already working on this issue. If possible, please try working on another issue so that we don't end up putting in twice the amount of effort required in this issue. Thanks!

**Comment by krzysztof** [comment]
True, the datacite serializer is not in Zenodo but in an invenio-records-rest. If the fix is to end up there, it's a PR to https://github.com/inveniosoftware/invenio-records-rest.
However, the ``DataCiteSchemaV1`` lives in Zenodo: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/schemas/datacite.py
(Take a look at the constructor of the serializer: https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/__init__.py#L74

You can think of serializer as just a mapping function, and of the schema as 'the mapping' itself. Whether this bug is in the serializer or the schema I'm not sure - you'll have to check both places (use ipdb and see at which point the data is lower-cased).

Finally some tips:

1. Check if this is only for title, or if it's for any field (description, author, keywords etc.). If it's a single field it's probably easily fixable in the schema. If it's all strings that are lower-cased it might be some serializer issue.
2. If the change is to be in the serializer (invenio-records-rest), you'll have to make a PR to that Invenio module. For the time being here's a guide on how to test checkout and test Invenio modules locally: http://zenodo.readthedocs.io/en/latest/development/guide.html

**Comment by lnielsen** [comment]
Is there any progress or PR on this issue? Just to know if it is being worked on and what the state is.

**Comment by slint** [comment]
This one's pretty sneaky: the [title field in the DataCite marshmallow schema](https://github.com/zenodo/zenodo/blob/e7f4be30ca1832a12c6d51c727205276502de85f/zenodo/modules/records/serializers/schemas/datacite.py#L82), doesn't need to be `Nested`. What happens is that marshmallow actually calls `str.title()` for the `metadata.title` field, thus producing the weird title casing...
