### ISSUE TITLE
deposit: missing value in related identifier in API uploads

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#970]
The automatic upload of new articles often does not complete the last related identifier. According to our input, the attribut eg "is part of this upload"

![image](https://cloud.githubusercontent.com/assets/4609956/23259521/c2fe839c-f9cd-11e6-83e0-ffc655297ca6.png)

https://zenodo.org/deposit/321255

This then has the consequence, that after editing the record cannot be saved anymore.

other unfixed examples are 
https://zenodo.org/deposit/321799
https://zenodo.org/deposit/321798
https://zenodo.org/deposit/321790

**Comment by lnielsen** [comment]
Seems like the alternate identifier option is missing in the deposit ui. @slint Can you please have a look?
