### ISSUE TITLE
docker: statsd error 'The super constructor "inherits" must not be null or undefined'

### ISSUE THREAD

**Issue by ttgil95** [zenodo/zenodo#985]
Hello, I have been trying to use docker installation to install Zenodo but have been running into a few issues when doing so. When I try running the docker-compose up command, I receive the following errors:

statsd_1    | TypeError: The super constructor to "inherits" must not be null or undefined
statsd_1    |     at Object.exports.inherits (util.js:967:11)
statsd_1    |     at Object.<anonymous> (/usr/local/lib/node_modules/statsd/lib/config.js:33:6)
statsd_1    |     at Module._compile (module.js:571:32)
statsd_1    |     at Object.Module._extensions..js (module.js:580:10)
statsd_1    |     at Module.load (module.js:488:32)
statsd_1    |     at tryModuleLoad (module.js:447:12)
statsd_1    |     at Function.Module._load (module.js:439:3)
statsd_1    |     at Module.require (module.js:498:17)
statsd_1    |     at require (internal/module.js:20:19)
statsd_1    |     at Object.<anonymous> (/usr/local/lib/node_modules/statsd/stats.js:4:14)
statsd_1    | util.js:967
statsd_1    |     throw new TypeError('The super constructor to "inherits" must not ' +

later followed by:

frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:06:40 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:06:43 +0000] "HEAD /ping HTTP/1.0" 500 0 "-" "-" "-"
frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:06:45 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:06:50 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:06:55 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"
frontend_1  | 172.17.0.12 - - [01/Mar/2017:22:07:00 +0000] "HEAD /static/ping HTTP/1.0" 200 0 "-" "-" "-"

Then, I tried running the docker-compose run --rm web bash /code/zenodo/scripts/init.sh while keeping the session with the docker-compose above alive, and in a new shell and receive the following error:
pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/usr/local/bin/zenodo", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3014, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3043, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zenodo' distribution was not found and is required by the application

**Comment by krzysztof** [comment]
@ttgil95 Did you have the newest master branch? Starting with this commit: https://github.com/zenodo/zenodo/commit/41d8a2507bbb3b562a3a9b94620b2284410812eb and following the updated installation guide, the docker installation should go smoothly.

**Comment by rajat1994** [comment]
@ttgil95 ... try running sudo docker-compose up 
cheers :)

**Comment by krzysztof** [comment]
Or better: http://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

I'm not sure that was the problem though.

**Comment by rajat1994** [comment]
try installing docker-compose via pip  ...    pip install docker-compose
may be it can solve the issue

**Comment by krzysztof** [comment]
I guess the issue has been resolved? Reopen if still experiencing this error.

**Comment by ttgil95** [comment]
I've tried running sudo docker-compose up and I'm still getting the same errors. Also, I do have the newest master branch. Not sure where to go from here

**Comment by rajat1994** [comment]
@ttgil95 ...you should check the troubleshooting guide.
https://github.com/zenodo/zenodo/wiki/Troubleshooting

**Comment by krzysztof** [comment]
@ttgil95 Also it seems that it's the full-stack installation that's crashing. Can you please try to move to the Developer installation (run only four nodes using docker)

**Comment by krzysztof** [comment]
@ttgil95 Were you able to run Zenodo on docker?
