### ISSUE TITLE
deposit-ui: licenses suggestions need some tuning

### ISSUE THREAD

**Issue by krzysztof** [zenodo/zenodo#986]
Finding "Creative Commons Zero - CC0 1.0" license is hard to find.

The following searches don't bring it up:

- "Zero"
- "CC0"

You can find it with "Creative Commons Zero", which is not the first thing people look for.

**Comment by rajat1994** [comment]
Can't we simply explain "Creative Commons Zero - CC0 1.0" in one or two lines  under the license section so that people don't need to search it?

**Comment by lnielsen** [comment]
Moved to Invenio-OpenDefinition repo.
