### ISSUE TITLE
write access to deposition that have been added to BLR

### ISSUE THREAD

**Issue by myrmoteras** [zenodo/zenodo#991]
in our workflow we extract facts from documents that are deposited at Zenodo and are part of the Biodiversity Literature Community, deposit them on Zenodo or our TreatmentBank and then add those related identifiers to the source document. These documents are either uploaded through our BLR account, or then asked to be included in the BLR community.

In the latter case, we cannot add additional links to the facts or images we extracted. Is there a way we could have write access to add such links?
![image](https://cloud.githubusercontent.com/assets/4609956/23653447/e0c35a2a-032c-11e7-8221-db81e3c65a92.png)

**Comment by lnielsen** [comment]
It will be possible once we get around to doing community teams (#35) and allow curators access to edit metadata.
