### ISSUE TITLE
serializers: BibTex escape special characters

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo#997]
Current BibTex export is not escaping special characters such as ampersands ("&"), causing trouble in applications that use LaTeX. Example record: https://zenodo.org/record/345946/export/hx.

A list/sepcification of these special characters should be found and escaped during serialization using backslashes (eg. `{ Some subject \& another subject }` ). More information can be found in [this SO thread](http://tex.stackexchange.com/questions/7198/how-to-escape-the-ampersand-character-in-bibtex).

**Comment by vedantrathore** [comment]
@slint I'd like to tackle this, so I need to find the serializer and escape the "&" right?

**Comment by slint** [comment]
@vedantrathore Yes, you should take a look at the [BibTex serializer](https://github.com/zenodo/zenodo/blob/master/zenodo/modules/records/serializers/bibtex.py). Try also to do some investigation and find more special characters that BibTex doesn't play along with (a lot of people use LaTeX editors/compilers that throw errors about certain characters). If possible provide a solution that allows this set of characters to be configurable so that it's easy in the future to add more of them.

**Comment by vedantrathore** [comment]
@slint I was thinking of adding this method to Bibtex serializer, what do you think?

```python
    def _clean_input(self,input):
        unsupported_char = ['&']
        chars = input.split('')
        for char in chars:
            if char in unsupported_char:
                char = "\\" +char
        return ''.join(chars)
```

**Comment by daas-ankur-shukla** [comment]
@krzysztof i want to work on this. may i start?

**Comment by slint** [comment]
@vedantrathore Do you have a work-in-progress PR or a branch for this issue? I can't recall if we ever addressed your question in private or as a comment in a PR/commit.

**Comment by vedantrathore** [comment]
@slint I have updated code in my local machine but I needed your validation on that method so never pushed it, actually my mid semester exams were finished 2 days ago so couldn't do it yet. can you please check if that method I posted will do the job? thanks :)

**Comment by krzysztof** [comment]
Fix has been integrated here https://github.com/zenodo/zenodo/pull/1241
